### ISSUE TITLE
Sample dashboard works for InfluxDB but not Graphite

### ISSUE THREAD

**Issue by dnsmichi** [Mikesch-mp/icingaweb2-module-grafana#1]
Furthermore it specifies the Grafana datasource with a hardcoded name. Requires proper documentation.

**Comment by Mikesch-mp** [comment]
Hmm when i import the dashboard it asks me to select a datasource. I tested it with fresh installations of Grafana. Maybe i add also a Graphite one (have to install it first.

**Comment by dnsmichi** [comment]
I did not test it, just looking into the dashboard's sourcecode. I did not know that Grafana will ask you to select the datasource (at least I haven't seen it in 3.x). Might be worth a note in the docs too, that (and where) you'll have to define the datasource.

**Comment by Mikesch-mp** [comment]
I wrote that Grafana >= 4.1 is a requirement, but maybe i will install some other versions and test it if the work the same way.

**Comment by markusr** [comment]
I can confirm that Grafana 4 will ask for datasource to use. 

![grafik](https://cloud.githubusercontent.com/assets/1866703/23486150/0416662c-fedf-11e6-8366-2e63d4483d2f.png)

The selected data source must however of the same type as defined in imported json. I think Grafana cannot automatically convert influx dashboards to graphite dashboards.

**Comment by dnsmichi** [comment]
One further reason I was asking was to automatically import that dashboard inside the Icinga Vagrant boxes (I'd like to show the integration next week during my talk). I might look into that myself but still got some other tasks to prepare ;)

**Comment by Mikesch-mp** [comment]
Added support for graphite with 1.0.3.
