### ISSUE TITLE
merge the 2 module-grafana projects

### ISSUE THREAD

**Issue by marcofl** [Mikesch-mp/icingaweb2-module-grafana#10]
We should try to merge the two module-grafana projects. From what I see it's very similar. What do you think? 
https://github.com/vshn/icingaweb2-module-grafana

**Comment by Mikesch-mp** [comment]
Hi,
can we do a talk via skype?  Join https://join.skype.com/o9tp1jk5UCsQ

**Comment by Mikesch-mp** [comment]
Since no one from vhsn ever contacted me or even answer me i close this :(
