### ISSUE TITLE
Graph displayed doesn't match the service

### ISSUE THREAD

**Issue by pirona** [Mikesch-mp/icingaweb2-module-grafana#100]
## Expected Behavior
When I click on a service, I see the corresponding graph.

## Current Behavior
When I click on a service, I always se the host-alive check->

I really don't know where to look here.
I installed Icinga, with graphite as a backend and grafana for display (with your excellent dashboard)
After a very hard time to make it work, I'm not sure where to look now. Can you point me somewhere ? 

![image](https://user-images.githubusercontent.com/31767324/30744072-b66eb420-9fa0-11e7-98a1-ab07e821ce34.png)

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.1.10
* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian 8.9
* Enabled features (`icinga2 feature list`):

Disabled features: compatlog debuglog gelf influxdb livestatus opentsdb statusdata

Enabled features: api checker command graphite ido-mysql mainlog notification perfdata syslog

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: MON-DEB8-04
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 1 SyslogLogger.
information/ConfigItem: Instantiated 2 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 20 Notifications.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 18 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Mikesch-mp** [comment]
Hello,
which dashboard do you use as your default dashboard? Please post also your grafana module and graph configuration.

Regards,
Carsten

**Comment by pirona** [comment]
Sure,

![image](https://user-images.githubusercontent.com/31767324/30803283-569d5c9a-a1e9-11e7-9315-93981db288ac.png)

![image](https://user-images.githubusercontent.com/31767324/30803320-7c955a42-a1e9-11e7-8224-92242e4b1eb9.png)

![image](https://user-images.githubusercontent.com/31767324/30803445-f279f0ce-a1e9-11e7-9545-28b429df9eb9.png)


![image](https://user-images.githubusercontent.com/31767324/30803358-9f6ea12c-a1e9-11e7-8a97-9d64037f8dda.png)


![image](https://user-images.githubusercontent.com/31767324/30803402-c3aceb5c-a1e9-11e7-887a-5c6b7c6063e6.png)

**Comment by pirona** [comment]
I must precise this : 

Whenever I want to add a graph, I got a time out. For instance : 

![image](https://user-images.githubusercontent.com/31767324/30807748-7549adbc-a1fb-11e7-989e-70b05d7013d3.png)

![image](https://user-images.githubusercontent.com/31767324/30807751-7f6c9390-a1fb-11e7-8dc9-e74c5756ef47.png)

**Comment by Mikesch-mp** [comment]
Got it :) The icinga-default template that is shiped with the module has only one panel. If configured in the main configuration, this dashboard is used when no other graph is configured like you tried in your last screenshot. If you want other graphs then the default you must create your own dashboards with panels or use the provided base-metric for example.

**Comment by pirona** [comment]
That was mu thought too. But how can I see those panels in grafana then ? 
I name my dashboard icinga-default, but it comes with several panels.

May be I'm getting this the wrong way ? 

![image](https://user-images.githubusercontent.com/31767324/30845659-baea39ba-a294-11e7-9966-0f66e822ed7d.png)

**Comment by Mikesch-mp** [comment]
Hi,

please dont use this es default dashboard. The one that is provided with the module will generate a graph with the vars the module will send to Grafana. If you want to use this dashboards panels you have to configure them in the Graph configuration of the module.

Regards,
Carsten

**Comment by pirona** [comment]
Ok thank you. I must have missed that part.

I'm using base-metrics and it's ok now.

Beautiful 👍 

![image](https://user-images.githubusercontent.com/31767324/30911039-4e38d03a-a387-11e7-959a-0913c8e6a264.png)

**Comment by pirona** [comment]
Hmm actually. Im still having issue.

All the services are displaying the same graph (ping4)

How can I change this ?

**Comment by Myriagone** [comment]
Hello, where is "graphite-icinga2-default" ? On grafana or on icingaweb2 ? Or maybe config file ?

Thk.

**Comment by MaRoMa1** [comment]
Hello,
I don't know how I can install graphite in icinga, I active graphite in icngaweb but I have this problem 
![image](https://user-images.githubusercontent.com/39944645/40969613-a29d0f14-68b8-11e8-8f7a-3a7f6d3f4cc5.png)

Any person can help me?
thank you a lot
