### ISSUE TITLE
Update releases

### ISSUE THREAD

**Issue by druchoo** [Mikesch-mp/icingaweb2-module-grafana#104]
## Expected Behavior

[releases](https://github.com/Mikesch-mp/icingaweb2-module-grafana/releases) should match [module.info](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/module.info)

## Current Behavior

Latest release is 1.1.8 but module info is 1.1.10

## Possible Solution

Release 1.1.9/1.1.10

## Steps to Reproduce (for bugs)

Have a look at:
* [releases](https://github.com/Mikesch-mp/icingaweb2-module-grafana/releases) 
* [module.info](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/module.info)

## Context

Have to use git revisions in [Puppet module](https://github.com/Icinga/puppet-icingaweb2).

**Comment by Mikesch-mp** [comment]
Hi,
Master is not the releases.

Regards,
Carsten
