### ISSUE TITLE
Create new dashboards for ITL plugins

### ISSUE THREAD

**Issue by Mikesch-mp** [Mikesch-mp/icingaweb2-module-grafana#105]

**Comment by dnsmichi** [comment]
How would one import that in an automated fashion? Those are many small files :-)

**Comment by Mikesch-mp** [comment]
This is only one time doing, to automate it takes for sure more time then importing the ones you need by hand. They are more examples to get the users to make them by themself after reading the docs for [influx](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/06-create-grafana-dashboards-influxdb.md) or [graphite](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/06-create-grafana-dashboards-graphite.md). And why not one big dashboard? i learned Grafana loads all panels on a dashboard or at least try to load them, if you have only 1 panel inside, its on big environments with a lot of users a lot faster.

**Comment by Mikesch-mp** [comment]
Du machst mich fertisch :) Muss nu aber erstmal los Richtung Zwickau
