### ISSUE TITLE
Error after upgrading to Icinga Web 2 v2.5.0

### ISSUE THREAD

**Issue by clemensloebig** [Mikesch-mp/icingaweb2-module-grafana#106]
After upgrading to Icinga Web 2 v2.5.0 the Grafana module from https://github.com/Mikesch-mp/icingaweb2-module-grafana
brings follow errors:
ErrorException in /usr/share/php/Icinga/File/Ini/IniParser.php:263 with message: syntax error, unexpected END_OF_LINE, expecting ‘=’ in Unknown
and so on….

**Comment by Mikesch-mp** [comment]
Module Version?
PHP Version ?
Post content of your modules config.ini please

**Comment by clemensloebig** [comment]
PHP 7.0.22-0 

grafana module version 1.1.10

[grafana]
username = "icingaweb2"
host = "grafana.DOMAIN.de"
protocol = "https"
password = "....."
height = "280"
width = "640"
timerange = "3h"
enableLink = "yes"
defaultdashboard = "icinga2-default"
datasource = "graphite"
defaultdashboardstore = "db"
accessmode = "proxy"
usepublic = "no"
custvardisable = "idontwanttoseeagraph"
theme = "light"
authanon = "no"
proxytimeout = "90"

**Comment by Mikesch-mp** [comment]
What you click on when that error happens. So far everything looks good to me

**Comment by clemensloebig** [comment]
i try to view a service in icingaweb with the graph, and also when i click Konfiguration=>Grafana Graphs

**Comment by clemensloebig** [comment]
![icingaweb-grafana-issue](https://user-images.githubusercontent.com/10742891/33378517-587d6d66-d515-11e7-8e59-a01132ce5dfa.PNG)

**Comment by clemensloebig** [comment]
currently i have only the config.ini in /etc/icingaweb2/modules/grafana/

Thanks for Help

**Comment by dnsmichi** [comment]
Another round - your screenshot stacktrace gives a config snippet your can grep for in /etc/icingaweb2. 

```
grep -r '[disk]' /etc/icingaweb2
```

**Comment by clemensloebig** [comment]
i found the issue.
it was one line in the file commented out with # after removing the line, it works.
why it doesn't work with the commented line?

**Comment by dnsmichi** [comment]
The ini format spec requires you to use `;` for comments. It might be that this error was hidden silently somewhere, and a fixed bug in the framework makes this now visible.

**Comment by clemensloebig** [comment]
yes can be, thanks for your help and your time

**Comment by Mikesch-mp** [comment]
Thanks @dnsmichi :) and iam glad he could solve your problem.
