### ISSUE TITLE
Time used by graphs in Icingaweb2

### ISSUE THREAD

**Issue by omattsson** [Mikesch-mp/icingaweb2-module-grafana#107]
Hi,

I'm wondering if it is possible to change so when viewing the graphs in Icingaweb browser time (or a configurable time zone) is used? When clicking on the graph and viewing it directly in Grafana browser time is used. When viewing in Icingaweb the server time is used.
This would make it less confusing for the users if the data displayed shows the same time span.

Brgds
Olof Mattsson

**Comment by Mikesch-mp** [comment]
Hi,

it should be the same behavior. Can you check if your icingaweb2 profile uses a different timezone please, normally it should be set to browser timezone.

Regards,

Carsten

**Comment by omattsson** [comment]
Hi,

The server time is set to UTC. We set php.ini date.timezone = "Europe/Stockholm". The Icingaweb2 users have Europe/Stockholm set in their profile.
When I create downtimes in Icingaweb the correct timezone is used. 

Brgds
Olof Mattsson

**Comment by Mikesch-mp** [comment]
If you use proxy mode the timezone set in php.ini is used (because of serverside rendering). Can you please verify that you php instance is using the correct timezone?
