### ISSUE TITLE
Using "hostdisplayname" as a parameter for graph generation

### ISSUE THREAD

**Issue by codingwatermelon** [Mikesch-mp/icingaweb2-module-grafana#109]
Hello!

I'm using v1.1.10 of the module and was wondering if there could be a way to use the host display name instead of the host name to dynamically assign graphs to hosts. Let me elaborate:

I have configured the InfluxDBwriter from MySQL (Icinga2) to InfluxDB (Grafana) to send the host display name as well as the host name. That way, I can use the display name instead of the host name for better display on Grafana dashboards (e.g., a host with host name "PV3820iMGMT11" has display name "PV 3820i MGMT 1/1"). However, as it is, I cannot use the host's display name to populate graphs in Icingaweb2, only the host name. This leaves me with ugly names for the graphs as mentioned above.

If I try to use the host's display name (similarly, if I omit the name altogether and statically assign a name for the graph), it will pull the graph from only first host from the list of hosts from Grafana for all hosts in Icingaweb, therefore, the graph that I want for each host will be the **same** for each and every host.

Perhaps I'm doing this incorrectly. If so, please let me know what I could be doing wrong. If not, please implement this functionality!

If I have not explained this feature request well enough, please let me know.

Thanks in advance!

**Comment by Mikesch-mp** [comment]
Can you upload an image of an graph using the host displayname please? I dont get it really.
