### ISSUE TITLE
Add a regex field to match a graph to a service

### ISSUE THREAD

**Issue by cstegm** [Mikesch-mp/icingaweb2-module-grafana#112]
Hi,
I have some Services named like:

- "Logical Disk C Avg Disk per Sec Read" 
- "Logical Disk D Avg Disk per Sec Read" 
- "Logical Disk C Avg Disk per Sec Write"
- "Logical Disk D Avg Disk per Sec Write"
- ...

It would be awesome if you can add a regex field to the configuration of graphs which is considered by the service name search order. (https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md)

This would give users the option to assign the correct graphs without changing the servicenames (wich you can see in my example above).

**Comment by Mikesch-mp** [comment]
Regex is not easy, because of the data i have when the hook is loaded. I think i will add an configurable variable that can hold the dashboard & panelid for a service which is used then beside the normal search order. Would this help you?

**Comment by cstegm** [comment]
I don't get the point how this could help me can you give an example? 
The most comfortable way would be to configure regex pattern. Yes it is not easy because you have to iterate over the whole configsections and looking there for the regex pattern. In the example I have to asdign a dashboard for the Logical.*Read Services and one for Logical.*Write Services.

**Comment by Mikesch-mp** [comment]
The problem with regex is, where should i get it? The module is loaded when the service is loaded and then looks into config about servicename or command name. The only way i can get a regex or a dashboard loaded is via a vars from the service itself. So you have to configure something like 

`
   vars.grafana_dashboard = "dashboardname:panelid"
`

or 

`
   vars.grafana_regex = "Logical Disk.*Read"
`

in Your service configuration or template.

**Comment by cstegm** [comment]
Hope the pull request is okay for you :)

**Comment by Mikesch-mp** [comment]
Added a custom variable option in 1.2.0 where you can set the graph config to use for the service/host object.

**Comment by friesoft** [comment]
@Mikesch-mp works great for me, thanks :smile:
