### ISSUE TITLE
Custom panel not showing in icingaweb

### ISSUE THREAD

**Issue by zevilz** [Mikesch-mp/icingaweb2-module-grafana#114]
I used [this dashboard](https://grafana.com/dashboards/1572). Panels worked fine in icingaweb. Then I create [new dashboard](https://gist.github.com/zevilz/ff3cda3a5c5881480207b85af54227d9) with one panel, set it in isingaweb grafana module. But my panels not showing, link to grafana panel working. What I do wrong?

![17-02-2018 12-26-58](https://user-images.githubusercontent.com/12094229/36339038-07ce94dc-13de-11e8-8918-8af485377772.png)
![17-02-2018 12-28-52](https://user-images.githubusercontent.com/12094229/36339043-22ee1d50-13de-11e8-88cd-8f69583d9e37.png)

**Comment by Mikesch-mp** [comment]
Hello @zevilz ,

this dashboard is not intended to use with the module. Its just a dashboard that show what is possible with Icinga2 and Grafana. You can add a host action that links to this dashboard inside Icingaweb2, but thats it. If you want to use dashboards for the module you have to import the provided dashboards or create new by yourself.

The feature to show all graphs from a host will be in 1.2.0

Best Regards,
Carsten

**Comment by zevilz** [comment]
@Mikesch-mp i'm create dashboard in grafana interface with same options and same panel like in [this dashboard](https://grafana.com/dashboards/1572). But it not show in icingaweb.

Also that I find in log:
```
t=2018-02-17T16:09:56+0500 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=evil method=GET path=/render/dashboard-solo/db/icinga2-main status=500 remote_addr=127.0.0.1 time_ms=60005 size=1763 referer=
t=2018-02-17T16:09:56+0500 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
t=2018-02-17T16:10:06+0500 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=evil error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```

**Comment by zevilz** [comment]
Now i tried make graph in icingaweb. It working, but should to create graphics for each service.

**Comment by Mikesch-mp** [comment]
If you want a default graph that is used for non configured graphs, import the icinga2-default that is provided with the module and set default dashboard in module config to icinga2-default. If you want a special graph or a graph with correct units, you have to create for each service name or command name a panel in Grafana.

**Comment by zevilz** [comment]
I import icinga2-default, but some settings not apply in icingaweb
![18-02-2018 12-33-12](https://user-images.githubusercontent.com/12094229/36349427-733cebfe-14a8-11e8-8024-54d1827990a1.png)
![18-02-2018 12-34-51](https://user-images.githubusercontent.com/12094229/36349428-735ef212-14a8-11e8-8b5a-0eba559653c2.png)

**Comment by zevilz** [comment]
It seems display that panel
![18-02-2018 12-40-07](https://user-images.githubusercontent.com/12094229/36349446-f478091a-14a8-11e8-8ff7-b501078dd2de.png)

**Comment by Mikesch-mp** [comment]
Did you do the graph configuration for the memory service? you can find them configuration -> Grafana graphs. See the [docs](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md) on how to configure them.

Regards,
Carsten

**Comment by zevilz** [comment]
I have understood, thanks!
