### ISSUE TITLE
Grafana 5 compatibility

### ISSUE THREAD

**Issue by vita2** [Mikesch-mp/icingaweb2-module-grafana#116]
hello carsten,

i am testing the new grafana 5 beta and playing around with it. did you know that the png render url was changed in grafana 5 beta? in cause of that the grafana module won't load any graphs anymore :confused:

## Current Behavior

direct link of rendered image in grafana v4.6.3:
```
https://monitoring.home.lan/grafana/render/dashboard-solo/db/icinga2-default-multimetrics?orgId=1&var-hostname=monitoring.home.lan&var-service=load&var-command=load&panelId=1&from=1519276482371&to=1519298082371&width=1000&height=500&tz=UTC%2B01%3A00
```

direct link of rendered image in grafana v5.0.0-beta4:
```
https://monitoring.home.lan/grafana/render/d-solo/000000010/icinga2-default-multimetrics?orgId=1&var-hostname=monitoring.home.lan&var-service=load&var-command=load&panelId=1&from=1519276419245&to=1519298019245&width=1000&height=500&tz=UTC%2B01%3A00
```

just wanted to let you know that :wink: 

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.1.10
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-5-amd64)
* Webserver, PHP versions: apache2 2.4.10-10+deb8u11 + php5 5.6.33-0+deb8u1

**Comment by Mikesch-mp** [comment]
Thanks for the information. I will wait to get a final version 5 and then change/extend module for it.

**Comment by Mikesch-mp** [comment]
As far as i can see now every dashboard has also an uid needed for the renderer :(

**Comment by nbuchwitz** [comment]
It looks like the old url schema still is working. In my grafana 5 installation the old schema redirects to the new schema with uuid?

**Comment by Mikesch-mp** [comment]
This works if dashboard names are unique, as soon you have 2 dashboards with same name the modules gets problems :)

**Comment by dnsmichi** [comment]
I always ensure that my dashboard names are unique. The programmer in me expects problems with duplicates, no matter which application :)

**Comment by dnsmichi** [comment]
Git master works fine for me with Grafana v5.

```
commit 7a8500528a9b13d897f5c5d57513271b349f63d9
Author: Carsten Koebke <carsten.koebke@koebbes.de>
Date:   Sat Mar 3 19:57:48 2018 +0100

    Add new timeranges also to graph config form
```

```
[root@icinga2-influxdb ~]# yum info grafana
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.wiuwiu.de
 * epel: ftp-stud.hs-esslingen.de
 * extras: mirror.wiuwiu.de
 * updates: mirror.wiuwiu.de
Installed Packages
Name        : grafana
Arch        : x86_64
Version     : 5.0.0
Release     : 1
Size        : 149 M
Repo        : installed
From repo   : grafana
Summary     : Grafana
URL         : https://grafana.com
License     : "Apache 2.0"
Description : Grafana
```

<img width="1414" alt="screen shot 2018-03-04 at 16 30 16" src="https://user-images.githubusercontent.com/382049/36947237-8974ae44-1fc9-11e8-8c56-891ad2c6c496.png">
<img width="1414" alt="screen shot 2018-03-04 at 16 30 54" src="https://user-images.githubusercontent.com/382049/36947238-89928022-1fc9-11e8-94e5-b0e89396c0fc.png">

**Comment by gino0631** [comment]
@dnsmichi what type of Grafana access you have configured, and does it work with Direct access as well for you?

**Comment by nbuchwitz** [comment]
Direct access works flawless. Just generated an API key and configured the grafana module.

**Comment by dnsmichi** [comment]
@gino0631 auth.anonymous with direct access. 

https://github.com/Icinga/icinga-vagrant/blob/master/.puppet/modules/profiles/manifests/icinga/icingaweb2.pp#L323

**Comment by vita2** [comment]
okay, so if it works then i need to check my configuration. 

currently i see a timeout message when looking for a graph in service view.

![icingaweb2-grafana-service-debug](https://user-images.githubusercontent.com/25298055/37089160-ee660482-21ff-11e8-929b-4ad92fef64c9.png)

my grafana installation is reachable behind a nginx reverse proxy. i've configured it like mentioned in the grafana documentation[1]. 

![grafana](https://user-images.githubusercontent.com/25298055/37089169-f47d77b0-21ff-11e8-99ec-a17f242b741f.png)

here is a short summary of my configuration: 

- `/etc/grafana/grafana.ini`:
  ```
  [server]
  protocol = http
  http_port = 3000
  domain = localhost
  root_url = %(protocol)s://%(domain)s:/grafana
  ```

- nginx configuration for the grafana location (`/etc/nginx/sites-enabled/vhosts.conf`):
  ```
  server {
      listen 443;
      server_name monitoring.home.lan;
      index index.php;
      ...
      location /grafana/ {
        proxy_pass http://localhost:3000/;
      }
      ...
  }
  ```

- icingaweb2 grafana module configuration:
  ![icingaweb2-grafana-module-config](https://user-images.githubusercontent.com/25298055/37089177-fb37f95e-21ff-11e8-8d1f-f5ec77843eb5.png)

i've tried to change the root_url in my `grafana.ini`:
```diff
 [server]
 protocol = http
 http_port = 3000
 domain = localhost
-root_url = %(protocol)s://%(domain)s:/grafana
+root_url = %(protocol)s://%(domain)s:/
```

after reloading the grafana server i can see the graphs in icingaweb2. but unfortunately the grafana webui is broken then or no more fully reachable :confused:

![icingaweb2-grafana-service-debug-without-sub](https://user-images.githubusercontent.com/25298055/37089817-3142e7f0-2202-11e8-9e44-c87f27598031.png)

a click with the mouse on the graph shows:
![grafana-without-sub-clicking-on-graph](https://user-images.githubusercontent.com/25298055/37089932-bdf3bbfc-2202-11e8-9348-61290ad7314e.png)

opening the grafana webui:
![grafana-without-sub](https://user-images.githubusercontent.com/25298055/37089825-350997ee-2202-11e8-8f40-2adc5bf6c19b.png)

any suggestions to resolve this?


[1] http://docs.grafana.org/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-com-grafana

**Comment by Mikesch-mp** [comment]
First i think you forgot to do a `systemctl daemon-reload && systemctl restart grafana-server`

Grafana 5 redirects internaly old URLs to new URLs schema. See https://github.com/grafana/grafana/pull/10809

**Comment by gino0631** [comment]
Just to be sure - to work with Grafana 5, the latest version from master is required? Because currently we are using the latest release 1.1.10, the integration is not working, so I assume we should wait for the next release before investigating any further.

**Comment by kav2k** [comment]
I'm seeing the same problem as @vita2 - if Graphana 5 is behind reverse proxy on the same vhost, then legacy redirection fails (it produces a 404 in Graphana's log, followed by timeout).

Something that may be related is https://github.com/grafana/grafana/issues/10878

**Comment by kepi** [comment]
We are able to use Graphana 5 with same settings as before with following change:

```
❯ git diff
diff --git a/library/Grafana/ProvidedHook/Grapher.php b/library/Grafana/ProvidedHook/Grapher.php
index 8b7c414..1671fb7 100644
--- a/library/Grafana/ProvidedHook/Grapher.php
+++ b/library/Grafana/ProvidedHook/Grapher.php
@@ -205,10 +205,10 @@ class Grapher extends GrapherHook
             }

             $this->pngUrl = sprintf(
-                '%s://%s/render/dashboard-solo/%s/%s?var-hostname=%s&var-service=%s&var-command=%s%s&panelId=%s&orgId=%s&width=%s&height=%s&theme=%s&from=now-%s&to=%s',
+                '%s://%s/render/d-solo/000000033/%s?var-hostname=%s&var-service=%s&var-command=%s%s&panelId=%s&orgId=%s&width=%s&height=%s&theme=%s&from=now-%s&to=%s',
                 $this->protocol,
                 $this->grafanaHost,
-                $this->dashboardstore,
+                #$this->dashboardstore,
                 $this->dashboard,
                 urlencode($hostName),
                 rawurlencode($serviceName),
@@ -274,12 +274,12 @@ class Grapher extends GrapherHook
                 $this->height
             );
         } elseif ($this->accessMode == "direct") {
-            $imghtml = '<img src="%s://%s/render/dashboard-solo/%s/%s?var-hostname=%s&var-service=%s&var-command=%s%s&panelId=%s&orgId=%s&width=%s&height=%s&theme=%s&from=now-%s&to=%s&trickrefresh=%s" alt="%s" width="%d" height="%d" class="'. $imgClass .'"/>';
+            $imghtml = '<img src="%s://%s/render/d-solo/000000033/%s?var-hostname=%s&var-service=%s&var-command=%s%s&panelId=%s&orgId=%s&width=%s&height=%s&theme=%s&from=now-%s&to=%s&trickrefresh=%s" alt="%s" width="%d" height="%d" class="'. $imgClass .'"/>';
             $previewHtml = sprintf(
                 $imghtml,
                 $this->protocol,
                 $this->grafanaHost,
-                $this->dashboardstore,
+                // $this->dashboardstore,
                 $this->dashboard,
                 urlencode($hostName),
                 rawurlencode($serviceName),
```

**Comment by Mikesch-mp** [comment]
@kepi this only works for your! Everyone els witll get another "Magic" number for the Grafana installations.
This is a bug in Grafana regarding redirects, see issues [10878]
(https://github.com/grafana/grafana/issues/10878) and [11180](https://github.com/grafana/grafana/issues/11180). 

@all please stop posting code snippets that will only work for your environment. Full support for Grafana 5+ will come soon

**Comment by plachetka** [comment]
I think Mikesch-mp will add the second parameter for the dashboards to the grafana config inside the module. The new url style requires the id and the name of the dashboard. So we've to wait for the update. :-)

**Comment by Mikesch-mp** [comment]
I will :) just finished new proxy mode, which will speed up page load

**Comment by kav2k** [comment]
With Graphana 5.0.2 released, direct/proxy mode with reverse proxy now works flawlessly - should help you as well, @vita2

**Comment by vita2** [comment]
yes it does. i've just installed grafana 5.0.2 and the graph rendering is working again. thanks for your help guys and sorry for the noise @Mikesch-mp  :wink:

for me the issue is fixed 😃

**Comment by friesoft** [comment]
Using 5.0.2 rendering works for me now as well :slightly_smiling_face: 

One bug I noticed is wrong height if the second graph fails to render (grafana). Only difference between the two is the grafana version used.

Old Version (5 pre release (shortly after 4.6 was renamed to 5))
![old](https://user-images.githubusercontent.com/124109/37490327-9d503eb8-289a-11e8-88f8-3988993c58c7.png)

New Version (5.0.2)
![new](https://user-images.githubusercontent.com/124109/37490325-9d094954-289a-11e8-8198-450f49e3ac8b.png)

The second graph should be a piechart but rendering it doesn't work in grafana 5.0.2 => timeout.

**Comment by Mikesch-mp** [comment]
Thats because i have to render error messages to image, real dirty but only way to send them back as image :) For timeout, did you try to set it to 10s or even higher?

**Comment by friesoft** [comment]
Changing timeouts doesn't help as the rendering of piecharts doesn't work in Grafana.. no matter how long the timeout is.
So is this a seperate bug then? Or do you think there will be no way around it?

**Comment by Mikesch-mp** [comment]
Open a bug @Grafana repository?

**Comment by friesoft** [comment]
There is already a bugreport for the piechart: https://github.com/grafana/piechart-panel/issues/131
It was more a matter of if the failing panel could be handled more gracefully by this plugin. If there's no way that's fine as it is a cornercase which shouldn't happen normally.

**Comment by Mikesch-mp** [comment]
Added Grafana 5 support with b2a87e0 . Keep in mind to read the update docs **before** opening new issues ;) Happy testing
