### ISSUE TITLE
custom variables in graphs

### ISSUE THREAD

**Issue by phil-or** [Mikesch-mp/icingaweb2-module-grafana#120]
I am using Grafana with custom templates, to display all icinga services from one host with correct units in one dashboard (custom-network).
I would like to see the correct graph from every service in icinga and tried to use the custom variables in the graphs config.
![grafik](https://user-images.githubusercontent.com/36534023/36893776-96916fde-1e09-11e8-9799-8127ad264db2.png)
In this case i get linked to this grafana page and the $service.name$ dont get resolved.
![grafik](https://user-images.githubusercontent.com/36534023/36894076-9dc01a48-1e0a-11e8-9011-8529a94f80d1.png)

Is it possible to use Icinga variables in the icingaweb2-grafana Modul, or which variable must be set in the graph config to display the correct graph?

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.2.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Grafana Version: 5.0.0

**Comment by dnsmichi** [comment]
Huh?

**Comment by phil-or** [comment]
I am sorry, sent too early.  Now the post has been successfully edited.

**Comment by Mikesch-mp** [comment]
The Custom Variable field can only use custom variables from Icinga.
But you can use the service variable that is send to grafana. You need to use templating, see the docs for [influxdb](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/06-create-grafana-dashboards-influxdb.md) or [graphite](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/07-create-grafana-dashboards-graphite.md) on howto create dashboards.

Regards,
Carsten

**Comment by phil-or** [comment]
Thanks!
I always tried the icinga variable, with the custom variable the link to grafana works.
I should just read more carefully...
