### ISSUE TITLE
Grafana ApiKey and iFrame

### ISSUE THREAD

**Issue by dupondje** [Mikesch-mp/icingaweb2-module-grafana#121]
Hi All,

It would be nice to have the option to use the ApiKey with the iFrame option.
The proxy option is really slow, and not very usefull in production :)

But if you could somehow manage to get the Bearer send via iFrame, this would work out much better!

Thanks

**Comment by Mikesch-mp** [comment]
Hi @dupondje,

iam sorry but Grafana **API**keys are only for use with the API. Can't use this in an iframe. Only basic authentication, but then you can also enable anonymous auth :)
 
Best regards,
Carsten
