### ISSUE TITLE
Idea: How to speed up proxy mode

### ISSUE THREAD

**Issue by cstegm** [Mikesch-mp/icingaweb2-module-grafana#126]
Hi Carsten, 

thanks for the feature with the custom variable! It is awesome and It works very well!

I was thinking about how to speed up the proxy mode:
Basically the idea is to combine direct access and proxy.

- Build a new controller action wich only outputs header content-type png and raw image data from curl-request of the visualization from grafana, but no html. 
- So for Example the URL: /icingaweb2/grafana/show/image?host=testhost&service=testservice just shows a png.
- Just link the images to those URLs. So the website can load without waiting for the curls and icingaweb can show host/service details while loading the images via proxy parallel.

**Comment by cstegm** [comment]
Another advantage could be that one can put a graph on a dashboard using this url

**Comment by doctore74** [comment]
+1

**Comment by Mikesch-mp** [comment]
Please test by cloning latest master.
