### ISSUE TITLE
Indirect Proxy Mode: If one panel fails to render the previous gets duplicated

### ISSUE THREAD

**Issue by friesoft** [Mikesch-mp/icingaweb2-module-grafana#128]
Using indirect proxy mode the first panel is duplicated if the second fails to render.

## Expected Behavior
Show error message about failing to fetch the second panel like in proxy mode

## Current Behavior
Duplicate first panel

## Steps to Reproduce (for bugs)
1. Create dashboard with 2 panels (second one should fail to render)
2. Assign dashboard to service
3. Use proxy mode to verify the second panel can't be displayed
4. Switch to indirect proxy mode => duplicate first panel

## Your Environment
* Icinga Web 2 Grafana version (System - About): master (126fd9b1eeb03bffe490dd57ab7f4b029becc118)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Grafana Version: 5.0 pre
* Version used (`icinga2 --version`): 2.8.1-1
* Operating System and version: Red Hat 7.4

**Comment by friesoft** [comment]
PS: thanks for the indirect proxy mode! :smiley: much faster! :+1:

**Comment by Mikesch-mp** [comment]
Can you upload dashboard and post module config + graph config please

**Comment by friesoft** [comment]
I'll post the dashboard/config tomorrow (battery of my notebook just died)

I'll also try to update Grafana tomorrow. Last time I tried the beta I experienced some (reported) bugs preventing the move to production.

Thanks for the fast response :)

**Comment by friesoft** [comment]
5.0.1 doesn't work for me yet as I hit this bug: https://github.com/grafana/grafana/issues/11180

module config:
```
[grafana]
host = "ourip:3000"
protocol = "http"
defaultdashboard = "icinga2-influxdb-default"
defaultorgid = "1"
defaultdashboardstore = "db"
theme = "light"
datasource = "influxdb"
accessmode = "indirectproxy"
height = "280"
width = "900"
enableLink = "yes"
usepublic = "yes"
publichost = "ourdomain/grafana"
publicprotocol = "https"
debug = "0"
timerangeAll = "1w/w"
shadows = "1"
authentication = "token"
apitoken = "ourtoken"
custvardisable = "grafana_graph_disable"
custvarconfig = "grafana_graph_config"
defaultdashboardpanelid = "1"
```

graph config
```
[Loadbalancing]
dashboard = "icinga2-loadbalancing"
panelId = "1,2"
orgId = "1"
height = "150"
repeatable = "no"
```

Dashboard: [icinga2_loadbalancing.txt](https://github.com/Mikesch-mp/icingaweb2-module-grafana/files/1807979/icinga2_loadbalancing.txt)

**Comment by juangranados** [comment]
Same problem on Grafana 5.0.1 as explained in [#129](129)

**Comment by Mikesch-mp** [comment]
Yeah, PanelIDs start at 2 with Grafana 5. Set you panelId to 2,3 and everything should be ok.

**Comment by Mikesch-mp** [comment]
Seem a bug with reverse proxy and panelid 1 . Just checked my setup (without reverse proxy) and it works flawless.

**Comment by juangranados** [comment]
Thanks!

I changed to

![image](https://user-images.githubusercontent.com/6050403/37364025-a28d44e0-26f9-11e8-973d-e735910cdf66.png)

Now I got the same graph repeated:

![image](https://user-images.githubusercontent.com/6050403/37364064-b9638f4e-26f9-11e8-84fd-d328a0641a50.png)

If I click on graph, Grafana shows the correct one.

**Comment by Mikesch-mp** [comment]
@friesoft  Can you please test the latest master? i just pushed a fix for repeating panels that also fixes multiple ids configured.

**Comment by friesoft** [comment]
Works great now :smiley: Thanks for the lightning fast fix! :1st_place_medal:
