### ISSUE TITLE
Module does not load first graph (panelId=1) from dashboard

### ISSUE THREAD

**Issue by juangranados** [Mikesch-mp/icingaweb2-module-grafana#129]
## Expected Behavior

All graphs are shown
## Current Behavior

Panel id 1 does not appear on screen.
## Steps to Reproduce (for bugs)

1. Create new Grafana graph using icinga2-default for a service with multiple performance values.
2. Set repeating panel.
3. Go to service in icinga web 2 and the first graph is not loaded

![image](https://user-images.githubusercontent.com/6050403/37358471-7741c33c-26eb-11e8-906b-b88d550306a9.png)

If I change from proxy to Indirect Proxy, no graphs are loaded due to [#128](128)

![image](https://user-images.githubusercontent.com/6050403/37358800-4283144c-26ec-11e8-8be3-b3f0c0f8f412.png)

If I click on first link: https://domainname:3000/dashboard/db/icinga2?var-hostname=hostname&var-service=CPU%20Load&var-command=check_win_perfmon&from=now-6h&to=now&orgId=2&panelId=1&fullscreen

It shows all graphs instead of graph 1

![image](https://user-images.githubusercontent.com/6050403/37358945-a49c9e50-26ec-11e8-9bf1-ae9acf0acaa0.png)

If I click on second link:

![image](https://user-images.githubusercontent.com/6050403/37359008-ca4973bc-26ec-11e8-82af-70c11730ed6d.png)

## Context

Before update to Grafana v5.0.1 I have no problems. 

## Your Environment

* Icinga Web 2 Grafana version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04.4 LTS (Xenial Xerus)
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`): 
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: domainname
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 82 Zones.
information/ConfigItem: Instantiated 81 Endpoints.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 770 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 224 CheckCommands.
information/ConfigItem: Instantiated 15 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 EventCommand.
information/ConfigItem: Instantiated 82 Hosts.
information/ConfigItem: Instantiated 3 Comments.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 Dependencies.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 688 Services.
information/ConfigItem: Instantiated 6 ServiceGroups.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Mikesch-mp** [comment]
Thats an easy one. With Grafana 5 there is no more panelId = 1, All dashboards start at panelid 2.

Please check the panelids and correct them in your graph config (also for default dashboard).

**Comment by juangranados** [comment]
Thanks! 

I changed to:

![image](https://user-images.githubusercontent.com/6050403/37364188-1bb9663c-26fa-11e8-85ae-06a7166c9285.png)

But now I have same graph for all metrics:

![image](https://user-images.githubusercontent.com/6050403/37364225-369b3552-26fa-11e8-9bde-efdc675a2a94.png)

If I click on one graph, Grafana shows the correct graph.

**Comment by Mikesch-mp** [comment]
Sorry have to stop, iam running into this bug on my installations.
https://github.com/influxdata/influxdb/issues/9562 :(

**Comment by Mikesch-mp** [comment]
i got the repeating panel problem fixed :) Works with Grafana 4 and 5, but 5 needs a higher timeout

![image](https://user-images.githubusercontent.com/6574967/37366497-dea192a4-2700-11e8-8580-7a97823cbf3a.png)
