### ISSUE TITLE
png preview files not generated...

### ISSUE THREAD

**Issue by Christiaan-Liebenberg** [Mikesch-mp/icingaweb2-module-grafana#13]
Not sure if issues, am running:

Ubuntu 16.04.02
Icinga2.6.2-1
Icinga2Web 2.4.1
Grafana 4.1.2
Graphite 
IcingaWeb2-Module-Grafana 1.0.3

I was able to follow the steps in the README successfully and can see (Windows and LocalHost) data in Grafana. I am able to click on generated preview images in Icinga (to access the relevant Grafana graph.

1. The links on the preview images did not work correctly (or in my case, I'm using anonymous access to Grafana. I needed to change the URL in Grapher.php (line 80) from:

'%s://%s%s/render/dashboard-solo/db/%s?var-hostname=%s&var-service=%s&panelId=%s&width=%s&height=%s&theme=light&from=now-%s&to=now',

To:

'%s://%s%s/dashboard/db/%s?var-hostname=%s&var-service=%s&panelId=%s&width=%s&height=%s&theme=light&from=now-%s&to=now',

When I clicked the link, I would get page could not be displayed). After correcting the URL in Grapher.php, when I now click the links, they open correctly in Grafana, see screenshot 1.

2. However, the preview links are still not rendering in Icinga, see screenshot 2.

Think this may be an issue localized to my installation. Have so far tried to install libpng-dev but with no luck.

(Note I had previously been testing with icingaweb2-module-graphite, in this case I was able to get previews working correctly in Icinga Web.)

![grafanapreview](https://cloud.githubusercontent.com/assets/26408315/23902038/4d3532f0-08c8-11e7-81ba-5ca7bf6cccb5.PNG)

![previewoutput](https://cloud.githubusercontent.com/assets/26408315/23901904/dcd87b16-08c7-11e7-85ab-c3658e70274d.PNG)

**Comment by Mikesch-mp** [comment]
Hello Christian,

please download and install this version https://github.com/Mikesch-mp/icingaweb2-module-grafana/archive/master.zip and install it. Or just set in the module config the default template name to "icinga2-default". There was a bug/typo in the 1.0.3 release which uses "icinga-default" as default template name.

If you still have problems , we can do a teamviwer session if you want.

**Comment by lordbernd** [comment]
Hello Mikesch-mp,

just want to add my 2cent here.

Your module out of the box shows me the following error on my environment:

![image](https://cloud.githubusercontent.com/assets/4759375/23922997/09fa19e6-0905-11e7-8166-f284043830a3.png)

after removing "/render/" from the URL as Christiaan-Liebenberg described I face the exact same problem. I've tried to update to the version you suggested right before, but it's still the same. 

My test test system:

CentOS 7.3.1611
Icinga2.6.0
Icinga2Web 2.4.0
Grafana 3.1.1 (sane with 4.1.1)
Graphite
IcingaWeb2-Module-Grafana 1.0.3

The graphite or pnp module are working fine.

Is there any other requirement?

Many thanks in advance!_

**Comment by Mikesch-mp** [comment]
hi,

.../renderer/... is just a direct way to get the panel/graph as png and not as a website. 
Do you have set "enforce_domain" to true in Grafana or use reverse proxy?

If one of you have time for a remote seesion i would like to see whats going wrong.

**Comment by lordbernd** [comment]
hi,

"enforce_domain" is false and I have no reverse proxy in use.

I would be available later today for a remote session.

thanks for your time!!

**Comment by Mikesch-mp** [comment]
You can contact me via my E-Mail orbuse it to find ne in Skype. Carsten.koebke(at)gmx.de

**Comment by lordbernd** [comment]
I've sent you an invite in skype :)

Thanks again!

**Comment by Mikesch-mp** [comment]
Christian,

please revert all changes you made to the source files and enable "basic.auth" like @lordbernd  wrote and test if it is working then. If it is still not working i can also do a remote session with you to fix your problem.

**Comment by Christiaan-Liebenberg** [comment]
Hi Mike, 

Many thanks for your quick response and offer of support to resolve this. 

To be fair, my install may be a bit 'messy' as I was testing all the different Icinga2 modules and plugins to get an idea of what works best / simplest.

I've started from scratch on my test environment and now that I know what components I like, am only installing those. I think this module for preview of Grafana graphs is great (if I can get it working).

Give me a few days to setup the test systems and generate some data. I'll let you know if I'm still struggling,

Thakns again!

**Comment by Christiaan-Liebenberg** [comment]
Success! Must say, the preview graphs look great!

Changed the basic.auth setting Mike and all is looking good:

![image](https://cloud.githubusercontent.com/assets/26408315/24007837/74a318e6-0a78-11e7-9851-7b148f85c0ba.png)


Just a head's up, looks like there are some schema changes in InfluxDB. When I re-setup my test environment, I initially installed InfluxDB and Grafana by adding package repositories (as per their install documentation) then ran apt-get.

This all installed fine but when trying to import your dashboards, got an import error "Template variables  could not be initialized" and "grafana JSON -> JS Serialization failed:".

Looking at your templates I saw they indicated  you were running InfluxDB version 1.0.0 and Grafana 4.1.1. Once I installed those versions everything was good.

**Comment by Mikesch-mp** [comment]
Which Version you had installed before ? The InfluxDB version > 1.0 should create any error. Only Grafana version lower then 4.1.x can cause trouble.

**Comment by Mikesch-mp** [comment]
Solution: enable basic auth or anonymous acccess to Grafana.

**Comment by mcasviper** [comment]
Sorry for reopening this issue but i have the exact same problem and my grafana is configured for anonymous or basic auth and it doesn't work. 
If I try to copy the url (.../render/...) and paste it to a new window I get the png. I could find your email so I reopened this issue. 

Graph currently unavailable: file_get_contents(http://abc.def.ghi:3000/render/dashboard-solo/db/icinga2-default?var-hostname=HOSTNAME&var-service=load&panelId=1&width=640&height=280&theme=light&from=now-6h&to=now): failed to open stream: HTTP request failed!

**Comment by Mikesch-mp** [comment]
Hello,

just contact me in skype. carsten.koebke(at)gmx.de

**Comment by mcasviper** [comment]
Hi today I was not at home. So I think next week on friday evening is best for both of us. Please let me know if I can get you any needed informations like config settings.

**Comment by mcasviper** [comment]
Hello,

I found my problem. My Icinga2 stack with graphite and grafana is running on a bananapi and I am running in timeouts with the pngs. If I change the timeout value from 5 to 15 I get the pngs after the second try. So first call is the old message and then i got images.
To say it clear, the module is working fine!

**Comment by Mikesch-mp** [comment]
HI,

nice you found a way to solve it yourself.
