### ISSUE TITLE
[Feature request] Indirect Proxy: Reserve space to prevent jumps when graphs appear

### ISSUE THREAD

**Issue by friesoft** [Mikesch-mp/icingaweb2-module-grafana#131]
## Expected Behavior
Reserve the space needed for graphs while they are loading (placeholder image? spinner?)

## Current Behavior
Currently the headline "Performance Graph" and the timechooser is shown and while scrolling/looking/clicking through the page the graphs appear and move everything down possibly leading to unwanted clicks.

## Possible Solution
If the height of the graphs is specified I guess the div "icinga-module module-grafana" could be set to this size to already preoccupy the needed space.

## Steps to Reproduce (for bugs)
Use indirect proxy and open services/hosts containing graphs - the page content moves down as soon as the graphs appear.

## Context
Could lead to wrong annoying behaviour (trying to click on "schedule downtime" - graphs appear - clicked on one of the graphs jumping into a grafana tab

## Your Environment
* Icinga Web 2 Grafana version (System - About): master (c1858288bd4842e4904a1f16ca0ae107df76d972)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): 2.8.1-1
* Operating System and version: Red Hat 7.4

**Comment by Mikesch-mp** [comment]
Hmm have to read if there is a solution for this.

**Comment by Mikesch-mp** [comment]
Was easier then i thought first :)

**Comment by friesoft** [comment]
Nice :) Will test tomorrow, but diff looks like I would probably have done it - but I'm all but an expert on CSS :laughing: 
Thanks! :smiley:

**Comment by friesoft** [comment]
Works for me :smiley:
