### ISSUE TITLE
Scope of Custom Variables

### ISSUE THREAD

**Issue by druchoo** [Mikesch-mp/icingaweb2-module-grafana#132]
Not sure if this should be possible or if I'm simply doing this incorrectly.

I'm trying to use a custom host variable in a config for a service graph but the variable isn't getting resolved. Custom variables defined in the service work just fine. Tried a few other things that I saw in closed issues with no success:

* For `customVars` tried `$host.vars.load_balancer_name$`
* tried `vars.load_balancer_name = "$host.vars.load_balancer_name$"` in service template which gave me `%24host.vars.load_balancer_name%24` in the url

Here is how everything is currently configured:

```
[Unhealthy Host Count]
dashboard = "aws-alb"
panelId = "2"
orgId = "1"
repeatable = "no"
customVars = "&var-load_balancer=$load_balancer_name$"
```

```
zones.d/virginia/hosts.conf
object Host "myhost.mycompany.com" {
    import "myhost-host"

    display_name = "myhost.mycompany.com"
    address = "myhost.mycompany.com"
    vars.load_balancer_id = "123456"
    vars.load_balancer_name = "my-alb"
    vars.load_balancer_target_group = "my-target-group"
}

zones.d/director-global/service_templates.conf
template Service "Unhealthy Host Count" {
    import "generic-service"

    check_command = "influxdb-query"
    vars.influxdb_query_label = "ALB"
    vars.influxdb_query_query = "SELECT mean(\"foo\") FROM \"bar\" WHERE time > now() - 5m AND \"load_balancer\"='$load_balancer_name$/$load_balancer_id$'" AND \"target_group\"='$load_balancer_target_group$'"
}

```

```
Cannot fetch graph with curl: 'Operation timed out after 5001 milliseconds with 0 out of -1 bytes received'.
Performance Graph Debug
Access mode	proxy
Authentication type	basic
Protocol	https
Grafana Host	mygrafana.mycompany.com:443
Dashboard Store	db
Dashboard Name	aws-alb
Panel ID	2
Organization ID	1
Theme	light
Timerange	6h
Timerangeto	now
Height	280
Width	640
Graph URL	https://mygrafana.mycompany.com:443/render/dashboard-solo/db/aws-alb?var-hostname=myhost.mycompany.com&var-service=Unhealthy%20Host%20Count&var-command=influxdb-query&var-load_balancer=$load_balancer_name$&panelId=2&orgId=1&width=640&height=280&theme=light&from=now-6h&to=now
```

## Expected Behavior

Custom host variables should work in configs of graphs for services?

## Current Behavior

Variables aren't resolved

## Steps to Reproduce (for bugs)

1. Define host with custom variables
2. Create graph config for service with `Custom Variables` of those defined in the host config.

## Context

Trying to access variables that are defined in Icinga host config in the Grafana module config for a service graph.

## Your Environment

* Icinga Web 2 Grafana version (System - About): `1.2.0`
* Icinga Web 2 version and modules (System - About): 

```
Icinga Web 2.5.1
businessprocess	2.1.0
cube	1.0.1
director	1.4.2
doc	2.5.1
fileshipper	1.0.1
generictts	2.0.0
grafana	1.2.0
monitoring	2.5.1
puppetdb	1.0.0
toplevelview	0.1.0
translation	2.5.1
vsphere	1.1.0
```
* Version used (`icinga2 --version`): `r2.8.1-1`
* Operating System and version: `CentOS Linux release 7.2.1511 (Core)`
* Enabled features (`icinga2 feature list`):
```
Disabled features: command debuglog elasticsearch gelf graphite ido-pgsql opentsdb perfdata statusdata syslog
Enabled features: api checker compatlog ido-mysql influxdb livestatus mainlog notification
```
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 6 Zones.
information/ConfigItem: Instantiated 8 Endpoints.
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 6 NotificationCommands.
information/ConfigItem: Instantiated 1706 Notifications.
information/ConfigItem: Instantiated 210 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 52 Hosts.
information/ConfigItem: Instantiated 366 HostGroups.
information/ConfigItem: Instantiated 359 Users.
information/ConfigItem: Instantiated 6 ServiceGroups.
information/ConfigItem: Instantiated 604 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by Mikesch-mp** [comment]
i just tested it for hosts and it works, also for services. What you want todo is to use a host variable inside a service and forward it to Grafana :) That showuld work also.

1. Configure your custom variable in your host like you did.
```
vars.blubber = "Blubb"
```

2. In the service create a custom var that points to the host variable
```
vars.blubberblubb = host.vars.blubber
```

3. Configure your service graph customvar to
```
&var-whatever=$blubberblubb$
```

Using host vars directly doesnt work with my module, the varibale must be defined in the object you just watch.

**Comment by druchoo** [comment]
Hi @Mikesch-mp, I did try what you're saying but through Director. It seems to do a literal instead of interpreting the var :-( .

It's what i meant by:

> * tried `vars.load_balancer_name = "$host.vars.load_balancer_name$"` in service template which gave me `%24host.vars.load_balancer_name%24` in the url

So for example:

![image](https://user-images.githubusercontent.com/2237523/37426594-4faf35f4-279d-11e8-9c3f-a287e91db7d1.png)

produces:
```
zones.d/director-global/service_templates.conf
template Service "Unhealthy Host Count" {
    ...    
    vars.load_balancer_name = "$host.vars.load_balancer_name$"
}
```
I think I'm experiencing this issue https://github.com/Icinga/icingaweb2-module-director/issues/1257

Did you do `vars.blubberblubb = host.vars.blubber` through Director or manual edit of config files?

**Comment by Mikesch-mp** [comment]
I don't use Director for reasons :)

**Comment by druchoo** [comment]
haha ok fair enough. Thanks for confirming how to accomplish this. I'll troubleshoot this on the Director side.

**Comment by fl0wx** [comment]
@druchoo hey, were you able to resolve this issue? i have a similar issue and hoped to get help here :)
