### ISSUE TITLE
Optional use host_display_name instead of host_name in call to Grafana

### ISSUE THREAD

**Issue by idMaxCZ** [Mikesch-mp/icingaweb2-module-grafana#133]
Feature request: 

Please add combobox option to Module configuration for optional change var-hostname source. In present version of module is everytime used host_name host variable for call grafana. I suggest two options - host_name as default and host_display_name as optional way. 

We have stored data in influx under display_names because host_name are humen unreadable strings from our configuration management database. 

Example current:
.../dashboard-solo/db/icinga2-default?**var-hostname=srv154848754878**&var-serv...

Expected state:
.../dashboard-solo/db/icinga2-default?**var-hostname=testmachine_displayname**&var-serv...

Icinga host object:
object Host "srv154848754878" {
    import "generic-host"
    display_name = "testmachine_displayname"
    address = "8.8.8.8"
}

Thank you

**Comment by Mikesch-mp** [comment]
Hello @idMaxCZ ,
in short: no!
The problem is that in icinga2 host_names have to be unique and display_name you can have hundreds of the same. If you need to display the display_name in your graphs, just get it via templating (as query) or set it via the customvar option of the module and then use it. 

if you want to set it via customvar option you have to create a custom var that points to the  display_name like

```
vars.displayname = display_name
```

then for the graph configuration set custom variables like this
```
&var-displayname=$displayname$
```

**Comment by idMaxCZ** [comment]
Thank you for your answer. I understand there can be problem with duplicates, this is reason why i recommend this as optional option in module configuration. Default as hostn_ame with possibility change to display_name. 

I am little bit stacked now, because I have named measurements by display_name and host_name is not present in my influxDB. I already updated Grapher.php for this, but its my hack and every version of plugin I have update this file again.

**Comment by dnsmichi** [comment]
Going for display_name is dangerous here, as you cannot guarantee the correctly selected graph for it. I don‘t think that such a special case should be handled with yet another config option either. Imho the module already has too many config settings and behaviours, impossible to test them all to endure stable releases.

**Comment by idMaxCZ** [comment]
I totally understand, our environment is probably specific. 
Closing this feature request. Thank you for your opinions and suggestions.
