### ISSUE TITLE
Add New Grafana Graph Question

### ISSUE THREAD

**Issue by Fiiti** [Mikesch-mp/icingaweb2-module-grafana#14]
Hi,
I am not pretty sure to understand all functions.
Must I add by myself ALL Grapfs in the Graphs Menu I would like to see by the service ?
I mean the "Add New Grafana Graph".

Or for what is this feature?

It seems, that a lot of Graphs are available, without adding a Graph (mem, ping, hostalive, ...)

Thanks in advanced
Fiiti

**Comment by Mikesch-mp** [comment]
Hello Fiiti,

if you dont configure any graph it will use the default graph (icinga2-default). 
The default graph will only show the first perfdata it find and doesnt show any unit at the Y-axis
![image](https://cloud.githubusercontent.com/assets/6574967/24073241/c1acacb0-0bf4-11e7-935c-f43b611b969a.png)
If you configure a graph it will look like this (from base metrics)
![image](https://cloud.githubusercontent.com/assets/6574967/24073249/e20430b4-0bf4-11e7-8233-8676ef1e3287.png)

So you can configure your own graphs from selfmade dashboard, or use premade from base-metrics, or  never configure one and stay on the default one.

**Comment by Fiiti** [comment]
Many thanks for the fast and very good replay!
So now it's clear!
Fiiti
