### ISSUE TITLE
indirectproxy mode - custom variables

### ISSUE THREAD

**Issue by phil-or** [Mikesch-mp/icingaweb2-module-grafana#145]
First, thank you for the indirectproxy mode, awesome!

## Expected Behavior

correct representation of a graph with a custom variable in Icingaweb2 using the indirectproxy mode

## Current Behavior
indirectproxy mode can't fetch graphs if a custom variable is set in the graph config.
![curl](https://user-images.githubusercontent.com/36534023/39174855-5121f82a-4798-11e8-8a0a-e6b5abc789bc.JPG)
But if I open the link to Grafana, the correct Panel is displayed  .
Using the proxy mode, there are no Problems.

## Steps to Reproduce (for bugs)

1. Create a graph with a custom variable
2. use indirectproxy mode with authentication type "API Token"

## Your Environment

* Icinga Web 2 Grafana version (System - About): latest master
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): 2.8.2
* Operating System and version: CentOS 7
* Grafana: 5.0.4

/etc/icingaweb2/modules/grafana/config.ini:
[grafana]
host = "hostname:3000"
protocol = "http"
shadows = "0"
theme = "light"
datasource = "influxdb"
accessmode = "indirectproxy"
debug = "1"
defaultorgid = "0"
defaultdashboard = "icinga2-default"
enableLink = "yes"
usepublic = "no"
timerangeAll = "1w/w"
height = "400"
width = "640"
defaultdashboardpanelid = "2"
version = "1"
authentication = "token"
apitoken = "xxxxx"
defaultdashboarduid = "SpYSCSgik"
proxytimeout = "15"

/etc/icingaweb2/modules/grafana/graphs.ini:
[icmp-customIP]
dashboard = "network"
panelId = "15"
orgId = "2"
customVars = "&var-service_icmpcustom=icmp-customIP%20$icmp_address$"
repeatable = "no"
dashboarduid = "000000015"

**Comment by Mikesch-mp** [comment]
Hi,

iam short of time this week. but i will try to check/test it next weekend.
One thing that i see is this

```
customVars = "&var-service_icmpcustom=icmp-customIP%20$icmp_address$"
```
This will look like `var-service_icmpcustom=icmp-customIP 1.1.1.1`, maybe it should you wanted it like
```
customVars = "&var-service_icmpcustom=$icmp_address$"
```

or do you really save the customip with the text into influxdb?

**Comment by Mikesch-mp** [comment]
Just looked at my code, i think the problem is the space between "icmp-customIP" and the ip itself.

**Comment by phil-or** [comment]
Thanks for your quick response, it would be great if you can fix this bug!
Yes I want to save the customVar as "icmp-customIP 1.1.1.1"

**Comment by stevie-sy** [comment]
+1

**Comment by herrfeuer** [comment]
+1

**Comment by phil-or** [comment]
Thanks a lot @Mikesch-mp !!!
