### ISSUE TITLE
Use icingaweb2 auth hook?

### ISSUE THREAD

**Issue by dupondje** [Mikesch-mp/icingaweb2-module-grafana#147]
Hi,

I just noticed icingaweb 2.5.2 got released with an Authentication Hook feature.
See pull req: https://github.com/Icinga/icingaweb2/pull/3401#issue-178030542

Think it might be used with the grafana module to auth the user to grafana when he's logging in to icingaweb2.

**Comment by Mikesch-mp** [comment]
I saw it already and knew someone will ask for it. I will try and see what i can do as soon i have more time.

**Comment by Mikesch-mp** [comment]
i tested now many things to do this, all do not work correctly. In the future of the module, you have to use api key (and the iframe will be kicked out)
