### ISSUE TITLE
Data removed after few hours

### ISSUE THREAD

**Issue by jorfermo** [Mikesch-mp/icingaweb2-module-grafana#148]
I managed to get the module running. It's displaying the charts but it only retains a few hours of data.

This is the content of /etc/carbon/storage-schemas.conf:

```
# Schema definitions for Whisper files. Entries are scanned in order,
# and first match wins. This file is scanned for changes every 60 seconds.
#
#  [name]
#  pattern = regex
#  retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...

# Carbon's internal metrics. This entry should match what is specified in
# CARBON_METRIC_PREFIX and CARBON_METRIC_INTERVAL settings
[carbon]
pattern = ^carbon\.
retentions = 60s:90d

[default_1min_for_1day]
pattern = .*
retentions = 60s:90d
```

Shouldn't it retain the data for 90 days? Is there any other file where the retention time is set?

## Environment
* Icinga Web 2 Grafana version: 2.5.2
* Icinga Web 2 version and modules: grafana | Master
* Version used: r2.8.4-1
* Operating System and version: Ubuntu 16.04
* Enabled features: api checker command compatlog graphite ido-mysql livestatus mainlog notification
* Config validation: Valid

**Comment by Mikesch-mp** [comment]
Hello @jorfermo ,

iam not a graphite specialist :) But i knew that this questions come up often. Maybe one of this topcis will help you [Graphite not showing older data](https://monitoring-portal.org/t/graphite-not-showing-older-data/2098) or [
Graphite not showing Data older than a week](https://monitoring-portal.org/t/graphite-not-showing-data-older-than-a-week/451).

if this doesnt help, create an account @monitoring-portal.org and ask the community :)

Best regards,
Carsten

**Comment by jorfermo** [comment]
Thanks a lot Carsten. 

That info solved my problem :) 👍
