### ISSUE TITLE
hostname, service, command parameters in icinga2-default

### ISSUE THREAD

**Issue by AlexThaveau** [Mikesch-mp/icingaweb2-module-grafana#149]
Hi,

i'm setting up grafana 5.1.0 with icinga 2.5.1, thanks for the nice tutorial.
There one thing i don't understand (sorry i'm new to this), when i import icinga2-default to grafana, it is asking to me name, icinga2 (for my influxdb datasource) and hostname, service and command (which are set to null. What should i enter in those 3 fieds ?

I provide a screenshot.

Thanks,
![capturegraf](https://user-images.githubusercontent.com/38788304/39365612-e892c75c-4a31-11e8-8cc7-df823b695756.PNG)

**Comment by Mikesch-mp** [comment]
Hi Alex,

for the datasource input your influxdb datasource, the other fields you can enter whatever you want. I set all variables to be constants in the dashboard i provide, they will get overwriten with the ones the modules sends when generating the images.

Best regards,
Carsten

**Comment by AlexThaveau** [comment]
ok thanks very much for your answer.
