### ISSUE TITLE
Provide metric as render parameter + display all panels

### ISSUE THREAD

**Issue by friesoft** [Mikesch-mp/icingaweb2-module-grafana#15]
Hi,

we have many services which generate a variable amount of perfdata, depending on the host. We would like to graph each of these metrics in its own graph. Example: one service to check disk space on all partitions - each partition is a seperate metric with value, min, max, warn, ...

We would like to have:
Service DISK
* Graph: /home
* Graph: /usr
* Graph: /var/log
* Graph: /tmp

Currently this isn't possible as in Grafana we can't repeat the panel on each metric - only on each service.

To make this possible we would need:
* an url parameter &var-metric=<METRIC_NAME>
* the possibility to display all panels of a dashboard

Thanks & Best regards
Bernhard Friedreich

**Comment by Mikesch-mp** [comment]
Hi Bernhard,

not possible the qya you want it. I can not relay on perf data, i cant get data from Grafana how much panels a dashboard have. But i can create a dashboard that shows all metrics like you want it and you can use the power of icingaweb2 shared navigation to create a link to with a filter for it :) Just give me a day or 2. Iam just back from customer installing icinga2 :)

Best regards,

Carsten

**Comment by Mikesch-mp** [comment]
Here is the dashboard. I took the icinga check as example, you can change it in the templating &  panel query to your service you want. If you change the perfdata to "ALL" it will show all metrics in repeating panels.

[New dashboard Copy-1490167985942.zip](https://github.com/Mikesch-mp/icingaweb2-module-grafana/files/860646/New.dashboard.Copy-1490167985942.zip)

Die Navigation Config in Icingaweb2 sollte dann so aussehen:
```
[Test Grafana]
users = "*"
type = "service-action"
target = "_blank"
url = "https://grafana.host.name:3000/dashboard/db/new-dashboard-copy?var-hostname=$host_name$&var-service=$service_display_name$&var-perfdata=All"
icon = ""
filter = "service_description=icinga"
owner = "Blubber"

```

filter = "service_description=icinga" halt anpassen an den Service den Du mit dem Dashboardlink beglücken möchtest :)

**Comment by friesoft** [comment]
Thanks for the dashboard and sample :)
