### ISSUE TITLE
No Data visible in grafana

### ISSUE THREAD

**Issue by AlexThaveau** [Mikesch-mp/icingaweb2-module-grafana#150]
Hi,

i have an icinga 2.5.1 system with another vm with grafana 5.1.0 installed and influxdb. I reached the step 5
of the procedure and configured some hostalive graphs but unfortunately no values are showed at all in my base metrics graphs.
Moreover what annoys me is that i can't see any traffic with tcpdump betwenn my icinga server and my
grafana/influxdb server ... Here is my configuration : 

[grafana]
version = "1"
host = "192.168.1.22:3000"
protocol = "https"
timerangeAll = "1w/w"
defaultdashboard = "icinga2-default"
defaultdashboardpanelid = "2"
defaultorgid = "1"
shadows = "0"
theme = "light"
datasource = "influxdb"
accessmode = "direct"
height = "280"
width = "640"
enableLink = "yes"
usepublic = "no"
debug = "1"
directrefresh = "no"
defaultdashboarduid = "y-bLd4Gmz"
ssl_verifypeer = "0"
ssl_verifyhost = "0"

I saw nothing interesting in logs except this (a few hours ago)
t=2018-04-27T17:01:35+0200 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="Timeout error. You can set timeout in seconds with &timeout url parameter"

Thanks for your help,

**Comment by Mikesch-mp** [comment]
Please enable debug output in the module and use the link from debug in your browser. If you have still an error its mostly because authentication is not working or configured.

**Comment by AlexThaveau** [comment]
Hi Mike,

i configured 1 graphs for CpuWin for example, which i tried to plug to base-metrics dashboard CpuWin panel. I see one graph in icinga but 
- no data points in the graph
- it looks like the axis is bad (-1.0B to 1.0B but we are talking about CPU, i should be able to modify JSON ... but anyway there is no point in the graph
Here is debug :
`
Access mode | direct
-- | --
 
http
192.168.1.22:3000
v8iPO4Gik
base-metrics
2
1
light
6h
now
280
640
 
http://192.168.1.22:3000/render/d-solo/v8iPO4Gik/base-metrics?var-hostname=AD2&var-service=CpuWin&var-command=nrpe&panelId=2&orgId=1&width=640&height=280&theme=light&from=now-6h&to=now&trickrefresh=now
grafana_graph_disable
grafana_graph_config
No
`

I tried hostalive, and this not better, no graph is printed at all, and when i click on it, i'm takend to icinga2-defaults rather than base-metrics with no graph at all.
Here is debug :
`
Access mode | direct
-- | --
 
http
192.168.1.22:3000
_exe2NGmk
icinga2-default
2
1
light
6h
now
280
640
 
http://192.168.1.22:3000/render/d-solo/_exe2NGmk/icinga2-default?var-hostname=AD2&var-service=ma-ping&var-command=ma-ping&panelId=2&orgId=1&width=640&height=280&theme=light&from=now-6h&to=now&trickrefresh=now
grafana_graph_disable
grafana_graph_config
No
`

**Comment by Mikesch-mp** [comment]
Hi @AlexThaveau ,

you need to configure the graphs. If you dont configure them the default dashboard from global config will be used. See https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md

Regards,
Carsten

**Comment by AlexThaveau** [comment]
Thanks. I configured the graphs following the page you refered to. 

For each of my graph, i used "v8iPO4Gik" (base-metrics dashboard) with the right panel id. If i look at debug, it looks like hostalive did not take the right "dashboard uid" , however i remove/add it several times on base-metrics dashboard but it looks like it is handled specifically.

![icingacapture](https://user-images.githubusercontent.com/38788304/39434470-e8e2f358-4c98-11e8-8212-a96768c1a51c.PNG)
![grafanacapture](https://user-images.githubusercontent.com/38788304/39434519-0fec16aa-4c99-11e8-8f5c-cbb67b994a6d.PNG)

**Comment by Mikesch-mp** [comment]
From you picture i can see that Grafana has problems. Please klick on the red corner with ! and see if the error message can help you to fix your problem

**Comment by Mikesch-mp** [comment]
no more fedback -> close
