### ISSUE TITLE
Indirect-proxy-mode not working when using FQDN as hostname

### ISSUE THREAD

**Issue by aschwoerer** [Mikesch-mp/icingaweb2-module-grafana#156]
## Expected Behavior

When using FQDN as hostname graphs should display as in proxy mode.

## Current Behavior

Graph is broken / wont load. Examining the cause shows, that the used URL returns an error 404. The icingaweb2-interface shows a stacktrace.

URL from debug output:
```
Graph URL | http://monitoring.home.local/grafana/img?host=monitoring_home_local&service=apt&panelid=1&timerange=6h&cachetime=59
```
Output in Webinterface:
```
Service not found

#0 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/php/Icinga/Web/Controller.php(87): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/modules/grafana/application/controllers/ImgController.php(235): Icinga\Web\Controller->httpNotFound(String)
#3 /usr/share/icingaweb2/modules/grafana/application/controllers/ImgController.php(143): Icinga\Module\Grafana\Controllers\ImgController->getServiceObject()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\ImgController->indexAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```

## Possible Solution

It seems the problem comes with substitution of periods into underscores (as for graphite) happening to early and using the substituted hostname as hostname for icinga. Probably it would be sufficient to use the original hostname for the URL and substitute it later to match the corresponding graphite metric.

Tested with short hostname and check without special characters in name: Graphs are working correctly.

## Steps to Reproduce (for bugs)
1. Use FQDN as hostname
2. Open a service
3. Graph not working

## Your Environment

* Icinga Web 2 Grafana version (System - About): 
* Icinga Web 2 version and modules (System - About):
icingaweb2 | 2.5.3
director | 1.3.1
doc | 2.5.3
grafana | 1.2.4
monitoring | 2.5.3
* Version used (`icinga2 --version`):
r2.8.4-1
* Operating System and version:
Debian GNU/Linux 8 Jessie
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf icingastatus livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql influxdb mainlog notification

**Comment by Mikesch-mp** [comment]
Nice find. I think i fixed it in latest master. Can you test it please.

**Comment by aschwoerer** [comment]
Thanks for the quick fix.
 
Just tested latest master. This resolves the current issue somewhat... Now the graph ist loading but shows "No data points".

The resulting link to grafana is 
```
http://graphing.home.local/d/000000008/icinga2-default?var-hostname=monitoring.home.local&var-service=apt&var-command=apt&from=now-6h&to=now&orgId=1&panelId=1&fullscreen 
```
It looks like here the substitution should be in place, as metrics are created with substituted chars. In proxy mode the link contains the substitutions and is working as expected:  
```
http://graphing.home.local/d/000000008/icinga2-default?var-hostname=monitoring_home_local&var-service=apt&var-command=apt&from=now-6h&to=now&orgId=1&panelId=1&fullscreen
```
Greetings 
Andreas

**Comment by Mikesch-mp** [comment]
Hmm took not long while listening to Genesis Carpet Crawlers ;) Please test latest master again, just pushed a fix.

**Comment by aschwoerer** [comment]
Thanks again. New version looks promising, Graph is now loading correctly. Link to grafana is still using the dotted version of the hostname.
