### ISSUE TITLE
failure if grafana_graph_disable is not set

### ISSUE THREAD

**Issue by phil-or** [Mikesch-mp/icingaweb2-module-grafana#157]
## Expected Behavior

Services that use templates where the processing of performance data is disabled and the custom vars "no grafana_graph_disable" is unused should show an empty graph, or even better, automatically display no graph.

## Current Behavior

Services that use templates where the processing of performance data is disabled and the custom vars "no grafana_graph_disable" is unused show the failure below:
![failure](https://user-images.githubusercontent.com/36534023/39939452-e0d461dc-5545-11e8-9ccb-35a5d20229b7.JPG)

## Your Environment

* Icinga Web 2 Grafana version (System - About): master, commit 258c37b
* Icinga Web 2 version and modules (System - About): 2.5.3
* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: Centos7

**Comment by Mikesch-mp** [comment]
I was sure i fixed that already. Dont know why itr is in again :( Thanks forreporting it.

**Comment by phil-or** [comment]
Thank you!
