### ISSUE TITLE
HostAlive Grafana does not appear (or services Grafana)

### ISSUE THREAD

**Issue by ulyszk** [Mikesch-mp/icingaweb2-module-grafana#158]
When I set up Grafana module (thank you for that) for Icinga I faced a problem that I haven't got HostAlive grafana in individual host page. I found a perference on Grafana module settings page: Default panel id * and adjusted from 1 to 32. Now I have HostAlive Grafana on Host page but missing Grafanas on Service pages of hosts. Did I configure something wrong? Or is this a bug?

## Expected Behavior
Show HostAlive Grafana on host page and also services Grafanas on service page of hosts.

## Current Behavior
Described above

## Context
I try to set Default panel id * settings. I have no more ide what can I do.

## Your Environment
Icinga Web 2 Version
    2.5.3
Git commit
    ca7e886b820f0145999fdf7377f5c4132301eada
Git commit date
    2018-04-27
grafana | 1.2.4

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
You have new mail in /var/spool/mail/root

Disabled features: compatlog elasticsearch gelf graphite livestatus opentsdb perfdata syslog
Enabled features: api checker command debuglog ido-pgsql influxdb mainlog notification statusdata

**Comment by Mikesch-mp** [comment]
Hello @ulyszk ,

sorry for the late reply. You done everything right, you only have to configure the graph for the hostalive command or you could try the new default [dashboard](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/dashboards/influxdb/icinga2-default-test.json) where i did a trick to get hostalive working without the need to configure the command in the module.

Best regards,
Carsten

**Comment by ulyszk** [comment]
Thank you for the answer!
I tried you new default dashboard, but it does not produce grpahs at all. I have a list of servers, services and commands, but I have "Add row" button instead of any graphs.

**Comment by Mikesch-mp** [comment]
Its not for usage in grafana, it only works in when called from the icingaweb2-module-grafana.

**Comment by ulyszk** [comment]
Okay, I understand, however I cannot see them the from Icingaweb2. I used 1 as Default panel id *. I checked the doc and I see Default panel UID. I have no such field. Also I set panel id to 0 as the documentation suggest, but without success. What should I set fot this new dashboard?

I am using these configuration parameters:
[grafana]
host = "(hostname):3000"
protocol = "http"
defaultdashboard = "icinga2-default"
defaultdashboardstore = "db"
datasource = "influxdb"
accessmode = "direct"
defaultorgid = "1"
shadows = "0"
theme = "light"
height = "480"
width = "640"
enableLink = "yes"
usepublic = "yes"
publichost = "(hostname):3000"
publicprotocol = "http"
timerange = "7d"
debug = "1"
version = "0"
timerangeAll = "1w/w"
defaultdashboardpanelid = "0"
directrefresh = "no"


I found this: https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/images/03-module_grafana_configuration01.png

**Comment by Mikesch-mp** [comment]
You have Grafana Version 4 or 5? If you have Version 5 please enable it in the module configuration, then you will see all needed fields for Grafana version 5.

**Comment by ulyszk** [comment]
I have  Grafana version 4.5.2 currently

**Comment by Mikesch-mp** [comment]
I will create a dashboard for you later this evening, so you can test everything from inside grafana too.

**Comment by ulyszk** [comment]
Dear @Mikesch-mp ,
Did you manege to create dasboard for me?

**Comment by Mikesch-mp** [comment]
I did it, but it was to late yesterday to upload. as soon iam at home again i will upload it.

**Comment by Mikesch-mp** [comment]
I tested the new default panel, and it makes more trouble then it should. It shows wrong performance data for some checks. so i will delete it. If you want a graph for hostalive you have to configure it as written in the [docs](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#hosts)

**Comment by Mikesch-mp** [comment]
Closeing, because of no response anymore.

**Comment by atom83** [comment]
Hallo Mr. Mikesch,

Wir haben das gleiche Problem.
We have the same problem.

Grafana 6.4.3
Influxdb 1.0.2
IcingaWeb 2.7.3

Configured a new graph for the hostalive command like described  in the [docs.](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#hosts)

But graph doas not appear.

graph image looks like this:
![grafik](https://user-images.githubusercontent.com/2320391/70999852-808e7300-20da-11ea-96e4-3357a08a1313.png)

what am I doing wrong?

Thanks

Thomas

**Comment by Mikesch-mp** [comment]
can you supply you graph config for hostalive? Also did you import the provided dashboard or make one yourself?

**Comment by ulyszk** [comment]
Hi,
I will update all part of the stack into the near latest version and report back about my findings.

**Comment by atom83** [comment]
> 
> 
> can you supply you graph config for hostalive? Also did you import the provided dashboard or make one yourself?

sorry for late answer, found the problem. 
had to choose the proper panel ID, then it was working right away.
Cheers
