### ISSUE TITLE
Host Graph no data point (because of check_icmp?)

### ISSUE THREAD

**Issue by MarcusCaepio** [Mikesch-mp/icingaweb2-module-grafana#159]
Hi Carsten, 
thanks a lot for this beautiful module. I am testint it right now and it seems to work pretty well for the services. I am only facing problems with the host check command. I am using check_icmp instead of HostAlive and don't see any graphs for the hosts. Can you tell me please, what I have to change to fix it? 

I already changed the HostAlive metric in the base-metrik dashboard to icmp, and I get the icmp metrics in grafana shown, but not in the module. Using InfluxDB as backend

Cheers,
Marcus

**Comment by Mikesch-mp** [comment]
Hello Marco,

just configure the host check_command as a graph config like you would do it for a service command.

Best regards,
Carsten

**Comment by MarcusCaepio** [comment]
Can you give me a hint how? Did not do anything with grafana so far. Last time is over 1 year ago :D just know your templates by importing them ^^

**Comment by Mikesch-mp** [comment]
Thats a easy one, just read the [docs](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#hosts) 😃

**Comment by MarcusCaepio** [comment]
Hey Carsten, I got it working. But the doc was a little confusing for a beginner :) 
I now solved it by changing the HostAlive check to icmp in the base metrics dashboard and then add this via "graphs" in the module :) Thanks a lot for your help and thanks again for this great module! 

Cheers,
Marcus

**Comment by Mikesch-mp** [comment]
Backends are only needed with Grafana version 4.x. With Grafana 5 it's no longer needed to set a backend.
