### ISSUE TITLE
Graphs of different sizes for one Service

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Mikesch-mp/icingaweb2-module-grafana#160]
Hello. 

Is it possible to create graphics of different sizes for a single Service?

## Expected Behavior

Displaying multiple graphs of different sizes for the same Service:

![graphs-of-different-sizes](https://user-images.githubusercontent.com/17614847/40625298-0a87f468-62a1-11e8-8303-51be551bf12a.png)

## Current Behavior

All graphics have the same size. This is not always convenient.

## Possible Solution

It is necessary to specify several values of the sizes of graphs.

![graphs-of-different-sizes-settings](https://user-images.githubusercontent.com/17614847/40625387-ad06791c-62a1-11e8-8438-6c5994e55310.png)

**Comment by Mikesch-mp** [comment]
Iam sorry thats not possible. I will leave this issue open, maybe i get an idea how to make this possible.

**Comment by Mikesch-mp** [comment]
Just reading this again, why you dont have a single graph for every temperature group?

**Comment by Aleksey-Maksimov** [comment]
> Just reading this again, why you dont have a single graph for every temperature group?

In my example, it is not possible to use one graph for all sensors, as this is logically wrong. Some of the sensors show the temperature, the other part of the sensors shows the speed of the fans.

Mission Impossible? :)

**Comment by Mikesch-mp** [comment]
You can filter in your grafana panel with something like `/^Temp.*CPU.*/` or `/^Temp.*Memory.*/` and so on and trhen use multiple panels to show in the module

**Comment by Aleksey-Maksimov** [comment]
I do. But all charts in Icinga are the same size, and this is very inconvenient. Because one graph can have 20 metrics and another graph can have 2 metrics. And these graphs should have different sizes. That's what I wrote about in my first post.

**Comment by Mikesch-mp** [comment]
Then its not possible with the module
