### ISSUE TITLE
global Configuration for repeating Panel

### ISSUE THREAD

**Issue by n3k232** [Mikesch-mp/icingaweb2-module-grafana#162]
Hey,

it would be nice if we could get the repeating Panel option on Grafana graphs as a global configuration Point. because it would be hard do define a graph for every differnt Service in a big Icinga2 environment.

greetings

**Comment by Mikesch-mp** [comment]
I dont have any idea on how this should work with a global config. ANd you dont have to configure it for every service, you can also use the command name.
