### ISSUE TITLE
Same graph for all checks with same name

### ISSUE THREAD

**Issue by gms1234** [Mikesch-mp/icingaweb2-module-grafana#163]
### My setup:
One master, several clients/satellites. Checks run via service apply rules. Obviously, the checks have the same name. 

### What I want:
I want to have a dedicated graph for all checks. 

### My problem:
If I assign a graph for a check, define the dashboard it runs on, no matter what I do, it shows this graph for all checks with the same name.

### My question:
Is this a feature which is just not implemented, or am I doing something wrong?

```
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.4 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-042stab127.2
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 9c880c2f42f5

Icinga2 version: r2.8.4-1
Icingaweb2 version: 2.5.3
Grafana version: 1.2.5
```

**Comment by Mikesch-mp** [comment]
Please post your module config and the graph config.

**Comment by gms1234** [comment]
![grafana](https://user-images.githubusercontent.com/39398509/41099161-f3ca675a-6a5d-11e8-82b6-c90b53efca13.PNG)
![grafana_graph](https://user-images.githubusercontent.com/39398509/41099164-f4cd2912-6a5d-11e8-8f83-835aa8c69c51.PNG)

**Comment by Mikesch-mp** [comment]
this looks ok, but the default dashboard should show the servicename of the services without a own graph configuration.

**Comment by gms1234** [comment]
What do you mean by this? 

Is it actually possible for the module to show me a dedicated graph for every single check. Let's say I have 5 `linux-load` checks. Now, it shows me one `linux-load` graph. The one I configured. I can not configure any more graphs with the same name, so I only see 1 graph corresponding to the host I configured it for. But on all 5 hosts. 

Is it possible to show a graph for every dedicated host and check, although they all have the same name? And if so, please explain to me how.

**Comment by Mikesch-mp** [comment]
It is for every host, the module sends hostname, servicename , commandoname to grafana, if you use provided templates like the icinga-default it works out of the box. Also for the provided itl dashboards.
If you create your own dashboard you can read the howto in my docs. the important thing is templating, you need to use variables in your dashboard.

**Comment by gms1234** [comment]
I see. 

If I understand you correctly, I have to define one panel, which has all the services and their metrics. I then define the panel ID in the Icinga module, right?

I tried to do that, but when choosing the `$command` variable, I can not choose any further metrics. In Icinga, the names are shown correctly but it says `No data point` on the graph. 

If I use the hard coded `command` name in the panel, it shows the correct host and graph in Icinga, but for all graphs.

**Comment by Mikesch-mp** [comment]
Just import the provided dashboards and play arond with them. just import the right ones, depeding on your backend (graphite or influxdb).

**Comment by gms1234** [comment]
Everything works with the provided templates. Thank you for taking the time!

**Comment by Mikesch-mp** [comment]
Your welcome :)
