### ISSUE TITLE
The default timerange for graphs does not work

### ISSUE THREAD

**Issue by gino0631** [Mikesch-mp/icingaweb2-module-grafana#164]
## Expected Behavior
After changing the Timerange setting in the Grafana module configuration, I expect to get graphs with that timereange by default.

## Current Behavior
Instead, the graphs continue to appear with the default 6h timerange.

## Your Environment
* Icinga Web 2 Grafana version (System - About): 1.2.5
* Icinga Web 2 version and modules (System - About): 2.5.3

**Comment by Mikesch-mp** [comment]
Please post module config and graph config

**Comment by Mikesch-mp** [comment]
I found the bug. lates master gets an update in a minute
