### ISSUE TITLE
Enable link not working for icinga regular useres

### ISSUE THREAD

**Issue by jorfermo** [Mikesch-mp/icingaweb2-module-grafana#165]
I set up in the configuration "Enable link" = true

This is working fine when I log into icinga with the admin users. However if a regular user logs in the charts are not clickable.

## Expected Behavior
Clicking on a chart should forward the user to the grafana chart

## Current Behavior
Charts are not clickable

## Your Environment
* Icinga Web 2 Grafana version: master
* Icinga Web 2 version and modules: 2.5.3
* Version used: r2.8.4-1
* Operating System and version: ubuntu 16.04
* Enabled features: api checker command compatlog graphite ido-mysql livestatus mainlog notification
* Config validation: Finished validating the configuration file(s).

**Comment by Aleksey-Maksimov** [comment]
Hello,

Just try to set up permissions in Icinga Web:

Configuration > Authentication > Roles > Permissions Set

* Allow to follow links to Grafana (grafana/enablelink)

**Comment by jorfermo** [comment]
That made the trick! Links are clickable now but the result is an empty graphana chart.

This is console output:

`Failed to load *** render: Request header field X-Panel-Id is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by Mikesch-mp** [comment]
Do you allow anonymous access in grafana? If user is not logged in he will not see any graph he is not allowed to. Canyou add your modules config.ini please and tell us your configuration like grafana version, icigaweb2 version and module version.

Regards,
Carsten

**Comment by Mikesch-mp** [comment]
No more feedback -> closing.
