### ISSUE TITLE
Graf fall back to picked time after manual zoom

### ISSUE THREAD

**Issue by cadirol** [Mikesch-mp/icingaweb2-module-grafana#166]
Hy guys
I'm really fan of the grafana Module!
To use the manual zoom feature (with the small cross) to gain specific time range, i use the direct mode. Unfortunately, the graf falls back to the default time setting after the automatic page reload of icingaweb2. I allready disabled the reload feature of icingaweb2, this did the trick, but the whole page was not reloaded anymore... (as expected)
it would be great if the setting/feature exist, to preserve the manual zoomed timerange. 
Or to disable a "Refresh on direct" setting, same as "Refresh on indirect proxy"

Thank you very much for your work!
Best regards cadirol

## Your Environment
* Icinga Web 2 Grafana version (System - About): 2.5.1
* Icinga Web 2 version and modules (System - About): grafana | 1.2.5
* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: Ubuntu 16.04
* Enabled features (`icinga2 feature list`): api checker ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
Hello @cadirol,

iam sorry. But there is no way to disable the automatic pagereload inside a hook (at the moment).
The refresh on prxy is only a trick by appending a timestamp to the image url, so the browser will always load the image rather then from local cache :)

Regards,
Carsten
