### ISSUE TITLE
Possibility to change refresh time

### ISSUE THREAD

**Issue by pcasis** [Mikesch-mp/icingaweb2-module-grafana#17]
Hi hi, :smile:

It would be nice to be able to change the *refresh time* of the graph.
If I look inside the logs, I can see that the current graph is rendered every 10 seconds (approx).
In a way, it is nice to get fresh values. However it creates some traffic that I don't necessarily need.

What I ask for is the possibility to enable or not the refresh of graphs.
So when I click on a host/service I get a "screenshot" of the graph than isn't dynamically refreshed.

Regards and thx for your work :-)

```
t=2017-03-27T10:59:09+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/icinga2-default?var-hostname=fro1vmonitor2&var-service=hostalive&panelId=2&width=640&height=280&theme=light&from=now-30m&to=now"
t=2017-03-27T10:59:21+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/icinga2-default?var-hostname=fro1vmonitor2&var-service=hostalive&panelId=2&width=640&height=280&theme=light&from=now-30m&to=now"
t=2017-03-27T10:59:32+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/icinga2-default?var-hostname=fro1vmonitor2&var-service=hostalive&panelId=2&width=640&height=280&theme=light&from=now-30m&to=now"
t=2017-03-27T10:59:44+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/icinga2-default?var-hostname=fro1vmonitor2&var-service=hostalive&panelId=2&width=640&height=280&theme=light&from=now-30m&to=now"
t=2017-03-27T10:59:55+0200 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/icinga2-default?var-hostname=fro1vmonitor2&var-service=hostalive&panelId=2&width=640&height=280&theme=light&from=now-30m&to=now"
```

**Comment by Mikesch-mp** [comment]
Hi,

that cant be only done in the icingaweb2 sourcecode. Iam not aware of any option to change the default of 10 seconds. But there is a change coming for hooks soon (got the info at the Icinga Camp in Berlin), maybe then there is an option to change it for hooks.

Regards,
Carsten
