### ISSUE TITLE
Repeatable panels + metrics per panel

### ISSUE THREAD

**Issue by benohara** [Mikesch-mp/icingaweb2-module-grafana#171]
Using check_netint.pl, im getting (I think) 6 'metrics' per interface

$interface_in_bps
$interface_out_bps
$interface_in_errrors
$interface_out_errors
$interface_in_discards

In grafana, I've a dashboard with one repeatable graph, 'Network $interface' and in icingaweb2-grafana config I've configured the graph as 'repeatable' and 'metrics per panel = 6'

When I view in grafana its all fine, finds the $interface variable from lookup and shows 7 panels, one per interface with the 6 metrics on each panel.

When I view in icingaweb2, I see the expected 7 panels (one per interface), but then 35 'Error: cant fetch graph' 

With 7 interfaces, 1 metric per graph would generate 42 graphs? Which looks to be whats happening rather than using the '6 metrics per panel' config value.

Am I right in my thinking of how this should work with metrics per panel setting?

Cheers

**Comment by Mikesch-mp** [comment]
can you post your dahboard please, i will take a look on it as soon i have time.

**Comment by Mikesch-mp** [comment]
Is the dashboard also configured to repeat the panels ?

**Comment by benohara** [comment]
In grafana, the 'panel' is, like so

<img width="967" alt="screen shot 2018-07-16 at 10 52 14 pm" src="https://user-images.githubusercontent.com/415124/42759617-f844fa96-894a-11e8-9e8f-93b7a2116c94.png">

And in dashboard settings, the $interface variable correctly pulls out the interface names.  I do have the 'All value' enabled on the variable and if I then select 'all interfaces' and change hosts, it correctly renders panel , and if the host has more than one interface, panels 7-X.  Also the panel isn't in a row

Ben

**Comment by Mikesch-mp** [comment]
Doesnt matter if it is an row or not, the panel ids are important.

If you want i can try to get a closer look via remote desktop session (webex,teamviewer,whatever), i think its only a small thing i maybe forgot to write into the documentation.

**Comment by benohara** [comment]
Cheers, that looks better and only shows the required graphs.

Ben
