### ISSUE TITLE
View all graphs and grafana_graph_disable

### ISSUE THREAD

**Issue by benohara** [Mikesch-mp/icingaweb2-module-grafana#172]
If I set grafana_graph_disable = true on a service, the graph DOES disappears from the service page but still attempts to get displayed on the 'View All Graphs' page, linked from the host overview.

Cheers
Ben

**Comment by Mikesch-mp** [comment]
Thanks for reporting

**Comment by benohara** [comment]
I also had to change (default i think) the alltimeperiod from last week, which seems to be 1w/w to last 12 hours, otherwise the 'all graphs' page wouldnt display the graphs

**Comment by Mikesch-mp** [comment]
Taht only depends of the power of the grafana server. i install at least 2 servers and set them to rounf robin in the load balancer. Also its better to have a lot of cpu power for the grafana vm (+ a lot of ram for influxdb server if influxdb is used)

**Comment by dfrise** [comment]
First thanks for this awesome module!
Uising 1.2.5 module, we also see the issue that a disabled graph will show up in the "Show all graphs" page.

Dominique

**Comment by MarcusCaepio** [comment]
> Uising 1.2.5 module, we also see the issue that a disabled graph will show up in the "Show all graphs" page. 
>
Me too
> I also had to change (default i think) the alltimeperiod from last week, which seems to be 1w/w to last 12 hours, otherwise the 'all graphs' page wouldnt display the graphs
>
I think, this affected me too at 
#175

**Comment by dfrise** [comment]
Is working now as expected, Thanks !
