### ISSUE TITLE
No graphs for unavailable services

### ISSUE THREAD

**Issue by WojciechPolnik** [Mikesch-mp/icingaweb2-module-grafana#177]
I  am using agent architecture in icinga: 1 icinga master and a lot clients(in the future also satellites). Clients and master are on different hosts.
On master I have also grafana installed and icinga module for icinga2web. Grafana works well

Issue: When service is unavailable there is no graph for this service.
I checked these scenarios:
1. when host is unavailable(its icinga client) I get no graphs/panels for all services for this host
2. when host is available(its icinga client) I get graphs only for its available services, for unavailable services no graphs
- static positive checks have no effect
- state (ok/critical/unknown) does no matter

When services becomes available, I can see its graph immediately.

## Expected Behavior

I believe that if we have remote hosts/services unavailable we should still see theirs graphs/panels so we have history what happened, when and what was the state before failure.

## Current Behavior

When service/host is unavailable there is no graph for this service/host.

The site loads faster for "proxy" mode lile if this module was not loaded at all

## Possible Solution

I have no idea what's the flow of icingaweb2-module-grafana but it looks like the bug is the flow/ module loading. 
I have no clue why it depends on availability of host, why not just grafana and its dashboards/panels

## Context

I checked these scenarios:
1. when host is unavailable(its icinga client) I get no graphs/panels for all services for this host
2. when host is available(its icinga client) I get graphs only for its available services, for unavailable services no graphs
- static positive checks have no effect
- state (ok/critical/unknown) does no matter

## Your Environment

* Icinga Web 2 Grafana version (System - About):
1.2.5
* Icinga Web 2 version and modules (System - About):
icinga2 - 2.9.1-1
os - CentOS7

**Comment by Mikesch-mp** [comment]
hello,

tomorrow i will release 1.2.6. So please download it tomorrow and test if the problem still is there. I had that code put in for a short time, until i saw its also showing no graph when in critical and removed it again.

regards,
Carsten

**Comment by Mikesch-mp** [comment]
found it, sometimes i hate git.... bug is fixed in 1.3.1
