### ISSUE TITLE
Indirectproxy multiple panels show one panel multiple times

### ISSUE THREAD

**Issue by WojciechPolnik** [Mikesch-mp/icingaweb2-module-grafana#178]
For indirectproxy access to grafana, if you set **panelId** to "4,9" it shows only 4th panel but two times

## Expected Behavior

It should show two panels, one 4th and one 9th, they are different.

## Current Behavior

It shows two times same 4th panel

## Steps to Reproduce (for bugs)

use indirectproxy and set panelId in graph.ini to more than one panelId

## Context

It **works** for "proxy" mode but it **does not** for "indirectproxy"
just example:
[mem]
dashboard = "xx"
panelId = "4,9"
dashboarduid = "xx"

## Your Environment

Icinga Web 2 Grafana version (System - About):
1.2.5
Icinga Web 2 version and modules (System - About):
icinga2 - 2.9.1-1
os - CentOS7

**Comment by Mikesch-mp** [comment]
Please try 1.3.0 and test again, for me it works perfect.

![image](https://user-images.githubusercontent.com/6574967/44087071-e07427ae-9fbe-11e8-90dd-0da57a898627.png)

![image](https://user-images.githubusercontent.com/6574967/44087002-ae535cae-9fbe-11e8-9ba4-9220988b7188.png)
![image](https://user-images.githubusercontent.com/6574967/44087032-c38d2a96-9fbe-11e8-9a4e-6f5f4c9eabe7.png)

**Comment by WojciechPolnik** [comment]
Sorry I may have missed one thing which I've just discovered: it happens for host, not service.
