### ISSUE TITLE
Is it possible to use Regex in Grafana Config

### ISSUE THREAD

**Issue by MarcusCaepio** [Mikesch-mp/icingaweb2-module-grafana#179]
Hi Carsten,
sorry that I have to open an Issue for this.
First, thanks for all the help, I am on a really good way right now. Everything looks shiny.
I am just struggeling with one situation.

For the service "disk: ...." I have 3 different check commands: 
- disk for icinga hosts 
- by_ssh for linux hosts 
- by_wmi for windows hosts 
For each check_command, there are 2 kind of services: "disk:all partitions", which is my default service, spreaded by an template and "disk:XYZ" which appears, when sb. defines an dictionary (this also disables the all partition check) in an host config. I have a grafana panel called "disk" which already shows all three kinds of check_commands, depending on the host I choose. What I now need, is a way to use sth. like "disk:*" in the module config to lead the module to my default dashboard with the disk panel.

E.G.: In the module config I set the graph with the name "disk:all partitons" to my def. dashboard with the panel id, the Icingaweb preview shows the right graph for the service "disk:all partitions". But if I want the preview of "disk:/var/lib" the module leads to the "icinga-default" dashboard as long as I set "disk:/var/lib" in the module config.
As I don't want to set every single possible mountpoint, I need sth. like "disk:*", which always leads to my default dashboard with the disk panel id.
This regex would fit everything. is that anyhow possible?

Cheers,
Marcus

**Comment by Mikesch-mp** [comment]
Hello @MarcusCaepio ,

iam sorry but thata would not be possible. Icingaweb2 uses Zendframework and there is no working solution to use regex to find a matching configuration in a ini file. 

But you can use the [custvarconfig](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/03-module-configuration.md#custvarconfig) option in your services/apply rules to tell the module which dashboard it should use. For example you have a graph configuration for your disks named `my_disk_services` then you can add to your service/apply rule this line and it will use the graph configuration you put into the custom variable no matter what service name/command name is used.

```
   vars.grafana_graph_config = "my_service_graphconfig"
```
The other option is to name your services with a space after "disk:" , then you would also need only 1 graph configuration for service names `disk: `* . It would match then all service names that start with "disk:"

Best regards,
Carsten

**Comment by MarcusCaepio** [comment]
Thanks Carsten, will try it! :) 👍
