### ISSUE TITLE
Selecting any "Special" timerange breaks graph in module but following link to Grafana works

### ISSUE THREAD

**Issue by bw00sy** [Mikesch-mp/icingaweb2-module-grafana#182]
## Expected Behavior

Special timerange for previous days, weeks, months etc should select that timerange for the grafana graph.
## Current Behavior

The graph shows a red exclamation mark in the top left and the graph is empty. Clicking on the graph to open in Granafa, shows the graph working with the selected timerange. 
## Steps to Reproduce (for bugs)

1. Allow links on Grafana module.
2. Select "Special" timerange on graph
3. Click on link of "broken" graph

## Context

Was trying to select a Special timerange
## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.1 (patched the custom timerange as per issue #180 )
* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.8.1-1
* Operating System and version: Ubuntu 18.04.1 LTS
* Enabled features (`icinga2 feature list`):
Disabled features: debuglog elasticsearch gelf graphite opentsdb syslog
Enabled features: api checker command compatlog ido-mysql influxdb livestatus mainlog notification perfdata statusdata
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
It works in proxy/direct mode  but not in indirect proxyy mode. Thanks for reporting
