### ISSUE TITLE
Link to Grafana - Permission

### ISSUE THREAD

**Issue by phil-or** [Mikesch-mp/icingaweb2-module-grafana#183]
We have been using your module for several months and we are very happy with it. 
We enabled the link to Grafana and when you are redirected to Grafana you can see all dashboards.
But now, we have the problem, that some Icinga users shouldn't be allowed to switch to other dashboards in Grafana.
Is there a way to configure it?
In Grafana i can't configure a permission, that a user can't change a dashboard.
I think that might be a solution? https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/147 

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.2
* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.9.2

**Comment by Mikesch-mp** [comment]
There is nothing i can do, as long we cant have user settings for modules. Then we could set the company id per user for example to have something like a own environment of Grafana for each user (but you have to copy every dashboard to every company :( ).
