### ISSUE TITLE
Change graph size when adding new Graphana Graphs

### ISSUE THREAD

**Issue by mattg-92** [Mikesch-mp/icingaweb2-module-grafana#19]
Hi with adding new graphs using the  "Add New Grafana Graph" option would it be possible to add the ability to override the configuration width and height for each custom graph, or can i do that maunually from within the config file?

**Comment by mattg-92** [comment]
all good i modified a copy of the code to include this ability, if i knew how id add it to your code base but not 100% on how i do that

**Comment by Mikesch-mp** [comment]
Hi,

added this in 1.0.7.
