### ISSUE TITLE
No Graph shown on master since commits from 10.12.2018

### ISSUE THREAD

**Issue by wolf-in-sheeps-clothing** [Mikesch-mp/icingaweb2-module-grafana#192]
## Expected Behavior
Graphs should be shown :-)

## Current Behavior
Yesterday after git pull no graphs shown. The module shows only a number. I think it's the Panel ID

Examples:

![image](https://user-images.githubusercontent.com/31659047/49886561-3ffe7880-fe3a-11e8-9ef0-659bb2e03dd5.png)

![image](https://user-images.githubusercontent.com/31659047/49886605-63c1be80-fe3a-11e8-95cf-cabc8458c9dd.png)

After git checkout v1.3.2 everything is fine.

By the way: with git pull commits from 05.12.2018 everything works fine too!
## Possible Solution
I hope you know! ;-)

By the way, I love your work and your module.

## Steps to Reproduce (for bugs)
Use master with all new commits

## Your Environment

* Icinga Web 2 Grafana version (System - About): Master, but now v.1.3.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 16.04.5 x64

**Comment by Mikesch-mp** [comment]
Master is always my playground to test new code :) so please use it only if i ask you to test it.
At the moment iam not at home, but i will fix it untill sunday, because i want to release new version on sunday.

**Comment by wolf-in-sheeps-clothing** [comment]
Hey, that was no criticism.
I don't use master in my prod, only sometimes on my testsystem! This should only a note to a found "bug" so that this didn't went to release. It'm fine.

**Comment by Mikesch-mp** [comment]
I didnt took it as criticism, see the smily
