### ISSUE TITLE
Docs: Provide a code snippet for config.ini

### ISSUE THREAD

**Issue by dnsmichi** [Mikesch-mp/icingaweb2-module-grafana#2]
Mainly a documentation issue, I don't know how to exactly put that into `/etc/icingaweb2/modules/grafana/config.ini`. Would be helpful as well to get a step-by-step setup documentation.

**Comment by Mikesch-mp** [comment]
I added some text with the steps needed and also a sample of the config.ini.

**Comment by dnsmichi** [comment]
Cool thanks ❤️
