### ISSUE TITLE
Display selected time range

### ISSUE THREAD

**Issue by kogaba** [Mikesch-mp/icingaweb2-module-grafana#200]
It is rather a "pull request", because I couldn't find any way to show the selected timerange, so I made this simple modification:
```
library/Grafana/ProvidedHook/Grapher.php
  $menu .= '<td><div class="grafana-icon"><div class="grafana-clock"></div></div>'.$this->timerange.'</td>';
```
Please add it to the code
Thanks for the module!

**Comment by Mikesch-mp** [comment]
I will takea a look after my vacations

**Comment by kogaba** [comment]
Thanks!
I modified the corresponding less file a bit also:
![screenshot from 2019-02-15 17-46-16](https://user-images.githubusercontent.com/22454806/52871278-fd169500-3149-11e9-844e-fac57acf83b4.png)

grafana/public/css/module.less
div.grafana-icon {
  height: 32px
-  width: 32px;
+ width: 28px;
  position: relative;
  margin: 0px;
  overflow: hidden;
  display: inline-block;
+  vertical-align:middle;
}

**Comment by BorisTrnka** [comment]
(thumbs up)

**Comment by Mikesch-mp** [comment]
will be in 2.0.0
