### ISSUE TITLE
Graphs are Not Populating in Icinga2web

### ISSUE THREAD

**Issue by gintisaurabh** [Mikesch-mp/icingaweb2-module-grafana#201]
Uncaught Error: Class 'Icinga\Module\Grafana\Helpers\Timeranges' not found in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php:503

**Comment by Mikesch-mp** [comment]
How did you install the module? Sounds there are files missing.

**Comment by gintisaurabh** [comment]
Thanks for reply,downloaded the rpm and isntalled it.

 wget https://dl.grafana.com/oss/release/grafana-5.4.3-1.x86_64.rpm
yum install grafana-5.4.3-1.x86_64.rpm
wget https://dl.influxdata.com/influxdb/releases/influxdb-1.7.3.x86_64.rpm
yum install influxdb-1.7.3.x86_64.rpm
/etc/init.d/grafana-server enable

i have created that file manually from a sample file and the error is gone but not i am getting "Dashboard not available" for all the commands/service.

**Comment by Mikesch-mp** [comment]
Thats not how you installed the MODULE. Did you do a git clone installation or downloaded the tarball and extracted it. Also please post your module config.ini.

**Comment by gintisaurabh** [comment]
Hi Mike,

I have directly downloaded the rpm and installed it as i mentioned it above.

below is the link for exact error also the config.ini is pated below.

![image](https://user-images.githubusercontent.com/44056238/53289941-48bce480-37c3-11e9-8c8a-b0dc1dd16d68.png)


[grafana]
version = "0"
host = "localhost:3000"
protocol = "http"
timerangeAll = "1w/w"
defaultdashboard = "Test"
defaultdashboardpanelid = "1"
defaultorgid = "1"
shadows = "0"
defaultdashboardstore = "db"
theme = "light"
datasource = "influxdb"
accessmode = "iframe"
debug = "0"
timerange = "3h"

**Comment by gintisaurabh** [comment]
sorry for the confusion yest i have downloaded the tarball and extracted it.

created one script for the same and executed it

/root/file.sh
ICINGAWEB_MODULEPATH="/usr/share/icingaweb2/modules"
REPO_URL="https://github.com/icinga/icingaweb2-module-director"
TARGET_DIR="${ICINGAWEB_MODULEPATH}/director"
MODULE_VERSION="1.6.0"
URL="${REPO_URL}/archive/v${MODULE_VERSION}.tar.gz"
install -d -m 0755 "${TARGET_DIR}"
wget -q -O - "$URL" | tar xfz - -C "${TARGET_DIR}" --strip-components 1

**Comment by Mikesch-mp** [comment]
You need to configure it correctly. First set grafana version to 5, then you need the name of the dashboard + the uid of the dashboard. Did you enable anonymous access? If not, use basic auth or better use a token for authentication.

**Comment by gintisaurabh** [comment]
[root@Machine]# grafana-server -v
Version 5.4.3 (commit: 6539180, branch: HEAD)
{]# rpm -qa | grep grafana
grafana-5.4.3-1.x86_64

**Comment by Mikesch-mp** [comment]
Please go to the module configuration page in icingaweb2 and set all options needed. Also a look into the docs could help

**Comment by gintisaurabh** [comment]
Thank You Mikesch, It is working Now.

2 queries.

1. It is necessary to create grafana DB on Influx?
2. to add hosts and services can you please guide me for some link which can help me.

**Comment by Mikesch-mp** [comment]
You only need the DB for Icinga in Influx. But you can use other DBs too if you want.
The module ships some dashboards for ITL commands from Icinga2, if you want to create your own dashboards you can read the [docs](https://github.com/Mikesch-mp/icingaweb2-module-grafana/tree/master/doc), browse the icinga community boards, download examples from Grafana or use Google search.

If you dont want to use the default dashboard for host/service checks you have to configure them, see [Graph Configuration](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md) .

If your Problem is solved, please close this issue.

Best regards,
Carsten

**Comment by gintisaurabh** [comment]
Thanks, closing Now.
