### ISSUE TITLE
Module unusable with Grafana 5.2.4

### ISSUE THREAD

**Issue by davehayes** [Mikesch-mp/icingaweb2-module-grafana#205]
This module appears to be unusable with Grafana 5.

## Expected Behavior

One should be able to see stable updating graphs on a host/service's detail column. This should not bog the server down with multiple repeated rendering requests nor cause the graph to go away after 2 seconds because it takes 8 seconds to render the graph.

## Current Behavior

The icingaweb2 page refreshes every 10 seconds or so, allowing alerts to appear quickly. However, if you embed Grafana graphs in this page, they will refresh every 10 seconds or so as well. 

There is no grafana accessmode that I found that is useful for this idea. It seems there are only two effective choices (correct me if I am wrong). 

Most modes try to run a javascript rendering process. This process as of grafana 5 takes quite a long time, longer than the 10 second window for refreshing. Nothing is seen for a lot of compute time spent (the process is eventually killed by grafana).

The iframe mode is just as bad because after about 8 seconds you see the graph, which will get refreshed in another 2 seconds. 

## Possible Solution

As with all web development, it looks like the only solution is a rearchitecture of icingaweb2 to use async ideas and not refresh the entire page when it needs to change something. I do not claim to be an expert on icingaweb2, so I don't know if this is possible or even if I have this right. 

## Context

This module is a great idea! I wanted to see grafana graphs next to my services. That's all. 

## Your Environment

* Icinga Web 2 Grafana version (System - About): 5.2.4
* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): r2.9.2-1
* Operating System and version: FreeBSD 11-STABLE
* Enabled features (`icinga2 feature list`): api checker debuglog graphite ido-pgsql mainlog notification
* Config validation (`icinga2 daemon -C`): not willing to post this data

**Comment by Mikesch-mp** [comment]
I would say your dashboards are the problem. for me i have no problems with multiple graphs for one service and grafana is running on a single core celeron cpu. And for refreshing, you can use direct mode with disabled refresh or indirect proxy mode with refreshes the graph only when there is new data to see.

**Comment by davehayes** [comment]
Hm, according to my understanding of this it doesn't use a custom dashboard but the dashboards your module had me import. Are you saying those might be set up wrong?

Here's what is in my config.ini from the last thing I tried:

`version = "1"
host = "redacted.com"
protocol = "https"
accessmode = "direct"
username="redacted"
password="redacted"
timerangeAll = "1w/w"
defaultdashboard = "icinga2-default"
defaultdashboardpanelid = "1"
defaultorgid = "1"
shadows = "0"
defaultdashboardstore = "db"
defaultdashboarduid = "ceEf01_mz"
theme = "light"
debug = "0"
directrefresh = "no"
height = "280"
width = "640"
enableLink = "yes"
`
I had direct mode with direct refresh set up. The indirectproxy mode sounds better, but I'm unclear how to set that up and how it works. Direct mode seems to put a link to the grafana dashboard into the icingaweb2 page and that is going to refresh every 10 seconds. What does indirectproxy do?

It could be that this issue comes down to the fact that I am just not understanding the accessmode and exactly what it does. I have nginx proxies for some of the modes because of how things are set up (I use a unix domain socket for grafana if you remember the other issue). This is what I have to do for grafana in nginx:

```
location /grafana/ {
              error_log /var/log/nginx/grafana.elog warn;
              index index.html index.htm;
              proxy_pass http://unix:/sockets/grafana:/;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_buffers 64 4m;
          } 
```

**Comment by Mikesch-mp** [comment]
Direct mode -> User loads the rendered picture
Proxy mode - > Icingaweb2 loads the picture, but user can see the link is to grafana in the page source
Indirectproxy mode -> Icingaweb2 loads the picture and user only see icingaweb2 as source in the page source

**Comment by Mikesch-mp** [comment]
Sorry for late reply, had a hard time

**Comment by davehayes** [comment]
No worries. Thanks for the clarification. It's still unclear what I should use; graphs change every 10 seconds and I want the current graph to show, but this means rendering it and something has to do that. I'll get back to you here when I stop having a hard time too. ;)
