### ISSUE TITLE
Direct control of service graphs

### ISSUE THREAD

**Issue by muadddib** [Mikesch-mp/icingaweb2-module-grafana#207]
Hi community,

I need a help with tricky issue. I have some customized Grafana graphs, I want to display for specific services in Icinga.

Could you please point me to some detailed guide? Is this possible?

The intention is to display graph No. 1 only when there is specific name fo service(s) or some custome variable value and to display graph No. 2 for other combination of values. I am looking for something similar as Service Apply Rules when telling which graphs should be displayed where. I am looking for straighforward logic for 1:1 service:graphs assignment.

Per reading other discussions I can have graphs with custome variables from Icinga but that does not really fit this intention.

I can switch off defaut graph with variable and I would like to display others when some other variable is set. I really cannot use graphs with lot of customr variables and pass them for heavy variatey of checks which do no share options.

## Expected Behavior
I would like to have similar system of condition for grpahs as for Service apply rules.

## Current Behavior
I guess I should not comment this one.

## Possible Solution
No idea. Could you please help?

## Steps to Reproduce (for bugs)
No steps. It is a question.

## Your Environment

* Icinga Web 2 Grafana version (System - About):
* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

I have no saftware error when using all in latest versions - all downloads are one month old at worst. I have Icinga2 + Director+ Grafana and this (otherwise) really cool plug-in.

**Comment by kogaba** [comment]
Not sure what you want, but you can set grafana dashboard + panelid for every service in icingaweb2, based on the service name or check_command. 
https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md

**Comment by Mikesch-mp** [comment]
You can use the customvariable `custvarconfig` to change the dashboard that is used. The modules searches this variable in each service and then use the dashboard that is configured for this service.

With the Icinga2 DSL you can do something like

```
apply Service "prefix-" for (key => value in host.vars.dictionary) to Host {
  import "generic-service"
  
  if(regex("^Blubber", value)) {
     vars.grafana_graph_config = "Service_ABC_VariantA"
  } else {
     vars.grafana_graph_config = "Service_ABC_VariantB"
 }
  check_command = "ping4"
  vars.host_value = value
}

```
It will load the configured graph named "Service_ABC_VariantA" only when the `value` starts with "Blubber", if not it will load the configured graph named "Service_ABC_VariantB".

**Comment by kogaba** [comment]
Ok so it is possible, now I am just curious what are the circumstances when different graph needed for the same service.

**Comment by Mikesch-mp** [comment]
Is this issue solved for you? IF yes please close it.

**Comment by Mikesch-mp** [comment]
Closing because of no reaction
