### ISSUE TITLE
Problem with unknown Datasource

### ISSUE THREAD

**Issue by Net-Felix** [Mikesch-mp/icingaweb2-module-grafana#208]
to fix file library/Grafana/ProvidedHook/Grapher.php

line 538 should be fixed:

if ($dataSource == "graphite") {
to this:
if ($this->dataSource == "graphite") {

**Comment by Mikesch-mp** [comment]
Hmm which version are you using?

**Comment by Net-Felix** [comment]
Hi,

i fetched latest git master

**Comment by Mikesch-mp** [comment]
I fixed that in my IDE already, but forgot to push it :( Thanks for the bug report.
