### ISSUE TITLE
Graph render performance slow

### ISSUE THREAD

**Issue by shakalandy** [Mikesch-mp/icingaweb2-module-grafana#21]
We are experiencing slow render performance (2-3 sec) for graphs with default values:
```
Graph height The graph height in pixel, default: 280
Graph width The graph width in pixel, default : 640
Timerange The global time range for the graphs, default: 6h
```
We are fetching the graphs from localhost. 
how can the the render time be improved?
Is it solely depending on grafana? or graphite?

(we activated render logging in graphite, takes usualle 0,00x seconds for graphite to render - so much overhead lost on the way?)

Thanks!

**Comment by Mikesch-mp** [comment]
Hi,

Rendertime depends on Grafana, the amount of data that is queried. For my test systems it takes only about 2 to 4 seconds with InfluxDB (running on same host on a intel celeron). With Graphite on a other host (but still on same celeron) it takes also only about 2 to 4 seconds (only tested with ping4 service). Which php version you use? My test enviroment runs with php 7.1.x
 See my screenshot with the timestamps before and after rendering the graphs

Graphite:
![image](https://cloud.githubusercontent.com/assets/6574967/24836093/3d1d195a-1d13-11e7-9973-bb2964b5e536.png)


InfluxDB:
![image](https://cloud.githubusercontent.com/assets/6574967/24836097/63d15610-1d13-11e7-9c54-cb582d9d09ff.png)

**Comment by shakalandy** [comment]
yeah, that is what we see on our side. Comparing to good old pnp the rendering takes quite some time and results "hey everything is slow after migration" feeling ;)
Would it be possible to lazy-load the graphs via ajax or similar so that the rendering doesn't block the rendering of the page?

**Comment by friesoft** [comment]
We also see a performance hit in displaying the host/service pages because the page waits for the graph to be rendered by grafana. +1 for lazy loading :)

**Comment by Mikesch-mp** [comment]
I will add an direct link mode to the module.

**Comment by Mikesch-mp** [comment]
Added direct access, speeds up page load, but you need `auth.anonymous` enabled in the Grafana server settings.
