### ISSUE TITLE
Timelegend is shown UTC and not Browser / php time

### ISSUE THREAD

**Issue by fl0wx** [Mikesch-mp/icingaweb2-module-grafana#215]
## Expected Behavior
Showing local timezone in grafana graphs

## Current Behavior
Shows utc timestamps in grafana graph legend

## Context
I found this issue: [Issue107](https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/107) but i cannot fix the issue with setting server timezones.

GrafanaServer Timezone:
```
 php -i | grep timezone
Default timezone => Europe/Berlin
date.timezone => Europe/Berlin => Europe/Berlin
```
IcingaServer Timezone
```
 php -i | grep timezone
Default timezone => Europe/Berlin
date.timezone => Europe/Berlin => Europe/Berlin
```

If i open the link directly in grafana, it shows the correct times.
Screenshot from Icinga2 Grafana graph:
![image](https://user-images.githubusercontent.com/2448081/61796933-b464b580-ae26-11e9-8046-48251db3ac68.png)

Screenshot from Grafana directly:
![image](https://user-images.githubusercontent.com/2448081/61796961-c3e3fe80-ae26-11e9-8c8d-c7688fe37c9b.png)

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.4
* Icinga Web 2 version and modules (System - About): 2.6.3
* Version used (`icinga2 --version`): r2.10.5-1
* Operating System and version: cat /etc/debian_version -> 8.11
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite icingastatus livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`): everything OK

**Comment by Mikesch-mp** [comment]
Check you user settings in Grafana. There oyou can also set a default timezone.

**Comment by fl0wx** [comment]
@Mikesch-mp : Thanks, in Grafana the timezone is set to "Browser". The Visualization in Grafana also shows the correct time, as you can see in the post above.
![image](https://user-images.githubusercontent.com/2448081/62027114-2baa9880-b1dd-11e9-8d9b-e1c413195577.png)

I will take a look at the grafana.ini if there is something

**Comment by Mikesch-mp** [comment]
Then it must be the server timezone. Grafana dont use php settings, it uses the timezone set for the server it runs on by default.

**Comment by fl0wx** [comment]
Thanks, setting the server timezone solves the problem:)
