### ISSUE TITLE
Question concerning the 2 dashboards

### ISSUE THREAD

**Issue by tetanushamster** [Mikesch-mp/icingaweb2-module-grafana#216]
In chapter 2 of the docs we need to import 2 dashboards provided by the project. I am currently using grafana 6 which seems to require a dashboard uid (random string, visible in URI).
Said UID is also required when configuring the module (version 1.3.5) for icingaweb2 (default dashboard uid). Using the same UID for both dashboards (icinga2-default and base-metrics) results in weird behaviour as grafana seems to so a round robin over both dashboards. Since i can only provide one uid for the module config i fail to see how the other dashboard can be located by the module.

The function of the dashboards in general remains somewhat of a mystery for non-"grafana-natives". I seem to be getting useful graphs even when importing only the icinga2-defaults dashboard.

Can you shed some light on the functionality of said dashboards?

* Icinga Web 2 version and modules : 2.7.0 (grafana / monitoring) + influxdb

Great project, makes icingaweb2 so much more useful.

**Comment by Mikesch-mp** [comment]
Why you use a U(nique)ID on two different dashboards? Each dashboard should have its own UID. IF you configure wrong UIDs i cant really help you.

**Comment by tetanushamster** [comment]
That was just an example to highlight my point, the behaviour with 2 dashboards having the same UID (--> roundrobin) isn't useful. Sorry for the confusion.

What i'm trying to get at is as follows: 

Lets say i've imported the 2 dashboards (icinga2-default and base-metrics).
icinga2-default gets the UID "aaa" and base-metrics gets the UID "bbb".
Now that i have those UIDs i can configure the icingaweb2 grafana module. I can only set 1 UID in the module config as the "default dashboard uid". So in my understanding the other UID is not known to the module and can't be guessed. Since the UID is needed in the GET Request as part of the URI path i assume that one of those dashboards simply won't be visible in icingaweb2.

I've seem to got it working by only configuring the UID of icinga2-defaults in the module, at least i can see some graphs in icingaweb2. 

I would like to understand how "base-metrics" is needed as part of the module and if my configuration is correct, since the documentation doesn't really mention this case for Grafana 5+

**Comment by Mikesch-mp** [comment]
You can configure one default dashboard, but many other dashboards under the graph configuration that will be used by service name or command name etc.

**Comment by tetanushamster** [comment]
So the base-metrics dashboard must be referenced by an additional graph in the module config when using grafana >= 5 ?

**Comment by Mikesch-mp** [comment]
To give you an idea how it works
![image](https://user-images.githubusercontent.com/6574967/63044603-db1a8700-bece-11e9-8541-7b72b457ad6a.png)

**Comment by tetanushamster** [comment]
Thank you ill give this a shot.
