### ISSUE TITLE
[Feature request] Custom vars in graph menu

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [Mikesch-mp/icingaweb2-module-grafana#217]
Hi!

Would be great if I could define own variables that are editable and displayed in the graphs menu beside the timerange selectors. The editable value of the variable should be passed to the iframe URL. Basically the same thing the Grafana web interface has implemented, there you can define variables in the dashboard settings that can be used inside queries.

The variable types could be string (free text), dropdown list (predefined values), range e.g. 

Could look like this:
![image](https://user-images.githubusercontent.com/53210931/63010620-01b4cf80-be87-11e9-8ed0-27bb55f769b6.png)

Selection should be passed like this:

`https://mygrafana/d-solo/000000006/icinga2?var-hostname=xxx&var-service=xxx&var-command=xxx&from=now-5m&to=now&var-myvar=value1`

**Comment by Mikesch-mp** [comment]
Does not make really sense. So many services have different vars or need different vars or dont need any var at all.

**Comment by schuettloeffel-elsa** [comment]
Yes but like the normal custom vars, these special editable vars should be configured per graph, so you can set them for each service individually or dont set them at all.
