### ISSUE TITLE
Feature Request: Collapsible Performance Graph

### ISSUE THREAD

**Issue by IsReal8a** [Mikesch-mp/icingaweb2-module-grafana#218]
## Problem
I have too many network interfaces graphs that can't be displayed on IcingaWEB and it takes a lot of processing power on my laptop :)

## Possible Solution
Add a collapsible icon like the Plugin Output and Performance Data, with some throttling (5 graphs for example per click).
![Screenshot1](https://user-images.githubusercontent.com/2321294/63110204-272b0180-bf8b-11e9-941f-3b5b0e98baf1.png)

Thanks

**Comment by Mikesch-mp** [comment]
Why you dont use a graph with all Interfaces? Inside Grafana you can disable or show metrics only just by clicking on its name.

**Comment by IsReal8a** [comment]
Thanks Mike, that's an option, however the interfaces have different measurements and some devices have 50+ graphs. I can squeeze some if they have the same measurement, but still I may end up with 20+ graphs.
If this is not feasible then please discard it.

**Comment by IsReal8a** [comment]
Found a way to do this that doesn't need this at all, closing this feature request.
