### ISSUE TITLE
Hostalive is not shown

### ISSUE THREAD

**Issue by gitmopp** [Mikesch-mp/icingaweb2-module-grafana#22]
The hostalive graph is not shown because of an invalid query.
I configured my InfluxdbWriter as described here:
[https://docs.icinga.com/icinga2/latest/doc/module/icinga2/chapter/object-types](url)
```
object InfluxdbWriter "influxdb" {
  host = "127.0.0.1"
  port = 8086
  database = "icinga2"
  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "$service.check_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
    }
  }
}
```
Result:

```
> SHOW TAG KEYS FROM "nrpe";
name: nrpe
tagKey
------
hostname
metric
service

> SHOW TAG KEYS FROM "hostalive";
name: hostalive
tagKey
------
hostname
metric
```
=> hostalive does not have a tagKey service.

For a host the module generates the query including "service =~ /^hostalive$/" like
```
SELECT mean("value") FROM /^$/ WHERE "hostname" =~ /^MyHost$/ AND "service" =~ /^hostalive$/ AND "metric" =~ /^$/ AND time > now() - 6h GROUP BY time(15s) fill(none)
```
This works for services like nrpe, but not for hostalive because it has different tagKeys
Correct is
```
SELECT mean("value") FROM /^hostalive$/ WHERE "hostname" =~ /^MyHost$/ AND "metric" =~ /^rta$/ AND time > now() - 6h GROUP BY time(15s) fill(none)
```
The URL has to be changed:
/dashboard/db/icinga2-default?var-hostname=MyHost&var-command=hostalive&var-service&from=now-6h&to=now&orgId=1

I've a fix for it and will open a pull request.

**Comment by Mikesch-mp** [comment]
Did you configure your hostalive graph like any other service graph? Because  host commands a used from the module like any other service, its a trick i had to do.

![image](https://cloud.githubusercontent.com/assets/6574967/24901787/6f982262-1ea8-11e7-9c45-d7b3b27c4bbe.png)

**Comment by gitmopp** [comment]
I didn' t configure any Grafana Graph like in your image. To be honest I didn' t understand how this part of the module works.
If these Grafana Graph templates fix this issue, would it be possible to add a hostalive template as default?
Is it also possible to show warn and crit threshold using this method?

**Comment by Mikesch-mp** [comment]
The mode uses a default graph if no graph is configured. Thats works for mostly all services, except "hostalive", because its a host object. I cant deliver a default graph.ini. because i dont know if the users really use the dashboards i provide :(

And for all other graphs, you dont have to use my dashboards, you can create your  own  and configure them in the module.

If you want i can show it how to configure the graphs in a remote session.

**Comment by gitmopp** [comment]
Now I understand how it works and how to use the base-metrics dashboard. It works fine.
Maybe we can improve the README for this part.
You can reject the pull request.
