### ISSUE TITLE
FeatureRequest: Option to not auto load graphs.

### ISSUE THREAD

**Issue by NeverUsedID** [Mikesch-mp/icingaweb2-module-grafana#222]
As there is always some small delay, because graphs are loading, I would like to see an option to disable auto loading of graphs and add a button "Show Graphs" to only load them,  if you realy want to take a look at them. 

And thanks for your great Plugin, again :)

**Comment by Mikesch-mp** [comment]
Which mode are you using? Try the indirect_proxy mode, graphs then will be lazy loaded and page will displayed immediately

**Comment by NeverUsedID** [comment]
I used proxy. Switched to indirect proxy and that is solving the delay problem. Looks like my Feature Request is not so fancy anymore ;-)
