### ISSUE TITLE
Graph in host overview not working anymore

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [Mikesch-mp/icingaweb2-module-grafana#223]
Lately in my host overview no graph is displayed anymore. My Panel 13 and the Dashboard are working, I already tried changing them, no effect. In service overview, graphs are working fine.

**Graph Config:**
![image](https://user-images.githubusercontent.com/53210931/65020540-a9fa0000-d92d-11e9-9487-116cac26858c.png)

**Host Overview:**
![image](https://user-images.githubusercontent.com/53210931/65020838-3e646280-d92e-11e9-8b94-f8da5379d2c7.png)

## Your Environment
* Icinga Web 2 Grafana version (System - About): 1.3.6
* Icinga Web 2 version and modules (System - About): 2.7.1
* Version used (`icinga2 --version`): r2.10.5-1
* Operating System and version:
* Enabled features (`icinga2 feature list`): api checker command compatlog ido-mysql influxdb mainlog notification statusdata
* Config validation (`icinga2 daemon -C`): no problems

**Comment by Mikesch-mp** [comment]
Hello,

for hosts you have to configure a graph. The default dashboard will not work with host commands.
You will find dashboards for hostalive commands in the dashboard folde, import them and then configure the graph like in the picture.

![grafik](https://user-images.githubusercontent.com/6574967/69143627-b59eaa00-0ac9-11ea-836f-ad5df76c4229.png)


Regards,
Carsten

**Comment by schuettloeffel-elsa** [comment]
Hello Carsten,

thanks for your reply.

After some research i figured out my problem: i had disabled perfdata for the hostalive checks within the icinga2 config. Of course then there was no graph displayed since there was no data to display.. sorry for bothering
