### ISSUE TITLE
Icinga-Default Dashboard is empty, Base-Metrics shows data

### ISSUE THREAD

**Issue by Elfearo** [Mikesch-mp/icingaweb2-module-grafana#226]
Hi there,

i might be completeley wrong, but i am currently doing my first steps with Grafana in an Icinga2 environment. 

## Expected Behavior
Icinga-Default Dashboard should provide data for the icinga2 plugin

## Current Behavior
Icinga-Default Dashboard gets included, but is empty, thus not giving anything to icinga2. I could build my own checks and see that there is data stored in the influxdb and it is successfull parsed from Grafana and made visible. Only the Dashboard inclusion for Icinga to be used is killing me.

When Importing the Dashboard from the repository i am asked for options. I guess thats where i am failing right now. Using Wildcards or Hostnames never gave me a successfull Graph later.

<img width="928" alt="Bildschirmfoto 2019-10-08 um 14 46 07" src="https://user-images.githubusercontent.com/48962034/66397261-b7aa1f00-e9db-11e9-8190-16e86421d9fb.png">

I went through every step in your installation instructions, just struggling what to do with the last point "import dashboards". 

<img width="1831" alt="Bildschirmfoto 2019-10-08 um 14 59 50" src="https://user-images.githubusercontent.com/48962034/66397542-58004380-e9dc-11e9-806c-c69e11fb3a0f.png">

## Your Environment
* Icinga Web 2 Grafana version (System - About): Grafana v6.4.1 (4ba8388)
* Icinga Web 2 version and modules (System - About): 2.7.1 / PHP 7.1.30 
* Operating System and version: Centos 7
* Enabled Features: api checker command ido-mysql influxdb mainlog notification-host-mail notification-service-mail notification perfdata

Thank you for your help

Best wishes
Michael

**Comment by Mikesch-mp** [comment]
Hi,
that dashboard shows only graphs when used with the module in icingaweb2. Inn Grafana it will not work, because the variables are emtpy. if you want to see data you have to add var-hostname,var-service and var-command to your url with the data you want to see.

Or you copy the variable queries from the template dashboard to the default dasshboard, but then dont use this dashboard for icinga, variable queries will slow down the renderer.

Regards,
Carsten

**Comment by irodebush-wes** [comment]
@Elfearo I had an issue when importing the `icinga2-default` dashboard using the json from the repo. I imported the json from `/etc/icingaweb2/enabledModules/grafana/dashboards/influxdb/icinga2-default.json` and the graphs started working just fine.
