### ISSUE TITLE
reduce href to size of image

### ISSUE THREAD

**Issue by maaaax** [Mikesch-mp/icingaweb2-module-grafana#228]
In Version 1.3.6 the graph link is clickable within 100% of the column width.

## Expected Behavior
The link is only clickable inside the graph

## Current Behavior
I can click it outside of the graph

## Possible Solution
Put the Link into a
`<div style="display: inline-block;">`

**Comment by Mikesch-mp** [comment]
Have to test it.

**Comment by sebo1312** [comment]
Changing the Line
https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/e41377b85f7bcff50ed4c9bef3a47767d817f5bd/library/Grafana/ProvidedHook/Grapher.php#L657

to 
`return '<div class="icinga-module module-grafana" style="display: inline-block;">'.$this->title.$menu.$return_html.'</div>';`

works for me as expected
