### ISSUE TITLE
Display more than one graph per service

### ISSUE THREAD

**Issue by xenuser** [Mikesch-mp/icingaweb2-module-grafana#23]
First of all: Thanks for writing this awesome module! I appreciate your work!

There is a request regarding the service graphs:
We display a graph from Grafana when viewing a service within Icingaweb2.
We would not like to have only one graph, but to have multiple graphs per service, all displaying different time frames:
- Last hour
- Last day
- Last week
- Last month (30 days)
- Last year (365 days)

In addition, there is a request for extending this: Instead of displaying all graphs with a full size, we want to have a small thumbnail preview and when mouse-overing them, the full-size graph should be shown.

I patched your module in a customer installation to display 5 graphs for a service, and it works great. Unfortunately loading the service tab is now really slow since my modification makes your module request  5 images from Grafana, which is really slow.

I therefore would like to know what you, the author, thinks about this request and how one could optimize loading times then. One idea would be to make the module more intelligent by e.g. caching images for a configurable interval (or even pre-fetching them, if wanted). Or one could argue if graphs for a long time range (e.g. for the last year) really need to be refreshed every time someone loads the service tab.

**Comment by Mikesch-mp** [comment]
Hi,
even if i would do thumbnails it would be slow in proxy mode. No mater what size you choose, Grafana needs about ~2 seconds or more (depends on timerange)to render an image. With 1.1.0 + you can use direct access to speed up page load, but images will still take some time to be displayed. Also you can switch now in the host/service view the timerange, so there is no more need to display 5 graphs like pnp did.

Regards,
Carsten

**Comment by dnsmichi** [comment]
Adding a sensible global default for the timerange (and adjust that for specific graphs) is a fair and good option imho. I don't think that it makes sense to add multiple graphs with different timeranges next to each other. Once a host or service goes nuts, you normally want to see the last say 3 hours, but not an entire month in a pixel width round about 50px. That's what the URL under the image allows to - jump to the graph and analyze things further.

In terms of thumbnails - maybe Grafana has an option to pre-render multiple timeranges into one image. Might be worthwhile to ask over there, and then add a thumbnail option here (optional).

**Comment by xenuser** [comment]
Thank you both for your feedback.

I noticed that a recent commit extended the Grafana integration by allowing to select a time range. I appreciate this change and I like it.

In terms of displaying multiple graphs at once I would like to state that this covers other requirements.
Normally, when a service triggers alerts or shows strange values and you start investigating, you would not only like to see the last XX minutes or hours, but you would also would like to compare the current graphs to older ones. This is especially helpful for rather unexperienced admins who don't know their service yet in detail. In addition, placing the graphs with older timeframes below the current one helps comparing since all information is at one place.

I agree that in most usecases it would be possible to klick on the image and then continue the investigations within Grafana. However, in some other usecases, only few (or: not all) Icingaweb2 users are allowed to access Grafana, which is why displaying more information within Icingaweb2 is very useful, at least in my eyes.

I would like to know if this changes your view a bit.

Regarding thumbnails: I am not aware of such a prerendering feature.
However, adding more intelligence to the Icingaweb2 module should work IMHO.
But I agree that it can't hurt to ask the Grafana community what they think about providing thumbnails for their renderings.

**Comment by Mikesch-mp** [comment]
You can do it right now already. Just use multiple panels and create a dashboard with 4 panels for the same service/check_command and use fixed timeranges in 3 panels and for example let only the first one controlled by the module.

![image](https://cloud.githubusercontent.com/assets/6574967/25351298/8ba21802-2928-11e7-9da4-7eeb2da14095.png)

**Comment by xenuser** [comment]
Oh, ok. Thanks a lot for this insight. As a matter of fact, I did not think of this variant. Great!
