### ISSUE TITLE
Remove &fullscreen from the Grafana URL

### ISSUE THREAD

**Issue by bunghi** [Mikesch-mp/icingaweb2-module-grafana#230]
Hi,

When I click on a graph inside icingaweb2 it opens a link like this:

http://grafanahost:3000/dashboard/db/icinga2-default?var-hostname=myserver&var-service=myservice&var-command=nrpe&from=now-6h&to=now&orgId=1&panelId=1&fullscreen

How can I remove "&fullscreen" from the URL so by default I can see all the performance labels and not only one?

I'm using module version 1.3.5

Thanks

**Comment by Mikesch-mp** [comment]
The module links to the panel it shows in icingaweb2 and not to the dashboard the panel is in.
If you want to change it, search the source code and remove it for you, i will not change it.

Regards,
Carsten

**Comment by bunghi** [comment]
Thanks @Mikesch-mp ;)
