### ISSUE TITLE
allow to set relative path in publichost

### ISSUE THREAD

**Issue by sebo1312** [Mikesch-mp/icingaweb2-module-grafana#231]
## Expected Behavior
Allow to set a relative path in variable publichost

## Current Behavior
Have a reverse proxy running in front of my icinga server in order to operate under different domain names. Grafana is also configured to run under different FQDNs. The graphs (preview) integrated in the icingaweb2-UI will be shown correctly under each URL. The only issue I got is the link, pointing to grafana (when clicking the graph)  - it cannot be set relatively.

setting the following parameter
publichost = "/grafana"
publicprotocol = ""

Result in an URL like this:
https://host.domain.foo/icingaweb2/:///grafana/dashboard[...]

## Possible Solution
As a workaround I set the parameter as follows:
publichost = "../../../grafana"
publicprotocol = ""

Resulting URL will look like - Works!
https://host.domain.foo/grafana/dashboard[...]

The workaround is not very intuitive and should be replaced by a simpler solution.

## Your Environment
* Icinga Web 2 Grafana version (System - About): 1.1.10
* Icinga Web 2 version and modules (System - About): 2.7.3
Version used (`icinga2 --version`): 2.11.2-1
* Operating System and version: CentOS 7

**Comment by Mikesch-mp** [comment]
Public host is some other host then the one that grafana uses. Why you dont just enter the full host details, its not that complicated. Maybe i will add a check if details are entered correct or not to prevent this in the future

**Comment by sebo1312** [comment]
> Public host is some other host then the one that grafana uses. Why you dont just enter the full host details, its not that complicated. Maybe i will add a check if details are entered correct or not to prevent this in the future

That's not possible if you do have more than one hostnames for one server.
