### ISSUE TITLE
icinga2-influx-grafana  Users would not populate in grafana (syntax issue)

### ISSUE THREAD

**Issue by fireheadman** [Mikesch-mp/icingaweb2-module-grafana#232]
Was using the base-metrics.json from your site and could not get the Users metrics to show in grafana...   It kept saying No Data.

After reviewing the json and querying influx, I noticed a syntax error in the json file... Once I corrected this the graphs started working for "Users"

This is a snippet from the base-metrics.json showing the lowercase "users", which should be "Users"

![image](https://user-images.githubusercontent.com/19847195/69123126-cc0f1c00-0a5d-11ea-8342-224e599a9954.png)

...and from querying influx, you can see why this is a typo:

```
> show series on icinga2 from "users"
key
---
users,hostname=client1,metric=users,service=Users
users,hostname=client1,service=Users
users,hostname=client2,metric=users,service=Users
users,hostname=client2,service=Users
```

I'm now curious if there is an updated version of this file I can re-import?

**Comment by Mikesch-mp** [comment]
You named your service in icinga `Users`, when creating that dashboard i named the service  `users`.
So its up to you to change it (what you did) or change your service name :)

Regards, 
Carsten

**Comment by fireheadman** [comment]
This is odd.... other services like swap, load, ntp, ping are all in upper case and still work fine (without modifying the json).

BTW:   Is there a way to know which services are built into the base-metric.json file?
