### ISSUE TITLE
values in billion for memory and disk checks.

### ISSUE THREAD

**Issue by Axel577** [Mikesch-mp/icingaweb2-module-grafana#235]
Hi Carsten!
I got a new installation of icinga2, icingaweb2, grafana and your plugin:
icinga2: 2.11
icingaweb2: 2.7.3
grafana: 6.5.2
icingaweb2-module-grafana: 1.3.6

Your plugin is working but I noticed that disk, memory, network checks etc, use the short values. There is no calculation like in megabyte for example.
So the memory graph looks like that:
![image](https://user-images.githubusercontent.com/28043745/71004824-c94a2a00-20e2-11ea-9225-62a046e0d078.png)
I tried to change that value in the icinga2-default panel from short to megabyte, but then all graphs have that calculation to megabyte.
There are checks where the short value is perfect, for example the cpu check:
![image](https://user-images.githubusercontent.com/28043745/71004944-04e4f400-20e3-11ea-8d99-ae30dc54e12b.png)
In grafana, I got a lot of dashboards with custom panels and custom values. My question is if it's possible to reference every single service check to a grafana dashboard and panel. And not referencing it to the default-icinga2 dashboard.
I hope you understand what I'm trying to say.
Thank you!

**Comment by Mikesch-mp** [comment]
You can reference to whatever dashboard panel you want. You just need to configure it. Best Practise is to use command name for it, works for the most plugins.

**Comment by Axel577** [comment]
Can you tell me where I need to configure this? So for example I would like to reference a memory check of a host to a specific panel of a specific dashboard. Is that possible?

**Comment by Mikesch-mp** [comment]
Its all in the [docs](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md) ;)

**Comment by grant-veepshosting** [comment]
I have read the docs 3x and still can't figure out how to pass in sensible "default units" so the Grafana graphs don't display in Billions, per the above. Is someone sufficiently knowledgeable able to provide a "how to" with steps please? This affects the human readability of most disk, swap and memory metrics.

**Comment by Mikesch-mp** [comment]
1. Create a dashboard with a panel in Grafana for the service/command ....
2. Configure this dashboard/panel for the service/command inside the graph configuration of the module

Really simple

**Comment by grant-veepshosting** [comment]
Thanks, got it working.

**Comment by grant-veepshosting** [comment]
I must still be missing something here - I have built the dashboard in Grafana and tested it against 2-3 servers successfully within Grafana. When changing the <actual server name> to the template variable /^$hostname$/ and trying to view in Icingaweb2 (or copying the debug URL to browser) results in "no data".

**Comment by grant-veepshosting** [comment]
I have now resolved the above.
Option 1: Edit the "base metrics" dashboard and add an additional panel (it already has the correct variables setup).

or

Option 2: Add the variables to the Dashboard (not in the Panel config I had been looking though).

![Screen Shot 2020-01-17 at 1 25 42 pm](https://user-images.githubusercontent.com/43027184/72579417-2416b180-392d-11ea-94b1-a5d1aff63ba2.png)
