### ISSUE TITLE
Service name match for Grafana graphs

### ISSUE THREAD

**Issue by bunghi** [Mikesch-mp/icingaweb2-module-grafana#242]
Hi,

This is not a real issue but a question. 

I have several services for Windows hosts to monitor the disk space, one service per drive:

WIN_Disk_Space_C
WIN_Disk_Space_D
WIN_Disk_Space_E
WIN_Disk_Space_F
...

They all use **nrpe** check command with **disk_check** as nrpe command, only difference is the nrpe arguments (drive letter, warning threshold, critical threshold).

Is there any way to create one Grafana graph to match all WIN_Disk_Space_* services?

Versions installed:
IcingaWeb 2.7.3
Grafana Module 1.3.5

Thanks

**Comment by Mikesch-mp** [comment]
Yes you can go by command name or by servicename if you would name your service like `WIN_DISK_Space A`

**Comment by bunghi** [comment]
I can't go by command because there are hundreds of services with **nrpe** command, and I don't want to create one graph per each **WIN_Disk_Space_X** service.. With one graph I want to match all services matching name **WIN_Disk_Space** ...

**Comment by Mikesch-mp** [comment]
You can also add a variable to your services which is read by the module and uses the name in it to choose the graph configuration to use for that service. see https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/03-module-configuration.md#custvarconfig

**Comment by bunghi** [comment]
Thanks @Mikesch-mp , it works exactly the way I need it! Regards from me and Alex ;)
