### ISSUE TITLE
Graph displaying wrong time 

### ISSUE THREAD

**Issue by leonmarquez** [Mikesch-mp/icingaweb2-module-grafana#244]
Describe the bug
The grafana graph is not displaying the correct time. The values in the graph are matching as if the time was right. If i click on the graph and open it in Grafana it displays the correct values.
Icingaweb2 detects the right browser timer: Europe/Paris

Expected behavior
The graph should display the correct time matching the values above.

Screenshots
![image](https://user-images.githubusercontent.com/16097307/78263234-f855a180-7501-11ea-913e-9ef7e21d87fc.png)

Current time in the Image: 16:50 / 4:50pm

Your Environment
Include as many relevant details about the environment you experienced the problem in

Icinga Web 2 version and modules (System - About): 2.6.2 and module 1.3.5
Web browser used: Chrome, Firefox, Edge
Icinga 2 version used (icinga2 --version): r2.10.2-1
PHP version used (php --version): PHP 7.0.33-0+deb9u6
Server operating system and version: Debian GNU/Linux 9

**Comment by Mikesch-mp** [comment]
Hi, 
i bet your server runs on a different time zone settings. The Grafana image renderer uses only the server settings.

Regards,
Carsten

**Comment by leonmarquez** [comment]
Hi,
the server time is the same as the local time:
![image](https://user-images.githubusercontent.com/16097307/78331185-d140b380-7585-11ea-864f-d72ec19fb250.png)

**Comment by Mikesch-mp** [comment]
Which renderer do you use, the old java one, the chromium plugin or the docker container?

**Comment by leonmarquez** [comment]
I switched to the chromium plugin a few moths ago.

**Comment by leonmarquez** [comment]
If i open the direct image renderer from grafana the time is being displayed correctly:
![image](https://user-images.githubusercontent.com/16097307/78352281-65237700-75a8-11ea-9e38-7d3675501639.png)
The image in icingaweb2 is 2 hours behind:
![image](https://user-images.githubusercontent.com/16097307/78352347-7cfafb00-75a8-11ea-8005-d84ad1991c9b.png)

**Comment by Mikesch-mp** [comment]
Has Grafana any settings for timezone set? I think the default is to use browser time

**Comment by leonmarquez** [comment]
Yes. It's set to local browser time

**Comment by Mikesch-mp** [comment]
Strange, it works perfect for me and yours looks like it uses UTC for the renderer.

**Comment by mdicss** [comment]
Any news here? We see the same problem. The data in the graph is correct, but the times on the axis are UTC instead of UTC+1.

**Comment by mdicss** [comment]
Hi
We found the cause for the wrong displayed time. The grafana modul gets the grafana graphs rendered by the renderer. So the timezone in grafana and in icinga can be set correctly but you can have a different timezone - most likely UTC - for the renderer. We use a kubernetes pod with the renderer and had to set the timezone there instead of using the default. See also:
https://grafana.com/docs/grafana/latest/image-rendering/  -> Default Timezone
