### ISSUE TITLE
INFO: grafana 7.0.0 compat

### ISSUE THREAD

**Issue by BarbUk** [Mikesch-mp/icingaweb2-module-grafana#248]
The new release of grafana come with a breaking change.
The render plugin using phantomjs is not available anymore, a new render plugin must be installed.

There is a blogpost explaining the change: https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/

After upgrading to grafana 7.0.0, grafana display a message explaining you have to install the new renderer plugin.
![image](https://user-images.githubusercontent.com/64371/82291690-c1502800-99a9-11ea-9640-936299dc1fec.png)

## Installing the plugin

```
grafana-cli plugins install grafana-image-renderer
service grafana-server restart
```

## Fixing 500 error

After installing the plugin, icinga display a 500 error instead of the graph.
Testing directly in grafana produce:
![image](https://user-images.githubusercontent.com/64371/82291981-3facca00-99aa-11ea-8439-21eac97d2cfc.png)

`/var/log/grafana/grafana.log` give more information:

```
t=2020-05-19T08:09:12+0200 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=julien error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
```

Testing the provided chrome binary for missing libs:
```
# ldd /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome | grep not
	libnss3.so => not found
	libnssutil3.so => not found
	libsmime3.so => not found
	libnspr4.so => not found
	libXss.so.1 => not found
```

Installing the missing libs via `apt-get` fix the issue:
```
apt-get install libnss3 libxss1
```

## Your Environment
* Icinga Web 2 Grafana version (System - About): 2.7.3
* Icinga Web 2 version and modules (System - About): 

Name | Version
-- | --
grafana | 1.3.6
ipl | v0.1.1
monitoring | 2.7.3

* Version used (`icinga2 --version`): r2.11.3-1
* Operating System and version:
System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-9-amd64
  Architecture: x86_64

* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb mainlog notification

**Comment by ggzengel** [comment]
Waste of space! WTF?

@BarbUk  First, thanks for your info. So I had less to search for a solution.

You have a little typo:
```
- grafana-cli plugins uninstall grafana-image-renderer
+ grafana-cli plugins install grafana-image-renderer
```

I had some more missing packages:
```
apt install libxcursor libxcursor1 libasound2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 libgtk-3-0 
```

And this is what I got:
```
Start-Date: 2020-05-19  18:22:34
Commandline: apt install libxcursor1
Install: libxcursor1:amd64 (1:1.1.15-2)
End-Date: 2020-05-19  18:22:54

Start-Date: 2020-05-19  18:23:43
Commandline: apt install libasound2
Install: libasound2-data:amd64 (1.1.8-1, automatic), libasound2:amd64 (1.1.8-1)
End-Date: 2020-05-19  18:23:45

Start-Date: 2020-05-19  18:24:42
Commandline: apt install libatk1.0-0
Install: libatk1.0-0:amd64 (2.30.0-2), libatk1.0-data:amd64 (2.30.0-2, automatic)
End-Date: 2020-05-19  18:25:01

Start-Date: 2020-05-19  18:26:10
Commandline: apt install libatk-bridge2.0-0
Install: at-spi2-core:amd64 (2.30.0-7, automatic), libatspi2.0-0:amd64 (2.30.0-7, automatic), libatk-bridge2.0-0:amd64 (2.30.0-5)
End-Date: 2020-05-19  18:26:11

Start-Date: 2020-05-19  18:27:30
Commandline: apt install libpangocairo-1.0-0
Install: libpangoft2-1.0-0:amd64 (1.42.4-8~deb10u1, automatic), libpixman-1-0:amd64 (0.36.0-1, automatic), libthai-data:amd64 (0.1.28-2, automatic), libxcb-shm0:amd64 (1.13.1-2, automatic), libxcb-render0:amd64 (1.13.1-2, automatic), fontconfig:amd64 (2.13.1-2, automatic), libpangocairo-1.0-0:amd64 (1.42.4-8~deb10u1), libthai0:amd64 (0.1.28-2, automatic), libgraphite2-3:amd64 (1.3.13-7, automatic), libharfbuzz0b:amd64 (2.3.1-1, automatic), libcairo2:amd64 (1.16.0-4, automatic), libpango-1.0-0:amd64 (1.42.4-8~deb10u1, automatic), libfribidi0:amd64 (1.0.5-3.1+deb10u1, automatic), libdatrie1:amd64 (0.2.12-2, automatic)
End-Date: 2020-05-19  18:27:57

Start-Date: 2020-05-19  18:28:38
Commandline: apt install libgtk-3-0
Install: libjson-glib-1.0-0:amd64 (1.4.4-2, automatic), libsoup-gnome2.4-1:amd64 (2.64.2-2, automatic), libcroco3:amd64 (0.6.12-3, automatic), glib-networking-services:amd64 (2.58.0-2, automatic), libwayland-egl1:amd64 (1.16.0-1, automatic), libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1, automatic), libproxy1v5:amd64 (0.4.15-5, automatic), dconf-service:amd64 (0.30.1-2, automatic), libcairo-gobject2:amd64 (1.16.0-4, automatic), glib-networking:amd64 (2.58.0-2, automatic), libgtk-3-common:amd64 (3.24.5-1, automatic), libgtk-3-0:amd64 (3.24.5-1), librsvg2-common:amd64 (2.44.10-2.1, automatic), dconf-gsettings-backend:amd64 (0.30.1-2, automatic), libepoxy0:amd64 (1.5.3-0.1, automatic), gsettings-desktop-schemas:amd64 (3.28.1-1, automatic), xkb-data:amd64 (2.26-2, automatic), glib-networking-common:amd64 (2.58.0-2, automatic), libsoup2.4-1:amd64 (2.64.2-2, automatic), libwayland-client0:amd64 (1.16.0-1, automatic), adwaita-icon-theme:amd64 (3.30.1-1, automatic), libgtk-3-bin:amd64 (3.24.5-1, automatic), librsvg2-2:amd64 (2.44.10-2.1, automatic), libjson-glib-1.0-common:amd64 (1.4.4-2, automatic), libcolord2:amd64 (1.4.3-4, automatic), libgdk-pixbuf2.0-bin:amd64 (2.38.1+dfsg-1, automatic), hicolor-icon-theme:amd64 (0.17-2, automatic), libgdk-pixbuf2.0-common:amd64 (2.38.1+dfsg-1, automatic), librest-0.7-0:amd64 (0.8.1-1, automatic), gtk-update-icon-cache:amd64 (3.24.5-1, automatic), dbus-user-session:amd64 (1.12.16-1, automatic), libxkbcommon0:amd64 (0.8.2-1, automatic), libdconf1:amd64 (0.30.1-2, automatic), libwayland-cursor0:amd64 (1.16.0-1, automatic)
End-Date: 2020-05-19  18:29:30
```

```
# lsb_release -d
Description:	Debian GNU/Linux 10 (buster)
```

**Comment by BarbUk** [comment]
> You have a little typo:

Fixed, thanks

**Comment by MarcusCaepio** [comment]
Thanks guys for reporting this!

**Comment by tracestats** [comment]
Thanks guys!

**Comment by GalipoliX** [comment]
Thanks guys!
Had to also innstall libx11-xcb-dev package.
Ubuntu 18.04.

`apt install libx11-xcb-dev`

**Comment by bunghi** [comment]
It is not working to me after installing the plugin and the packages. This is how it look like:
![image](https://user-images.githubusercontent.com/31234197/83615524-59940280-a58f-11ea-8d22-24b97e488039.png)

**Comment by bunghi** [comment]
Nevermind, Thanks to the [troubleshoot ](https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshooting)link I figured out that some libraries were missing:

$:/var/lib/grafana/plugins/grafana-image-renderer# ldd chrome-linux/chrome | grep found
        libnss3.so => not found
        libnssutil3.so => not found
        libsmime3.so => not found
        libnspr4.so => not found
        libXss.so.1 => not found
$ apt-get install libnss3 libxss1

**Comment by daks** [comment]
Thanks a lot for information on this issue ! :)

I needed to install `libxdamage1 libxi6 libxtst6 libcups2 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libxcursor1 libnss3 libxss1 libx11-xcb1 libxcomposite1` on Debian 9... too much desktop packages on my servers now.
I hate to see something like `gtk-update-icon-cache` or `adwaita-icon-theme` on those.

**Comment by Mikesch-mp** [comment]
This has nothign to to with the module -> close

**Comment by MarcusCaepio** [comment]
But it would be nice, to have a hint in the docs :)

**Comment by Mikesch-mp** [comment]
Why, the modules uses Grafana only, so its up to the user to install Grafana correctly and the hint is in the Grafana docs. IF users upgrade there apps without reading the upgrade docs, i cant help them.

**Comment by BarbUk** [comment]
The intent for this issue was to help people with a broken icinga/grafana integration understand the problem following grafana 7 release.

It was the first place I looked for help, and though it would help people identify the issue quickly.

IMO, now that the grafana 7 release is 30 days old, the issue visibility is less important and the issue can stay closed.

**Comment by MarcusCaepio** [comment]
For all of you switching to 7, this could be interesting. I just rolled back to 6.8
https://github.com/grafana/grafana-image-renderer/issues/124

**Comment by Aleksey-Maksimov** [comment]
For Debian GNU/Linux 12 "Bookworm":


`# apt-get install libnss3 libxss1 libatk1.0-0 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2
`
