### ISSUE TITLE
Grafana Panel URL changed

### ISSUE THREAD

**Issue by mitch-geht-ab** [Mikesch-mp/icingaweb2-module-grafana#249]
Hello everybody,

after upgrading Graphana (6.7.2 >> 7.0.1) on my Deb10 system I noticed that the variable for the panelID selection changed from former:

https://\<system\>/grafana/d/1YrWroWZk/icinga2?var-hostname=xxxxxx&var-service=yyyy&var-command=snmp-netinterface&from=now-6h&to=now&orgId=1&**panelId=5**&fullscreen

to:

https://\<system\>/grafana/d/1YrWroWZk/icinga2?var-hostname=xxxxxx&var-service=yyyy&var-command=snmp-netinterface&from=now-6h&to=now&orgId=1&**viewPanel=5**&fullscreen

The problem is, icingaweb2 is linking to the panelid variable in the embedded picture of the graph. To view the graph you have to change panelid=<id> to viewpanel=<id>.

Debian 10.4
grafana                               7.0.1
icinga2-bin                           2.11.3-1.buster
icingaweb2                            2.7.3-1.buster

BR
mitch

**Comment by bunghi** [comment]
It is not working to me.. This is how I see the graph in icingaweb2 after upgrade:

![image](https://user-images.githubusercontent.com/31234197/83619830-1472cf00-a595-11ea-835d-1550b42a2b60.png)

**Comment by Mikesch-mp** [comment]
I updated my installation of Grafana to 7.0.3 and i dont have this problem. Does this happen if you set more then one graph for a service?

**Comment by mitch-geht-ab** [comment]
Hi,
no, it's only one graph for the service. Here is a screenshot story:

IcingaWeb2 Screen for ping service:
![screen1](https://user-images.githubusercontent.com/8008251/84589692-9504bb80-ae30-11ea-9d72-476cf31fa49d.jpg)

with the Link for grafana:
![screen2](https://user-images.githubusercontent.com/8008251/84589626-33dce800-ae30-11ea-90cd-be86467ca568.jpg)

when I click the link, I see all graphs in the dashboard:
![screen3](https://user-images.githubusercontent.com/8008251/84589660-65ee4a00-ae30-11ea-94d7-73f7f4d037a4.jpg)

... but it should only be one, the graph/panel for the ping command.
It should look like this, after I changed panelid= to viewpanel= by hand:
![screen4](https://user-images.githubusercontent.com/8008251/84589672-7ef6fb00-ae30-11ea-8175-543af943f9af.jpg)

**Comment by Mikesch-mp** [comment]
Ahh now i got it, will check that soon(tm)

**Comment by abaumgaertner** [comment]
since PhaontomJS was discontinued in 2018 and removed from Grafana 7 - see:
https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/
is this issue related to the new rendering plugin?
