### ISSUE TITLE
InfluxDB Error: query-timeout limit exceeded pop-up 

### ISSUE THREAD

**Issue by bunghi** [Mikesch-mp/icingaweb2-module-grafana#250]
Hi,

Since upgraded to Grafana 7 from time to time I get this timeout error on the grafana panel in IcingaWeb2, and there is no way to close the red pop-up message with the 'x', it just redirects to grafana server:

![image](https://user-images.githubusercontent.com/31234197/85104436-46309a80-b211-11ea-80d3-bb37b02b80e0.png)

1. Is there any way to avoid this pop-up?
2. How can I change the timeout setting?

Thanks

**Comment by Mikesch-mp** [comment]
Hello,

this is a setting from your influxdb. Normaly you can find them in /etc/influxdb/influxdb.ini.
Hint: Your influxDB server needs more ram :)

Regards,
Carsten
