### ISSUE TITLE
Update Grafana 6.6.2 -> 7.0.4 = Rendering failed

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Mikesch-mp/icingaweb2-module-grafana#251]
Hello, Carsten

I just updated the package **Grafana** from **6.6.2** to **7.0.4** and got a problem.

First, I saw a message in the Icinga Web web interface

> No image renderer available/installed. For Grafana to be able to generate an image you need to install the Grafana Image Renderer plugin

I found a document https://grafana.com/grafana/plugins/grafana-image-renderer and followed his recommendations:

```
# grafana-cli plugins install grafana-image-renderer
installing grafana-image-renderer @ 2.0.0
from: https://grafana.com/api/plugins/grafana-image-renderer/versions/2.0.0/download
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully

Restart grafana after installing plugins . <service grafana-server restart>

# service grafana-server restart
```

Now, instead of a graph, a link is displayed in the Icinga Web interface. 

![изображение](https://user-images.githubusercontent.com/17614847/86001902-42262900-ba18-11ea-9b95-064f989b30a9.png)

If I follow the link, then in Grafana the data is displayed.

![изображение](https://user-images.githubusercontent.com/17614847/86002000-61bd5180-ba18-11ea-87ce-1cbe4a0b8d1a.png)

Debian 9.12
grafana 7.0.4
icinga2    2.11.4-1.stretch
icingaweb2 2.8.1-1.stretch

How can we solve this problem?

**Comment by Mikesch-mp** [comment]
Please read the [image renderer docs](https://grafana.com/docs/grafana/latest/administration/image_rendering/) and install also the requirements for chromium.

**Comment by Aleksey-Maksimov** [comment]
Yes thank you. Already figured out this problem. I want to note that the new renderer in Grafana began to work significantly slower. I see that now it takes 3 times more time to render. And this is very sad.
