### ISSUE TITLE
Grafana InfluxDB selecting disks and services do not display correctly

### ISSUE THREAD

**Issue by HipDragon** [Mikesch-mp/icingaweb2-module-grafana#252]
## Description
After importing the InfluxDB base metrics I noticed that the disk panel doesn't update the graph when changing the disk variable correctly when selecting a disk. The disk panel also seems linked to the service variable, which also doesn't seem show any other services when you change the service window.

The problem seems to be with the query, adding 
`{
    "condition": "AND",
    "key": "metric",
    "operator": "=~",
    "value": "/^$disk$/"
}`
to the three disk queries seems to correct the disk display. It does not solve the service selection issue.

The service selection seems to be the queries only look at the disk in the from and it's never the service that is selected.

## Environment
* Icinga Web 2 Grafana version: 1.3.6
* Icinga Web 2 version and modules: 2.8.1
* Grafana version: Grafana v7.0.5
* Operating System and version: Red Hat Enterprise 8

**Comment by Mikesch-mp** [comment]
Base metrics is only a tech demo and should not used with the module
