### ISSUE TITLE
grafana image render plugin points to localhost when clicked

### ISSUE THREAD

**Issue by fireheadman** [Mikesch-mp/icingaweb2-module-grafana#253]
## Expected Behavior

Grafana now requires the image render plugin to be installed in order to see the graphs in icinga
Once this is completed, the graphs work, however if you click the graph, it will launch the grafana window and point to localhost host instead of the IPAddress of the icinga server.

This is causing a page not found condition.
If you replace localhost with the IPAddress in the link (new window), then it works.
Unsure what needs to be changed in the module to allow for the spawned window to launch with IPAdress or if there is a setting I can change on my side for this?

## Steps to Reproduce (for bugs)

1. navigate to client (ping graph or any service graph)
![image](https://user-images.githubusercontent.com/19847195/88835481-8e3cc880-d192-11ea-8178-683b61ca5507.png)

2. can also right click and copy link
![image](https://user-images.githubusercontent.com/19847195/88835543-a1e82f00-d192-11ea-8ae5-bf5f8ee1cb3e.png)
 This will get you [http://x.x.x.x:3000/d/xxxxxxx/base-metrics?var-hostname=xxxxxxxx&var-service=hostalive&var-command=hostalive&from=now-6h&to=now&orgId=1&panelId=9&fullscreen](http://x.x.x.x:3000/d/xxxxxxx/base-metrics?var-hostname=xxxxxxxx&var-service=hostalive&var-command=hostalive&from=now-6h&to=now&orgId=1&panelId=9&fullscreen)

seems good at this point
3. but it somehow get translated to this
[(http://localhost:3000/d/xxxxxxxx/base-metrics?from=now-6h&orgId=1&to=now&var-command=hostalive&var-hostname=clarorat05&var-service=hostalive&viewPanel=9)](http://localhost:3000/d/xxxxxxxx/base-metrics?from=now-6h&orgId=1&to=now&var-command=hostalive&var-hostname=clarorat05&var-service=hostalive&viewPanel=9)

and now it doesn't work....
4.  so if you substitute localhost for the IPAddress, then it works and I can see the data.

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.5
* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):  2.11.3-1
* Operating System and version:  rhel 7.8
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by R-Sommer** [comment]
You simply need to go **Configuration -> Modules -> grafana -> Configuration** and change the entry for **host** from `localhost:3000` to `x.x.x.x:3000`.

**Comment by irodebush-wes** [comment]
Uncomment and change the `domain` under the "Server" section in `/etc/grafana/grafana.ini` to your hostname or IP. The default config will redirect the link requests to `localhost:3000`.

**Comment by fireheadman** [comment]
@irodebush-wes    ====>>>> This is the solution!
I'm back online, thanks!
