### ISSUE TITLE
displaying apply button

### ISSUE THREAD

**Issue by willemdw** [Mikesch-mp/icingaweb2-module-grafana#259]
after upgrading, following error occured (see attachment)

![grafana](https://user-images.githubusercontent.com/61312377/105201547-4eeba500-5b41-11eb-9096-143e78b0f8ac.JPG)

## Your Environment

* Icinga Web 2 Grafana version (System - About): 7.3.7
* Icinga Web 2 version and modules (System - About): 2.8.2
* php version : 7.0.7
* Version used (`icinga2 --version`): 2.12.3
* Operating System and version: sles 12.5
* grafana module : 1.3.6
*  Enabled features (`icinga2 feature list`): 
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
This option will be removed
