### ISSUE TITLE
Custome hostname variable

### ISSUE THREAD

**Issue by Viv1986** [Mikesch-mp/icingaweb2-module-grafana#260]
Can't get working for host.name var in customes vars under graphs, 
I need to set different graphs per host, and trying to use 
&var-Environment=$host.name$ 
I tryed several options, like $host$ $host_name$  etc nothing work, but
&var-Environment=dev works, and I will have 1 graph per all hosts, what I should do?

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.3.6
* Icinga Web 2 version and modules (System - About): 2.6.3
* Version used (`icinga2 --version`): r2.10.5-1
* Operating System and version: Ubuntu 18.04
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
Read the docs
