### ISSUE TITLE
GRAFANA-ICINGA Graph is not loading

### ISSUE THREAD

**Issue by kaurav1108** [Mikesch-mp/icingaweb2-module-grafana#262]
Hi, 
I have configured ICINGA with Grafana module with influx db.
All configuration is done. in Grafana Web GUI i am able to see the graph but in ICINGA web GUI graph is not loading,can you please help the same.
GRAFANA Screenshot : 
![image](https://user-images.githubusercontent.com/71206196/111665219-d76d8580-8812-11eb-9b61-81a5c2b98244.png)
ICINGA2 screenshot:
![image](https://user-images.githubusercontent.com/71206196/111665376-fe2bbc00-8812-11eb-9dbc-4d1c9059bac1.png)
 Error  : http’s server IP address could not be found.

**Comment by bryanalfarom** [comment]
Hi 
I had the same problem, my config in icinga, i set grafana access as iframe, and get the same error.
I fixed adding the next line in apache config

####################################
Header set X-Frame-Options: "SAMEORIGIN" 
####################################

i use centos and i added on this file /etc/httpd/conf/httpd.conf on debian/ubuntu i think is /etc/apache2/conf-enabled/security.conf (i added at the end, before IncludeOptional line)

Maybe this link help you about options has X-Frame
https://developer.mozilla.org/es/docs/Web/HTTP/Headers/X-Frame-Options

I hope this help you

**Comment by Mikesch-mp** [comment]
Check your Grafana options, you have to allow it now. see https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_embedding
