### ISSUE TITLE
always connection to https://localhost:3000 instead of configured Hostname

### ISSUE THREAD

**Issue by terrik15** [Mikesch-mp/icingaweb2-module-grafana#265]
Hi,

I have the following problem, if I use https as the protocol, the connection to the grafana does not work because https://localhost:3000 is called again and again, but the certificate runs on the FQDN and not for the name localhost. If I change it to http then everything works fine in icinga and the external link

As a workaround, I put a reverse proxy in front of grafana, but if I specify https for the public protocol, this is ignored and the public host continues to try to address it with http instead of https. If I enter https to the new browser tab for the external link, it works fine.

Could it be that Public Protocol is being ignored? Or back to the actual problem: what is the reason that when https is activated in the host, access to https://localhost:3000 is always carried out, even if the FQDN is entered.

**Comment by Bierchermuesli** [comment]
Not sure if I had the sam issue.  (atleast 1.35?). 
If you copy the link text, paste it in the browser bar: the same!
edit just the host within the browser: Works - very strange.

But if you look close, there might be an  `&fullscreen` param at the end. which causes this redirect.

I had a local docker grafana running, and tought this was just my borwser (Brave) with kind of cache redirects.

**Comment by Mikesch-mp** [comment]
Check you grafana configuration (/etc/grafana/grafana.ini). This is not a module problem!
