### ISSUE TITLE
Dashboard UID  missing

### ISSUE THREAD

**Issue by gbin2265** [Mikesch-mp/icingaweb2-module-grafana#267]
Hello, 

I have installed the new module 14.1 and if I want to make a new graph there is no field left to enter my Dashboard UID *.

These are the fields i see :
Name *
Dashboard name *
PanelId(s) *
OrganizationId
Custom Variables
Timerange
Graph height
Graph width
Repeating Panel
Metrics per panel

There are the basic parameters:
Grafana access *  Indirect Proxy
Proxy Timeout 5 
Authentication type  Anonymous
Refresh on indirect proxy  Yes

have you heard about this problem  or am I doing something wrong??

regards,
Geert

Icinga Web 2  2.8.2
Git Commit    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version   7.3.20
MODULE      VERSION
grafana     1.4.1
map         1.1.0
monitoring  2.8.2

**Comment by gbin2265** [comment]
Hello,

I found the problem why the uid is not there and because of which I also had other problems. 
(did not find certain graphics on grafana, curl error).
He started searching for grafana on the basis of the name and not the uid.

I saw that the parameter 'version = 1' was disappeared from the file /etc/icingaweb2/modules/grafana/config.ini 
I added these manually and everything worked again.

But when I do an update of the configuration of the module via the GUI , then the line 'version' has disappeared again !!!!

The version 1.3.4 write always "version = 1" in the config file when I update de module config via the GUI.

regards,
Geert

**Comment by zorg-the-blue** [comment]
@gbin2265  - You rock!  I had the same issue with a new installation and was bumbling my way around wondering if it was my noob self with configuration and not knowing how this is supposed to work, but it does look like a bug. I manually entered the version line into the INI file and the missing DBUID showed back up in the graph UI screen. 

I'd been wondering why it wasn't there and how the URL was built if we didn't specify it on the per-graph configuration.
