### ISSUE TITLE
Graph images not loaded over configured protocol

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [Mikesch-mp/icingaweb2-module-grafana#270]
The graph images are not using the same protocol as the configured protocol

![image](https://user-images.githubusercontent.com/22965146/122235827-033ced80-ce8c-11eb-842e-cb18b4d947d4.png)

It is loading the image of https even though I have http configured.
The image link does respect the configured protocol

## Expected Behavior
the png images should be loaded over the configured protocol

## Current Behavior
the images are loaded over a different protocol than configured.

## Steps to Reproduce (for bugs)

1. configure http as the protocol for the grafana plugin. 
2. open service page
3. look in browser debug output, the png image is loaded over https regardless of configuration
4.

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.8.2
* Version used (`icinga2 --version`):  r2.12.4-1
* Operating System and version: ubuntu 20.04
* Enabled features (`icinga2 feature list`): api checker ido-mysql influxdb mainlog
* Config validation (`icinga2 daemon -C`): [2021-06-16 10:23:37 -0400] information/cli: Finished validating the configuration file(s).

**Comment by Mikesch-mp** [comment]
The images are loaded over the configured protocol, what you see is the indirect proxy url which is still a part of icingaweb2
