### ISSUE TITLE
graphs not working behind loadbalancer

### ISSUE THREAD

**Issue by fl0wx** [Mikesch-mp/icingaweb2-module-grafana#279]
## Expected Behavior
The graphs schould be shown
## Current Behavior
if i access the icingaweb2 host directly the graph is loaded as expected. If i try to access the icingaweb2 host not directly, but with a loadbalancer, then the graphs arent shown.

Reason could be the "getBaseUrl" function.

this codefragment generates always a baseurl with the icingaweb2 host, not the balancerhost:
https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/2cae443a51f964f01f83b59c5d206bba08bd944d/library/Grafana/ProvidedHook/Grapher.php#L219

I havent found any configuration property to change that behavior.

here is the function which is called by the grafana module: https://github.com/Icinga/icingaweb2/blob/b75cf362b8f3a64a028fd88c7cf8b40cfddb4c84/library/Icinga/Web/Url.php#L196

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Version used (`icinga2 --version`): 2.11.3
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by Littlericket** [comment]
Same here. The module does not take in account that X-Forwarded-Host and X-Forwarded-Proto can be defined.

**Comment by fl0wx** [comment]
was an issue with balancer config
