### ISSUE TITLE
indirect proxy behind reverse proxy - curl get schema.

### ISSUE THREAD

**Issue by mooneym17** [Mikesch-mp/icingaweb2-module-grafana#285]
I am testing running icingaweb2 within a container behind a reverse proxy. Currently the iciingaweb2 containier is http - https is terminated on the reverse proxy. 

USER --> 443[NGINX Reverse proxy] icingaweb2 -> 127.0.0.1:8080 (container 1)
                                           ||
           127.0.0.1/icingaweb2:8080 (http)  (container 2)

With this setup the images fail to load as the image is set to http://blah due to the backend being http.  It would be useful to be able to set the image schema (http/https) or even the server https://127.0.0.1 in the config like we can for external grafana links.

To workaround this we could configure the icingaweb2 to use ssl  or have nginx rewrite the html /http:/https/.

**Comment by Mikesch-mp** [comment]
You can set the protocol, please read the docs and recheck your module configuration
