### ISSUE TITLE
Grafana dashboard with influxdb2

### ISSUE THREAD

**Issue by rafi0101** [Mikesch-mp/icingaweb2-module-grafana#293]
Hello,

I am using icinga2 with influxdb2writer and an influxdb2 for performance data. Do you already have a Grafana dashboard with influxdb2 as backend?

With kind regards
Raphael

**Comment by cicigee** [comment]
Hi,

I was able to make myself a working dashboard by modifying the query used in the current release:
https://gist.github.com/cicigee/75454ea1e6968e5eb8a944d35d758b28

/Cici
