### ISSUE TITLE
Icingadbweb no graphs for new hosts

### ISSUE THREAD

**Issue by MarcusCaepio** [Mikesch-mp/icingaweb2-module-grafana#297]
Hi Carsten,
this probably goes together with the support for Icingadb(web).
With icingadb as backend, new hosts don't have any graphs. I get a "404 not found" in the browser devtools. Anyway, a click on the "missing picture" links to the correct grafana dashboard. Hosts and services, which were already configured before the change to the icingadb backend, are still working. 

Icinga Web 2 Version 2.11.1
grafana		1.4.2	
icingadb		1.0.0	

Thanks and cheers,
Marcus

**Comment by Mikesch-mp** [comment]
this version is  not made for icingadb, wait for 2.0.0
