### ISSUE TITLE
"default rendering" options in configuration

### ISSUE THREAD

**Issue by markusr** [Mikesch-mp/icingaweb2-module-grafana#3]
My suggestions are: 
- Add check box to enable/disable (If disabled only defined grafana graphs are shown)
- Add text box for default dashboard name

**Comment by Mikesch-mp** [comment]
> Add text box for default dashboard name
Added in 1.0.3

**Comment by markusr** [comment]
Thank you for the fast implementation. I just tested it and it works as expected.
