### ISSUE TITLE
Indirect Proxy and timespan selection is not working with Icingadb when Monitoring module is disabled

### ISSUE THREAD

**Issue by rafael-voss-fadi** [Mikesch-mp/icingaweb2-module-grafana#301]
- Indirect Proxy mode is not working, because it uses some code of the monitoring Module
- I can't select a Timespan because it links to the monitoring module:

![image](https://user-images.githubusercontent.com/67787769/198230580-ca9f70e7-f2c3-4558-bbe4-2dc1b5496d63.png)

**Comment by patrickesser** [comment]
The timespan-selector issue can be fixed by replacing the broken links in the gragana-grapher 'getPreviewHtml' function. 

From: 
/usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php

[..]
public function getPreviewHtml(MonitoredObject $object, $report = false)
   [...]
        if ($this->object instanceof Host) {
            $this->cacheTime = $this->object->host_next_check - $this->object->host_last_check;
            $serviceName = $this->object->check_command;
            $hostName = $this->object->host_name;
            $parameters = array(
         **// 'host' => $this->object->host_name,
                'name' => $this->object->host_name,**
            );
     **// $link = 'monitoring/host/show';
            $link = 'icingadb/host';**
        } elseif ($this->object instanceof Service) {
            $this->cacheTime = $this->object->service_next_check - $this->object->service_last_check;
            $serviceName = $this->object->service_description;
            $hostName = $this->object->host->getName();
            $parameters = array(
**//          'host' => $this->object->host_name,
                'name' => $this->object->host->getName(),**
                'service' => $this->object->service_description,
            );
        // $link = 'monitoring/host/show';
            $link = 'icingadb/host';
        }
