### ISSUE TITLE
disable the graph when no performance data are written

### ISSUE THREAD

**Issue by rafi0101** [Mikesch-mp/icingaweb2-module-grafana#302]
## Expected Behavior
Hide Performance Graph if no performance data are available / no performance data sent by the check

## Current Behavior
![image](https://user-images.githubusercontent.com/43086854/208631513-7115a675-c82d-4fdf-b416-ac64f998bafe.png)

**Comment by Mikesch-mp** [comment]
It dows show no graph when either the disable var is set correctly of `enable_perfdata = false`is set for a service.
if you use the module with icingadb, wait for 2.0.0

**Comment by rafi0101** [comment]
Is it possible that this could be detected automatically?
We do not have this option disabled anywhere,

**Comment by Mikesch-mp** [comment]
It is detected automatically when enable_perfdata is false or the disable var is set correctly.
if you need more help you should post examples and give more information
