### ISSUE TITLE
Macro Expansion for icingadb (v2.0)

### ISSUE THREAD

**Issue by fl0wx** [Mikesch-mp/icingaweb2-module-grafana#304]
hey,

could you please implement macro expanding here? See: https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/281#issuecomment-1432874352

So it will be possible to use custom vars with variable references and add them to grafana custom vars (for generating dynamic graphs).

Thanks and regards
fl0w

**Comment by Mikesch-mp** [comment]
You need that in private or for a company?

**Comment by fl0wx** [comment]
@Mikesch-mp what difference does that make? I need that for both currently

**Comment by Mikesch-mp** [comment]
the difference is that companie's dont get free support or new features. Feal free to provide a PR if you want that feature

**Comment by fl0wx** [comment]
@Mikesch-mp  ok ill look into that. can you provide any help or kickstart how to get into module development? what docs / ressources? Then ill do my best to provide a PR

**Comment by fl0wx** [comment]
@Mikesch-mp ping, can you maybe provide docs / informations on how to start on module development? and how to setup a proper test environment ?
