### ISSUE TITLE
v.2.0.0 Operation timed out after 30001ms with 0 bytes received

### ISSUE THREAD

**Issue by MarcusCaepio** [Mikesch-mp/icingaweb2-module-grafana#305]
Hi Carsten,
first of all, thanks a lot for the new release and the icingadb support.
I just updated the module and now run in a timeout for several services (but not all) with the message
`Operation timed out after 30001ms with 0 bytes received`
E.g. for services with several metrics or querries, like "disk: all partitions".
The module is set to indirectproxy access mode with token as authentication type and https.
Grafana runs on version 9.3.6
Following the link to grafana via click on the icingaweb2 panel leads to the correct dashboard and panel in grafana without delay.
If you need more information, please let me know.

Thanks and cheers,
Marcus

**Comment by Mikesch-mp** [comment]
Looks like the configured host and port is not reachable for icingaweb. enable debug and try to call the link in web browser and from command line via curl/wget.

**Comment by MarcusCaepio** [comment]
What I have found so far with the debug output: Given is the service name "disk: all partitions"
It seems the problem occurs when there is a ":" in the servicename. 
The Graph URL called by the module is
`/icingaweb2/grafana/icingadbimg?host=xxx&service=disk%253A%2520all%2520partitions&panelid=10&timerange=now-6h&timerangeto=now&cachetime=0` 
and does not work, although the PanelID and servicename is correct. 
By deleting the servicename and calling
`/icingaweb2/grafana/icingadbimg?host=xxx&panelid=10&timerange=now-6h&timerangeto=now&cachetime=0` 
the correct graph is shown. Changing back to the 1.4.2 module, the URL
`/icingaweb2/grafana/img?host=xxx&service=disk%253A%2520all%2520partitions&panelid=10&timerange=now-6h&timerangeto=now&cachetime=57.706000089645` 
also the correct graph is shown.

**Comment by Mikesch-mp** [comment]
Spaces and ':' are no problem for the module.
![image](https://user-images.githubusercontent.com/6574967/222057865-7518478b-180d-42c2-9c1f-2a25861b925a.png)
Can you please delete the config.ini (not the graphs) and reconfigure the module. just to see that there is no error

**Comment by MarcusCaepio** [comment]
Reconfigured the module, but unfortunately did not help. I don't think, that there is a config issue, as the panels worked in v1.4 and there are still several panels on the same dashbaord, which are  still working.

**Comment by Mikesch-mp** [comment]
Should work, the [graph config name](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#name-search-order) or the [custvarconfig](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/03-module-configuration.md#custvarconfig) are only important.
I think you have some misconfiguration there.

**Comment by MarcusCaepio** [comment]
As I already said, everything worked for ~2 years with V1.4 :) But the grafana_graph_config vars is a good indicator. I am just realising, that all services which are not working anymore, have a grafana_graph_config variable set. As this is the default custvarconfig, I did not set any additonal vars in the graph config. 
E.g. a service for Zombie processes:
```
apply Service "Zombies" {
  [...]
  vars.grafana_graph_config = "procs"
  assign where....
}
```
```
[procs]
dashboard = "basic-metrics"
panelId = "18"
orgId = "4"
height = "400"
repeatable = "no"
dashboarduid = "basic-metrics"
```
Maybe this is currently not working correctly? Or do I have to set Custom Variables in the Graph Config now?

**Comment by Mikesch-mp** [comment]
DONT USE BASE-METRICS DASHBOARD!!!!

**Comment by MarcusCaepio** [comment]
Seriously, why are you closing it? I'm just trying to help... 
It doesn't matter, if the dashboard is called "basic-metrics", "metrics" or whatever. I have several dashboards with dedicated panels, where units, axes etc. are defined. The icinga2-default dashboard is just a fallback dashbaord for services, where no explicit panel exists. I also got another dashboard where the exact same error occurs. Rolling back to V1.4.2 and everything is working fine again. Also cloning the basic-metrics dashboard into a totally new one with different name and dashboard UID does not work after adjusting all settings in the graphs.ini.
So imho it seems that "grafana_graph_config" is ignored in V.2...

**Comment by MarcusCaepio** [comment]
> Found a bug for proxymode that used the wrong variable to determine the config to used. will be fixed in the next version

Thank you! :)
