### ISSUE TITLE
After Upgrade to 2.0.0b Grapher not found

### ISSUE THREAD

**Issue by TheCry** [Mikesch-mp/icingaweb2-module-grafana#306]
I'd installed IcingaDB and switched from ido to IcingaDB. Then I'd installed the new version of icingaweb2-module-grafana.

## Current Behavior
```
Uncaught Error: Class 'Icinga\Module\Grafana\ProvidedHook\Grapher' not found in /usr/share/icingaweb2/modules/grafana/application/controllers/DashboardController.php:47
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\DashboardController->indexAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#6 {main}
thrown

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## Steps to Reproduce (for bugs)
Rename existing grafana folder. Install icingaweb2-module-grafana with git.
Open service with graph and oopen graph in new window.

## Context
After upgrading icingaweb2-module-grafana from 1.4.2 to 2.0.0b the error exists

## Your Environment

* Icinga Web 2 Grafana version (System - About): version: 2.0.0b
* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga DB: 1.0.2
* Version used (`icinga2 --version`): r2.13.7-1
* Operating System and version: Debian 10
* Enabled features (`icinga2 feature list`): api checker graphite icingadb ido-mysql mainlog notification
* PHP: 8.1.16
* incubator: 0.17.0
* ipl: v0.5.0
* reactbundle: 0.9.0
* Grafana: 9.3.6

**Comment by Mikesch-mp** [comment]
YOu have also installed icingadb web? Error you have is when you still have the old monitoring module installed and active

**Comment by TheCry** [comment]
Yes... Everything was installed. But i got it working now. I'd changed one parameter in the grafana config (web) and saved it. After this the WebUi and Grafana Modul works. No more errors.
