### ISSUE TITLE
Performance data not showing on latest 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by Manojnamdev** [Mikesch-mp/icingaweb2-module-grafana#308]
## Current Behavior

After upgrading from 1.4.2 to 2.0.1 the graphs are not displaying.

We have also checked the similar issue is having with the 2.0.0.

Attaching screenshot for the same.

![image](https://user-images.githubusercontent.com/4556651/224673598-ce50292b-2597-4b3d-9772-d8e9b7a78f8a.png)

## Expected Behavior
The performance data should be displayed as it was displaying in the 1.4.2

## Steps to Reproduce (for bugs)
1.  icingaweb2-module-grafana-2.0.1 

## Your Environment

* Icinga Web 2 Grafana version (System - About): Grafana-9.4.3
* Icinga Web 2 version and modules (System - About):r2.11.2-1
* Version used (`icinga2 --version`): version: r2.11.2-1
* Operating System and version: Ubuntu-20.04.5 LTS (Focal Fossa)
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
Grafana Module >= 2.0.0 is only for use with icingadb
