### ISSUE TITLE
Can't add a grafana graph to the dashboard.

### ISSUE THREAD

**Issue by duckq** [Mikesch-mp/icingaweb2-module-grafana#309]
Hello.
I have the problem with adding graph to the dashboard as described below (Current Behavior).

## Current Behavior

Can't add a grafana graph to the dashboard. The operation fails with an error:

```
Required parameter 'host' missing
#0 /usr/share/icingaweb2/modules/grafana/application/controllers/IcingadbdashboardController.php(37): Icinga\Web\UrlParams->getRequired()
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Grafana\Controllers\IcingadbdashboardController->indexAction()
#2 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#4 /usr/share/icingaweb2/library/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#5 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}
```
## Expected Behavior

![image](https://user-images.githubusercontent.com/71126528/225879276-799ebc1b-3bc3-4be2-b572-916c44302432.png)

## Possible Solution

I achieved the expected behavior by manually modifying the url as below.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/71126528/225880385-baecaed9-110a-4c97-8514-a302541bcc35.png">

## Steps to Reproduce (for bugs)

1.Choose the timeframe for the graph (e.g. 8 hours).
<img width="773" alt="image" src="https://user-images.githubusercontent.com/71126528/225874095-640666bf-c48e-4bff-80d3-c25aeee84a0d.png">
2.Add graph to the dashboard.
<img width="773" alt="image" src="https://user-images.githubusercontent.com/71126528/225874769-bd04f37e-845e-4a92-8297-8831b6ae6ebe.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/71126528/225876173-0e0801a3-c13b-44f0-8d02-85041d2fbe9d.png">
3. Error: "Required parameter 'host' missing"
<img width="787" alt="image" src="https://user-images.githubusercontent.com/71126528/225876608-fff41a77-46db-4338-87c4-c69228faf125.png">

## My Environment

![image](https://user-images.githubusercontent.com/71126528/225871374-44144c96-9c51-4a7e-8587-4b722f43de52.png)

**Comment by Mikesch-mp** [comment]
Hosts are working , services are broken. will fix it with next release. Thanks for reporting
