### ISSUE TITLE
Icinga monitoring module not compatible with grafana v2.0.1

### ISSUE THREAD

**Issue by rafi0101** [Mikesch-mp/icingaweb2-module-grafana#314]
Hi,
I do not use icingadb now but still want to use the grafana module with the icingaweb monitoring module.

See:
![image](https://user-images.githubusercontent.com/43086854/229837910-bbbdd131-4638-4447-b177-11f2fd63375a.png)

Maybe you can solve it like they did with the jira integration:
![image](https://user-images.githubusercontent.com/43086854/229838616-4f20eb77-68d4-4aff-984e-0d9ce0ae7fde.png)

**Comment by Mikesch-mp** [comment]
Thern you have to use the v1.4.x
