### ISSUE TITLE
Support PHP 7.2.24

### ISSUE THREAD

**Issue by drapiti** [Mikesch-mp/icingaweb2-module-grafana#315]
Please provide support for PHP 7.2.224, and not just PHP 8.1 as this version of PHP is not available on RHEL 8 which is the main stream version at the moment in many enterprise environments. 
The requirements should be similar to icingaweb2.

**Comment by Mikesch-mp** [comment]
PHP 7.2 is out of support / End of Life , see https://www.php.net/supported-versions.php.
There are newer php versions also for redhat 8 available

**Comment by drapiti** [comment]
As far as I can see documented on the Redhat 8 website. Maybe php 8.0 is available with a short support cycle from RHEL release 8.6 , however php 8.1 is not present at all. Since redhat is the official Icinga partner it would be best to follow RHEL support cycles or request redhat update it's packages officialy. Would this work with php 8.0?
![image](https://user-images.githubusercontent.com/4235359/233072675-d6aac170-abd6-427f-b1e8-f5d1ff77197f.png)

**Comment by Mikesch-mp** [comment]
https://rpms.remirepo.net/wizard/
