### ISSUE TITLE
Support PHP 7.4 

### ISSUE THREAD

**Issue by drapiti** [Mikesch-mp/icingaweb2-module-grafana#316]
Currently there is no PHP 8.1 support on RHEL 8. 
![image](https://user-images.githubusercontent.com/4235359/233096079-dcb83b13-67ca-4416-a37f-03b4d3936a68.png)

PHP 7.4 is required for RHEL 8.

**Comment by Mikesch-mp** [comment]
Opening new issues for the same issue ist not really helpful. Use Remi for a new php version. 
https://rpms.remirepo.net/wizard/
