### ISSUE TITLE
Repeating Panels configuration

### ISSUE THREAD

**Issue by markuslf** [Mikesch-mp/icingaweb2-module-grafana#317]
Imagine a Grafana dashboard like this, with repeating rows (!), based on a query that reads all the disks of a host (count differs from host to host). Each row shows the same several non-repeating panels.

![image](https://user-images.githubusercontent.com/31855393/234306330-f30f2997-1ac5-4ae6-b490-3bc590f238e3.png)

Am I right that the Grafana module cannot handle this today?
* If not, consider it a feature request ;-)
* If yes, please help me: How to set what value to what? Obviously "Repeating Panel=Yes", but "PanelIds=1" makes no sense here and "Metrics per panel" is impossible to guess. :-)

**Comment by Mikesch-mp** [comment]
Please read the docs, https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#auto-repeating-panels
It does exactly what you want to do, you just need to configure the dashboard for the module

**Comment by markuslf** [comment]
Ok, let me use another example - network I/O on network interfaces. What I mean is:

Like with disks, the "number of metrics" is dynamic. "metrics" example for a "network-io" check:
* Host 1: eth0_bytes_recv, eth0_bytes_sent
* Host 2: ens10_bytes_recv, ens10_bytes_sent, tun0_bytes_recv, tun0_bytes_sent, eth0_bytes_recv, eth0_bytes_sent

Therefore the number of red-highlighted panel rows is also dynamic.

Screenshot 1 - Dashboard "Network I/O", host 1 with one network interface:
![image](https://user-images.githubusercontent.com/31855393/234505789-1114c0d4-e44a-4015-b085-db23fda10d7f.png)

Screenshot 2 - the same dashboard, host 2 with multiple network interfaces:

![image](https://user-images.githubusercontent.com/31855393/234506232-8fd3bc73-03ab-4d9b-8379-cde20c1fdfce.png)

The "Network I/O" dashboard handles that fine, but following your docs I can't figure out any numbers to configure the Grafana module for this type of dashboard properly.

**Comment by Mikesch-mp** [comment]
Works only for repeating panels, not for rows. Cant be added as feature, because there is no way to figure out the row numbers / names

**Comment by markuslf** [comment]
That's what I wanted to know, thank you, Carsten.
