### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by mlg1** [Mikesch-mp/icingaweb2-module-grafana#336]
Pretty bad documentation. Please fix it. 90% of things I have to guess.

**Comment by RincewindsHat** [comment]
Not the maintainer here, but with all the necessary respect, this is a very poor issue description and I would suggest to either pay someone to fix whatever annoys you or do the work yourself instead of just complaining.

Sorry for the unfriendly language, but I think it needs to be said.
