### ISSUE TITLE
custom vars missing in link url

### ISSUE THREAD

**Issue by vita2** [Mikesch-mp/icingaweb2-module-grafana#36]
hello mikesch,

could you include the custom variables in the image link url, please? because of the missing vars i can't immediately jump to the right graphs. 

![grafana-icingaweb2](https://cloud.githubusercontent.com/assets/25298055/25344753/5eb265e6-2913-11e7-9926-f1badd02f7e3.png)

![grafana-graph](https://cloud.githubusercontent.com/assets/25298055/25345052/356a5b8e-2914-11e7-8c67-9609921aeea6.png)

here is the ``graphs.ini`` for my ``snmp-interface-custom`` command (extended check_snmp_int.pl):
```
[snmp-interface-custom]
dashboard = "icinga2"
panelId = "3"
customVars = "&var-snmpinterface=$snmp_interface$_in_bps&var-snmpinterface=$snmp_interface$_out_bps"
```

regards

**Comment by Mikesch-mp** [comment]
Fixed this in 1.1.2 branch. Will be released as soon @dnsmichi  send his PR for #35 . If you cant wait for the release ,you can just replace the file library/Grafana/ProvidedHook/Grapher.php with the one from 1.1.2 branch.

**Comment by vita2** [comment]
thank you 🍻

**Comment by dnsmichi** [comment]
Sorry, some Vagrant foo did hold me off from pushing a fix earlier.
