### ISSUE TITLE
Add a GitHub description

### ISSUE THREAD

**Issue by dnsmichi** [Mikesch-mp/icingaweb2-module-grafana#38]
Currently it says `No description, website, or topics provided.`.

I'd suggest to change that to

- description: Grafana module for Icinga Web 2 (supports InfluxDB & Graphite)
- website: none, or you may link to https://www.icinga.com/products/icinga-web-2-modules/
- topics: icingaweb2, icinga, grafana, influxdb, monitoring, metrics, integrations

**Comment by Mikesch-mp** [comment]
Iam still learning everyday something new about Git :)
