### ISSUE TITLE
Feature request - grafana graphs names wildcards specifications

### ISSUE THREAD

**Issue by junkett** [Mikesch-mp/icingaweb2-module-grafana#39]
Hi
I am using grafana module for couple of weeks now and I am generally happy with it as it is very useful module, I simply did not find anything with such possibilities yet.
I have one feature request (at least i did not find a way how to do this myself).
I have this situation:
We have multiple similar services that are checking similar stuff but they are named differently (also their check commands are), e.g. oracle-tablespace-usage-TEST / oracle-tablespace-usage-STAGE / oracle-tablespace-usage-PROD, they all use same graph but I have to define 3 different graphs inside icingaweb. 

It would be very handy if the module understand that if I define e.g.: oracle-tablespace-usage-* it would basically use such graph for any services matching this wildcard.

Regards David

**Comment by Mikesch-mp** [comment]
Hello David,

the module searches first for servicename with options like "harddisk c:\", if no confguration found it searches for "harddisk" and if still no configuration, it tries to find one for the check_command "disk".
So for your problem just configure a graph with name "oracle_health", that should be the command name.

But i will keep this open, have to test an idea for regex searches, but cant say in which version i can put it right now.

Best regards,
Carsten

**Comment by friesoft** [comment]
We are currently trying a similar thing. Most of our services use the check_command by_ssh. So only the service names are used to distinguish services.
I'm trying to match "Disk Mountpoint /opt" with a graph config "Disk Mountpoint". It isn't matching though :( It always falls back to the default dashboard.

Regex would also really help us :)

**Comment by Mikesch-mp** [comment]
With 1.2.0 you can define the used graph configuration inside a custom variable. Its not a regex, but it should also solve your problem.

**Comment by Aleksey-Maksimov** [comment]
Can you explain on a concrete example, how "custom variable" can help me?
I have 3 services "Network Utilization eth0", "Network Utilization eth1", "Network Utilization eth2" from one host. Now I have to create in "Grafana Graphs" 3 different records for each service. How could I make the setting more universal? If a wildcard were supported, I simply could create one rule for all kinds of interfaces. For example "Network Utilization *"

**Comment by Mikesch-mp** [comment]
Configure a graph, lets say you name it `network_utilization` like you would do it for the service itself.
Then you configure (in the module configuration) the name of the variable that will hold the just configured graph, i used `use_graph_config` as the name.

![image](https://user-images.githubusercontent.com/6574967/41243103-a29502b8-6da1-11e8-8add-560e2920ed4c.png)

After that you can add this to your service 
```
vars.use_graph_config = "network_utilization"
```

From now on the service will use the dashbaord & panel from the graph `network_utilization` ;)

Regards,
Carsten
