### ISSUE TITLE
Graphs don't refresh when Grafana access mode is direct

### ISSUE THREAD

**Issue by GaryElmes** [Mikesch-mp/icingaweb2-module-grafana#41]
When the Grafana access mode is set to "direct", the graphs are not updated when the service/host page refreshes.

**Comment by Mikesch-mp** [comment]
Yeah thats right, because the URL for the image does not change. So your browser will cache it until you  change the timerange or hard refresh the age (shift + f5). Think i have to add an option to enable image refresh also like in proxy mode.
