### ISSUE TITLE
Feature Request: Use iframe src instead of rendering the preview

### ISSUE THREAD

**Issue by gitmopp** [Mikesch-mp/icingaweb2-module-grafana#45]
In the current configuration `Grapher.php` creates a PNG using the render function of Grafana. An image is static.
It would be nice to use `iframe src=` to have a more dynamic graph. The problem with iframe might be the authentication. Basic authentication seems not to work very well with iframes. There might be a workaround using javascript to send the authentication headers.

**Comment by Mikesch-mp** [comment]
HI,

iframes are note possible in host/service view of Icingaweb2. They will be also refreshed every 10 seconds. The module is only to give you a quick graph and when you want to see more, just click on it and it will take you to grafana.

Best regards,
Carsten
