### ISSUE TITLE
Proposal: url and publicUrl config settings

### ISSUE THREAD

**Issue by mnsh** [Mikesch-mp/icingaweb2-module-grafana#46]
Proposal:
1. Introduce a config setting ```[grafana]``` -> ```url```, superseding & deprecating ```protocol``` and ```host```.
  From what I can see, the only uses of the current settings involve merging them into a URL. Also, ```host``` can be set to ```server.name:1234/path```, which is even less of a "host" than ```server.name:1234```.

   If ```url``` isn't set, it should default to ```${protocol}://${host}```.

2. Introduce an optional config setting ```[grafana]``` -> ```publicUrl```. If unset, it should default to the value of ```url```.

   This should be used for embed URLs in direct mode as well as the graph links in proxy mode.

These settings would allow a configuration like:
```
[grafana]
url = "http://localhost:3000"
publicUrl = "https://icingaweb2.host.name/grafana"
accessmode = "proxy"
enableLink = "yes"
```
to serve proxied graphs quicker (no SSL overhead) while presenting "proper" URLs for links to grafana dashboards.

I think a lot of installs out there would benefit from such a configuration.

**Comment by Mikesch-mp** [comment]
HI,

your right when it comes to protocol / host. But from my experience it is easier for the most of the users to configure it the way it is now. And if you think about it, that is an option you dont change every day.
For the publicurl you mentioned, i dont know any way to configure Grafana to allow direct access (host:3000) and proxy mode (host/grafana) at the same time.

For your SSL overhead:
`[root@koelin01 ~]# time wget --no-check-certificate 'https://koelin01.fritz.box:3000/render/dashboard-solo/db/amazon?orgId=1&panelId=1&from=1493791819075&to=1493964619076&var-hostname=Amazon&var-service=Price%20WMF-0792239990&width=1000&height=500&tz=UTC%2B02%3A00'

real    0m2.359s
user    0m0.033s
sys     0m0.016s
`

Without SSL

`[root@koelin01 ~]# time wget 'http://koelin01.fritz.box:3000/render/dashboard-solo/db/amazon?orgId=1&panelId=1&from=1493791819075&to=1493964619076&var-hostname=Amazon&var-service=Price%20WMF-0792239990&width=1000&height=500&tz=UTC%2B02%3A00'

real    0m2.270s
user    0m0.003s
sys     0m0.009s
`

**Comment by mnsh** [comment]
Hi,

For the configuration: you simply run grafana on localhost:3000 and use a proxy (apache, nginx etc) in front of it. In my case, the apache vhost running icingaweb2 proxies ```/grafana``` to localhost:3000.

The SSL overhead is there, but it takes a very busy server before it translates to noticeably longer response times; otherwise it mostly shows as higher cpu usage. Try your test with something like ```ab -c10 -n1000 -l``` instead of ```wget``` and look at cpu usages in addition to response times.

If you don't like renaming existing config settings - maybe you could consider adding ```publicProtocol``` and ```publicHost``` to achieve the same functionality?

**Comment by dnsmichi** [comment]
1.) host:port makes more sense to me, some implementations also keep using node:service or similar. That way you can iteratively build your configuration files from hash keys in Puppet for instance, and don't need to use string concat. More of a cosmetic thing, but anyways.

2.) public URL means more or less that you see "host:port" (or url) as an internal storage provider, while the rendered external URLs can be configured to use a different host:port setting. While I do understand it now, I think this will complicate the setup.

**Comment by Mikesch-mp** [comment]
let me see how i will add this, maybe i get it without complicate the setup for normal users.

**Comment by Mikesch-mp** [comment]
Added in v1.1.4

**Comment by mnsh** [comment]
Works fine. Thanks!

**Comment by terrik15** [comment]
Hi, 

I have the following problem, if I use https as the protocol, the connection to the grafana does not work because https://localhost:3000 is called again and again, but the certificate runs on the FQDN and not for the name localhost. If I change it to http then everything works fine in icinga and the external link

As a workaround, I put a reverse proxy in front of grafana, but if I specify https for the public protocol, this is ignored and the public host continues to try to address it with http instead of https. If I enter https to the new browser tab for the external link, it works fine.

Could it be that Public Protocol is being ignored? Or back to the actual problem: what is the reason that when https is activated in the host, access to https://localhost:3000 is always carried out, even if the FQDN is entered.
