### ISSUE TITLE
Proposal/Wish: Add a configuration switch for the theme/style

### ISSUE THREAD

**Issue by mcktr** [Mikesch-mp/icingaweb2-module-grafana#50]
Hello Carsten, 

first of all: great work! I really like your module.

This is gonna be really subjective. With the last update you added a shadow around the graph. I am not really a fan of those shadows, I liked the 'flat' style you've had before.

Maybe there are some other people who think like me. If you add an switch in the configuration tab to choose the style of the graph you would made both happy, people who like the shadow and those who dont.

Cheers

**Comment by dnsmichi** [comment]
Hmmm, I'd opt to entirely remove the image shadow. That does not fit the general Icinga Web 2 style and looks a bit strange. I know that this is coming from #49.

![screen shot 2017-05-22 at 11 01 57](https://cloud.githubusercontent.com/assets/382049/26300372/308da3c0-3ede-11e7-81c3-b096e6d40c70.png)

Another option would be to use CSS classes and allow users to modify such. Right now it is just inline PHP code which makes it impossible to override.

**Comment by Mikesch-mp** [comment]
I found no way to use my own css classes inside a hook :( 
Will remove the shadows with next release, but keep them in mind until i find a way to use CSS inside the hook.

**Comment by epinter** [comment]
The grafana graph background color has a light gray by default (don't fit icinga style) or black. My idea with the shadow was make the image to appear different from the rest, to show the user the image came from other system. Personally, I prefer the dark theme by default.

I think the css class is the best option. I will try to work on this.

**Comment by epinter** [comment]
#53 allows the use of css classes (defined in module.less)

**Comment by Mikesch-mp** [comment]
Users can edit module.less to have shadows if they want.
