### ISSUE TITLE
Unable to import json dashboards

### ISSUE THREAD

**Issue by hermannkm** [Mikesch-mp/icingaweb2-module-grafana#51]
When I try to prepare grafana for use with this module I understand it is necessary to import the dashboards given (icinga2-default, base-metrics).
Do I have to edit them beforehand?
When I try to import the first an error message is given:

> Dashboard init failed
Template variables could not be initialized: Datasource named ${DS_ICINGA2-GRAPHITE} was not found

I am a newbie with Graphite/Grafana - sorry if this has been said somewhere.

**Comment by Mikesch-mp** [comment]
Hi,

did you create a datasource first in Grafana? If you have one defined (InfluxDB or Graphite) you can import the dashboards and the dialog should ask you which datasource you want to use for it.

Regards, 
Carsten

**Comment by hermannkm** [comment]
Hi Carsten,

yes I did (and renamed it to GRAPHITE) - I have graphite locally installed, so my definition is 

http://localhost:8000 <http://localhost:8000/>

and I can use it inside Grafana to plot some data. Any hint?

Hermann

**Comment by Mikesch-mp** [comment]
HI Hermann,

not really. How did you try to import them ? When i import a dashboard, Grafana asks me about which datasource i want to use for it.

![image](https://cloud.githubusercontent.com/assets/6574967/26294161/0d852658-3ec2-11e7-8260-ca4582e8ed55.png)

**Comment by dnsmichi** [comment]
That error is usually thrown if you import the dashboard via curl request on the CLI. I needed to modify the files for automated setups, see https://github.com/Icinga/icinga-vagrant/commit/dba3c7820d7a395b1e2bd0e12f411018fe1604b1

**Comment by hermannkm** [comment]
Thank you all for trying to help.
At the moment after quite an amount of trying I could not get it to run, I can state:
1. On my Ubuntu 16.04 the version of grafana installed by using the standard repo is shown as 2.6.0+dfsg-1. This seems to be some 3.9.x version. Although I read the grafana installation instructions and added a grafana repo I cannot persuade my apt to install any other version. So I am stuck with this version which I know is not the required v. >= 4.1 for this plugin. Sorry.
2. I managed to import dashboards, they are shown nicely in grafana, but activating the plugin in icinga2 gives missing panel/dashboard messages. Your installation tutorial commands me to give panelId of 1 to icinga2-default dashboard which seems to be impossible in this version of grafana.

**Comment by Mikesch-mp** [comment]
You should remove the Grafana from standard repo first and then activate the Grafana repo and install it from there.
Taken from the docs http://docs.grafana.org/installation/debian/
```
echo "deb https://packagecloud.io/grafana/stable/debian/ jessie main" >>/etc/apt/sources.list
curl https://packagecloud.io/gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install grafana
```
Dont change the "jessie" or it will not work.

**Comment by hermannkm** [comment]
Thank you - that worked instantly (the "jessie main" was the important part). I am now on 4.3.1!

**Comment by Mikesch-mp** [comment]
Your welcome :)
