### ISSUE TITLE
Module dont show labels or text in Icingaweb2

### ISSUE THREAD

**Issue by Simkimdm** [Mikesch-mp/icingaweb2-module-grafana#54]
Hi Mikesch, 
i successfully installed your module. 
It shows the Graph but no Labels or Text.
I tried following:
Install curl - already installed
Change Grafana Theme from dark to light
Other Browser - Same issue
What did i wrong? 
In icingaweb2 it looks like:
![grafik](https://cloud.githubusercontent.com/assets/26118956/26343501/7caf4b96-3f9c-11e7-9446-8967e1a08f27.png)
On the Grafana Board it looks like this:
![grafik](https://cloud.githubusercontent.com/assets/26118956/26343541/aa91affe-3f9c-11e7-9401-c29bcf37c8b6.png)

**Comment by Mikesch-mp** [comment]
Grafana Version ?
Linux Distribution and Version ?

**Comment by Simkimdm** [comment]
Grafana Version 4.2
Red Hat 4.8.5-11

**Comment by Mikesch-mp** [comment]
Hmm looks like you miss some packages.
Please follow the docs from Grafana to install them
http://docs.grafana.org/installation/rpm/#server-side-image-rendering

**Comment by Simkimdm** [comment]
Yeah. Thank you very much. 
Its working now.

**Comment by Mikesch-mp** [comment]
Your welcome
