### ISSUE TITLE
Parse error: syntax error, unexpected '[' in Grapher.php

### ISSUE THREAD

**Issue by d-zalewski** [Mikesch-mp/icingaweb2-module-grafana#55]
Just tried latest checkout with icingaweb2 2.4.1 and grafana 4.3.1

Parse error: syntax error, unexpected '[' in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php on line 156

My grafana module config:

```
[grafana]
host = "10.10.0.100/grafana"
protocol = "http"
defaultdashboard = "icinga2-default"
defaultdashboardstore = "db"
datasource = "influxdb"
accessmode = "direct"
directrefresh = "no"
height = "280"
width = "640"
enableLink = "yes"
usepublic = "no"
```

**Comment by Mikesch-mp** [comment]
Please post your module version and your php version.

**Comment by d-zalewski** [comment]
root@ams-nms0 grafana]# grep Version module.info
Version: 1.1.5
[root@ams-nms0 grafana]# rpm -q php
php-5.3.3-49.el6.x86_64

**Comment by Mikesch-mp** [comment]
Yepp its your PHP Version. Really out of support already :) But i changed the code so it should work now also with PHP 5.3. But better consider to update thaat very soon

**Comment by d-zalewski** [comment]
Yeah its standard php version from centos 6.x . Just upgrade to latest 5.6.x and problems solved
