### ISSUE TITLE
Wildcard operator to define custom graphs

### ISSUE THREAD

**Issue by markusr** [Mikesch-mp/icingaweb2-module-grafana#6]
We have several icinga2 services that all have the following name:    ```[location]_googledns_ping4```

It would be nice if we could define a custom graph with a  wildcard  operator (or regex?). Such as:
![grafik](https://cloud.githubusercontent.com/assets/1866703/23580313/47d36104-00ff-11e7-98ac-7d7235a515bf.png)

**Comment by Mikesch-mp** [comment]
if you name your services like "ping4 [location]_googledns" or "ping4 googledns [location]" you can configure a graph named "ping4". The grapher will look first for example a service named "ping4 [location]_googledns" if not found it will look for "ping4" only.  Icinga2 can handle a "space" in names a lot better then icinga1 did 😄

**Comment by KKeXX** [comment]
Hello,
I would like to see this feature too. 
For example we monitor different hostnames (hostalive4) so something like *.domain.tld would be nice!
Or monitoring of processes: tnslsnr[eipq][1-9]0
That would help very much!

**Comment by Mikesch-mp** [comment]
Hi,

as i wrote above. name your service somthing like "process blubb blubber 1234", then you can do a panel for "process" which will match all services that dont have a own configuration. for example you have 3 services "process first", "process second" and "process third" + graph configuration for "process" and "process third". first 2 will match to the graph "process" , "graph third" will match to the graph configuration "process third".

**Comment by markusr** [comment]
@Mikesch-mp I understand that if you rename your services the graphs will be generated correctly. However, I think that for most users (including me) it is not a practical solution to rename a lot of their existing services just for getting this plug-in to work. I would prefer a solution in which a user is not forced to change their existing set-up.

**Comment by Mikesch-mp** [comment]
@markusr iam still thinking about this. would it help to change to module from service name based to command name? From my side it was my biggest mistake to go for service names and not on command name.

**Comment by markusr** [comment]
@Mikesch-mp Yes, changing it to the command name would solve all the service naming problems. Very good idea.

**Comment by markusr** [comment]
I just saw that you already added check_command support. I updated the plug-in and it works fine for me. From my point of view we can close this issue.
