### ISSUE TITLE
No Graph while Status Unknown

### ISSUE THREAD

**Issue by Simkimdm** [Mikesch-mp/icingaweb2-module-grafana#66]
Hi, 
there is no graph when the Status is Unknown. But there is one in Grafana.
Icingaweb2:
![grafik](https://cloud.githubusercontent.com/assets/26118956/26624821/638e43b8-45f2-11e7-9ace-c027f1a1dfef.png)

Grafana:
![grafik](https://cloud.githubusercontent.com/assets/26118956/26624868/8fd485fe-45f2-11e7-8339-d437c933cfb1.png)

**Comment by dnsmichi** [comment]
If you manually submit an OK check results for tests, is the graph shown in the detail view in Icinga Web 2?

**Comment by Simkimdm** [comment]
Hi, 
only Ok Check result test, doesnt help. but when i add performance data to the test check result then it´s shown.

**Comment by Mikesch-mp** [comment]
This comes from #20 . If there is no perfdata or perdata disabled it will not show the graph.
Have to think about to revert that change or make it config options.

**Comment by epinter** [comment]
I think if the host has perfdata enabled (process_perfdata ?), the graph should be shown, no matter it is generating perfdata now or not.

**Comment by Mikesch-mp** [comment]
I will remove #20 partly to show graph even if there is no perfdata.
Because you can use
- enable_perfata = false in host/service config
- disable graph with customvar (even if there is perfdata)

Hope @xbulat is not mad at me :)

**Comment by dnsmichi** [comment]
Now that I see it - #20 isn't correct with the runtime state assumption of no perfdata. Sometimes there are plugins which do not output perfdata when the state is unknown, but history in TSDBs prove otherwise Fixing all those plugins isn't possible ;)
