### ISSUE TITLE
1.1.5 - No more scaling of the graph size ?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Mikesch-mp/icingaweb2-module-grafana#67]
Hello, Mikesch-mp

In version **1.1.4** was a good scaling of the graph size (graph is dynamically reduced). 
Also was beautiful (in my opinion) shadow borders for graphics. 

![view114](https://cloud.githubusercontent.com/assets/17614847/26646914/96bbd35c-464e-11e7-90bc-2ca780eedbb2.png)

In version **1.1.5** it's all gone. 

![view115](https://cloud.githubusercontent.com/assets/17614847/26646934/a347cf40-464e-11e7-966e-f2861048261f.png)

Why?

**Comment by Mikesch-mp** [comment]
Can you please test the latest master. Its already 1.1.6. 
For the shadows, if you want them back just edit the CSS file to

```
.grafana-img {
    display: block;
    box-shadow: 0 3px 15px 0 rgba(0, 0, 0, 0.55) !important;
    width: auto;
    height: auto;
    max-width: 100%;
    max-height:100%;
    border-radius: 5px;
}
```

I will make it an config option in the final 1.1.6

**Comment by Mikesch-mp** [comment]
Added shadows option with a8d643710733190619c0201531286ef1dc3851ff
