### ISSUE TITLE
No datapoints when host check_command = icmp

### ISSUE THREAD

**Issue by MarcusCaepio** [Mikesch-mp/icingaweb2-module-grafana#7]
Hi Mikesch,
after seeing your module at Icinga Camp yesterday, I also want to try it.
So I use ICMP instead of hostalive for host checks. Sadly, I get an empty grafana graph on the host overview page with "no datapoints". Also after changing host check_command to hostalive, I don't get a graph. Can you give me a hint how to fix this? I am currently new in this 
grafana stuff :D

Thanks in advance

Marcus

![screeny](https://cloud.githubusercontent.com/assets/7324088/23694755/db6ba492-03db-11e7-978d-145512fe795f.JPG)

**Comment by Mikesch-mp** [comment]
Hello Marcus,

what datasource backend are you using?  If you use InfluxDB go to the dashboard and change the hostalive graph query from "hostalive" to "icmp" like in the pictrue below.

InfluxDB version:
![image](https://cloud.githubusercontent.com/assets/6574967/23714847/00d282f6-042b-11e7-9a57-9106d5d13015.png)

**Comment by MarcusCaepio** [comment]
I am using InfluxDB and your Dashboard where all services are shown. (https://grafana.net/dashboards/1572)
I got it working now, but my Querry looked totally different at the beginning. 
But thanks a lot :)
