### ISSUE TITLE
Graph is not displayed if service status UNKNOWN

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Mikesch-mp/icingaweb2-module-grafana#71]
Hello.

Today one of my hosts is DOWN. 
And Graph (historical data for the last time) became unavailable on Icinga Web :(

**Comment by Mikesch-mp** [comment]
Module Version ?
Which Graph? (Host or service)

**Comment by Aleksey-Maksimov** [comment]
1.1.5
Host and Service

**Comment by Mikesch-mp** [comment]
Please install 1.1.6

**Graphs will stay visible when there is no perfdata in last check**

https://github.com/Mikesch-mp/icingaweb2-module-grafana/releases/latest

**Comment by Aleksey-Maksimov** [comment]
Well. I updated via the git releases

# cd /usr/share/icingaweb2/modules/grafana/
# git fetch
# git checkout v1.1.6
Previous HEAD position was 08eaced... Add more timeranges
HEAD is now at 27d7391... Reverted dont show graph with no perfdata from #20. closes #66

And now I get error: Undefined variable: imgClass (https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/68)

**Comment by Mikesch-mp** [comment]
Strange it was fixed with commit 7a1046589c88488f9c3469e55e843a6bed2f2426
Can you do a "git pull" please

**Comment by Aleksey-Maksimov** [comment]
My colleague (a specialist in Linux) recommends me not to use "git pull". Instead, I use the git releases (git fetch / git checkout ). It is more convenient. If after installing a new release something gets broken I can easily switch to the previous release.
So, thank you, but I'll wait for the next release that nothing breaks.

**Comment by Mikesch-mp** [comment]
I know i did a mistake by fixing that without a new release. 1.1.7 will be there in a minute.

**Comment by Mikesch-mp** [comment]
1.1.7 is available now.

**Comment by Aleksey-Maksimov** [comment]
Great. Thank you. Now everything is working.

**Comment by dnsmichi** [comment]
> My colleague (a specialist in Linux) recommends me not to use "git pull". Instead, I use the git releases (git fetch / git checkout ). It is more convenient. If after installing a new release something gets broken I can easily switch to the previous release.
So, thank you, but I'll wait for the next release that nothing breaks.

That's perfectly fine. But it would really be helpful if you could test these things and provide feedback :) That way fixes are confirmed prior the release, and you can happily update your production environment afterwards.

In case you're looking for test environments, I've added such details in #72 and #74.
