### ISSUE TITLE
feature: per user settings

### ISSUE THREAD

**Issue by p0nt** [Mikesch-mp/icingaweb2-module-grafana#77]
It would be awesome to be able to use per user settings so we can personally choose between iframe / direct or proxy.

(not sure if its possible because they are 'general' module settings)

**Comment by dnsmichi** [comment]
I wouldn't do that. Imagine your NOC team calls and says 'graph is not rendered'. Your answer 'which user and how did you configure the access mode ?'. Imho this should be just a global setting and the preferred mode is chosen globally.

If you for instance need a public frontend with partial modules being accessible, I would definitely opt for a second setup on a dedicated web server.

**Comment by Mikesch-mp** [comment]
dnsmichi was (again) faster then me :) But i see it like dnsmichi wrote.

**Comment by p0nt** [comment]
I agree, lets close this.
