### ISSUE TITLE
How to select which variables will be displayed on service graph?

### ISSUE THREAD

**Issue by kalimalrazif** [Mikesch-mp/icingaweb2-module-grafana#78]
Good day: 

How can I select wich variable will be displayed on service graph? I made a custom icinga check_plugin and this plugin display a lot of variables, the service graph shows timestamp :-( 

![screenshot at 2017-06-09 11-03-28](https://user-images.githubusercontent.com/2915349/26981527-78c725c0-4d03-11e7-98df-3f9af2d439b3.png)
There is a way to configure this graphs?

Thanks in advance
Nomar

**Comment by Mikesch-mp** [comment]
Hello Nomar,

all you have to do is create a dashboard and a panel in Grafana that will display your metrics they way you want. Then configure the graph in Icingaweb2 for the service.  About time i write somed sort of documentation. If you still need help, we can do a remote session and i show you howto create them.

Regards,
Carsten

**Comment by kalimalrazif** [comment]
:-o ok :-) I can try, If it explodes me on face I will return :-) thanks :-) the config is via create graph on icingaweb?

**Comment by Mikesch-mp** [comment]
Yes :)

**Comment by kalimalrazif** [comment]
Perfect! I did it :-) thanks :-)
