### ISSUE TITLE
disk, mem and more always displayed as bytes

### ISSUE THREAD

**Issue by marcelfischer** [Mikesch-mp/icingaweb2-module-grafana#80]
## Expected Behavior
Unit should be configurable somehow. Or display in GigaBytes. In Grafana its displayed as gigabytes

## Current Behavior
currently is always bytes
![image](https://user-images.githubusercontent.com/5950740/27002537-0354bd42-4de5-11e7-91d6-f1807b9c0247.png)
![image](https://user-images.githubusercontent.com/5950740/27002552-1d046dbe-4de5-11e7-829e-3d275173a86a.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 Grafana version (System - About): newest
* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by Mikesch-mp** [comment]
Hi,

just create a dashboard or panels in Grafana and configure them in Icingaweb2. atm the moment its not possible to send unit via variable to grafana.

**Comment by marcelfischer** [comment]
Hey,

im using your basic-metrics, it shows everything in GB. Do I still need to add the graphs in your web2 module?

thanks
Marcel

**Comment by codesmaker** [comment]
I also have the same issue. Please check the attached pictures.
![icinga1](https://user-images.githubusercontent.com/6999196/27035414-9018f5d4-4f81-11e7-95f7-0cc6f5c83fcb.png)
![icinga2](https://user-images.githubusercontent.com/6999196/27035415-90610de2-4f81-11e7-8ffd-f9abb99c542d.png)

**Comment by Mikesch-mp** [comment]
@codesmaker icinga-default dashboard cant have units, because it autogenerates the graphs from service/chec_command name. You need to create one in a new dashboard or use the basic-metrics dashboard "disk" (panelID 2)

@marcelfischer if you want them to be used for disk checks, yes you have to add them under graph config
(Configuration -> Grafana Graphs)
![image](https://user-images.githubusercontent.com/6574967/27042551-9440e624-4f97-11e7-9dc4-c2216eca049a.png)

**Comment by codesmaker** [comment]
Thanks @Mikesch-mp for the explanation!

**Comment by codesmaker** [comment]
One more question, If I use the base-metrics dashboards, it won't work with multiple paths right?

**Comment by Mikesch-mp** [comment]
@codesmaker you are right, just create your own panel to use for the module :)

**Comment by Mikesch-mp** [comment]
@marcelfischer did it solve your problem?

**Comment by MarcusCaepio** [comment]
How to do this with disk? E.g. disk:/ ; disk: all ; disk: /var/lib ?

**Comment by Mikesch-mp** [comment]
@MarcusCaepio Just create a dashboard for the commando, see the docs for more details

**Comment by MarcusCaepio** [comment]
Can I use disk:* anyhow in the module config? I don't want to create a graph for every single mountpoint. Right now, because my check command is "by_ssh" I must create a graph in the graphana module for every service instance (disk:/; disk:/var/lib; /TMP and so on)

**Comment by Mikesch-mp** [comment]
@MarcusCaepio if you want we can do a skype session, i dont have any checks that use nrpe/by_ssh. So i could try to setup a dashboard + graph configuration with you.
