### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by prupert** [Mikesch-mp/icingaweb2-module-grafana#81]
Please create an RPM package of `icingaweb2-module-grafana`, and if possible release this package in the Icinga yum repository alongside the `icingaweb2*` packages.

**Comment by dnsmichi** [comment]
1.) a spec file isn't too hard to create, but I doubt that Carsten has the time to learn rpmbuild for now. It is merely a copy and link resource plus config which depends on icingaweb2 then. 
2.) This is a community module, it might or might not bet included in the official icinga project's repository. Adding packages somewhere also means that users will request support for it. It is not forgotten but still in discussion if and how on the Icinga side.

**Comment by Mikesch-mp** [comment]
@dnsmichi  i know rpmbuild already :)
@prupert i could create RPM files, but i couldnt add it to the official icinga repository.

**Comment by dnsmichi** [comment]
@Mikesch-mp ah ok ;)

**Comment by prupert** [comment]
Publishing RPM files with each release would be awesome. 

@dnsmichi I understand that you are hesitant with including community modules in the Icinga yum repository because of support. However, you are endorsing this module on https://www.icinga.com/products/icinga-web-2-modules/

**Comment by dnsmichi** [comment]
We will add more modules onto that page, but that won't mean that packages and support are done by the Icinga project itself. It is a kind wish and might happen, but nothing which is planned atm.

**Comment by mbanck** [comment]
Any news about this? Would be great if there was an RPM available.

**Comment by joernott** [comment]
As my customer an I prefer to distribute software via RPMs instead of tar.gz or zip files, I have created a small build script and SPEC file for the module.

**Comment by Mikesch-mp** [comment]
Packages for the most used os are provides here https://packages.netways.de/
