### ISSUE TITLE
Position of the graph

### ISSUE THREAD

**Issue by towolf** [Mikesch-mp/icingaweb2-module-grafana#83]
Thanks for your module, it's pretty nifty.

My colleagues like it, but some complain that it should be inserted lower on the page. Can this be made configurable?

**Comment by Mikesch-mp** [comment]
Hello @towolf ,

you have to tell you colleagues that is not possible :(

Regards,
Carsten

**Comment by p0nt** [comment]
What you could do is put the content in a div that is hidden by default and shown on click.

https://www.w3schools.com/jquery/jquery_hide_show.asp

And make that as an option.

Just a thought, personally I am happy with how it is.
