### ISSUE TITLE
Possibility to define organization ID

### ISSUE THREAD

**Issue by sysadmama** [Mikesch-mp/icingaweb2-module-grafana#84]
Hi Carsten,

in my Grafana, I defined two organizations: the first (`orgId=1`) is the "default" one with restricted access, the second (`orgId=2`) is for public access with 
```
[auth.anonymous]
enabled = true
org_name = Public Universe
org_role = Viewer
```

My Grafana graphs - dashboard icinga2-default is in the restricted universe aka `orgId=1` - in Icinga Web 2 worked well until I created the second organization. Now they are broken as it tries to reach the wrong `orgId`.
![screen shot 2017-07-10 at 10 39 46](https://user-images.githubusercontent.com/11242139/28009640-5ffc7916-655c-11e7-9086-bbbd350c9840.jpg)

Cheers,
  Marianne

## Possible Solution

In module config, I can store the default dashboard to use; would it be possible to store the default organization, too?

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.1.7 // 92bda4ce3c0a32a86fe430721f2c7b689f1dd2fb
* Icinga Web 2 version and modules (System - About): 2.4.0 // 7a2d8eda8dd8c37198d0e754218cdedd12e3fde4 // director, businessprocess
* Version used (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian GNU/Linux 8
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`): Finished validating the configuration file(s).

**Comment by Mikesch-mp** [comment]
HI Marianne,

iam aware of that problem already. @epinter had send a PR to fix this. but iam short on time these days (last days in old company). I will make an release thursday or friday this week with the PR included.

Regards,
Carsten

**Comment by sysadmama** [comment]
Hi Carsten,

great, thank you for this information. So I'll try to be patient... _bouncing foot_... ;-)

Cheers,
Marianne

**Comment by Mikesch-mp** [comment]
Fixed everything in master.
