### ISSUE TITLE
First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by d-zalewski** [Mikesch-mp/icingaweb2-module-grafana#85]
Hi,

I'm trying to get this module working with grafana in proxy mode but I'm getting following message in icingaweb2 window:

First parameter must either be an object or the name of an existing class

icingaweb2 grafana module 1.1.10 (latest github checkout)
grafana-4.3.2
icingaweb2 2.4.1
php-7.0.21
icinga2 2.6.3 on RHEL 7.3

Enabled features: api checker command ido-mysql influxdb mainlog notification

`2017-07-19T13:53:29+01:00 - ERROR - ErrorException in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php:251 with message: First parameter must either be an object or the name of an existing class
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'First parameter...', '/usr/share/icin...', 251, Array)
#1 /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php(251): property_exists(NULL, 'message')
#2 /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php(372): Icinga\Module\Grafana\ProvidedHook\Grapher->getMyPreviewHtml('hostalive', 'devldnvlmon1.uk...', '')
#3 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/grapher.phtml(2): Icinga\Module\Grafana\ProvidedHook\Grapher->getPreviewHtml(Object(Icinga\Module\Monitoring\Object\Host))
#4 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#5 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(3): Zend_View_Abstract->render()
#7 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#9 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/host/show.phtml(14): Zend_View_Abstract->render()
#10 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#11 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('host/show.phtml', NULL)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#22 {main}
`

**Comment by Mikesch-mp** [comment]
Hi,

did you configure the module? Can you please post the config.ini from /etc/icingaweb2/modules/grafana
Also did you have libcurl installed ?

**Comment by d-zalewski** [comment]
libcurl-7.29.0-35.el7.x86_64

`[grafana]
host = "my-grafana-server"
protocol = "https"
defaultdashboard = "icinga2-default"
defaultorgid = "1"
defaultdashboardstore = "db"
theme = "light"
datasource = "influxdb"
accessmode = "proxy"
shadows = "1"
authanon = "yes"
height = "280"
width = "640"
enableLink = "no"
`

**Comment by Mikesch-mp** [comment]
Shouldnt it be "invldnvltsdb1:3000" for the host?

**Comment by d-zalewski** [comment]
there is nginx proxy with ssl in front of grafana server so its https://invldnvltsdb1 and grafana listens on localhost:3000

When I choose iframe mode I can see log on page even thought anonymous auth is enabled. I have ldap auth enabled in grafana at the same time. I tried using using a username/password rather than anonymous but I'm getting wrong user/pass in icingaweb2 window. Same credentials work fine when I log on directly to grafana.

Thoughts?

**Comment by Mikesch-mp** [comment]
Did you set the organization to match yours? i had an error while testing with the wrong name in grafana.ini.

```
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Koebbes

# specify role for unauthenticated users
org_role = Viewer
```

For non anonymous you need also the enable basic auth

```
#################################### Basic Auth ##########################
[auth.basic]
enabled = true
```

Dont forget to restart the grafana server after changes made (i forget that all the time and the n i search the error for hours)

**Comment by d-zalewski** [comment]
I've set org_name under [auth.anonymous] as it was missing indeed and enabled basic auth but still getting same error. I have auth ldap enabled at the same time which I think might be causing a problem as when I browser to a grafana dashboard from other browser, it keep asking me to log on.

Problem is that proxy mode isn't working when using user/pass neither

**Comment by Mikesch-mp** [comment]
Can we do a remtote desktop session?

**Comment by Mikesch-mp** [comment]
Or can you temporarily disable ldap?

**Comment by sargon** [comment]
Same problem here. Also enabled ldap in grafana, worked well until now.

But aside from the interconnection problem, this should not crash the view of the icingaweb2 node,
so either the grafana plugin needs some additional check or even better icingaweb2 should not produce an error when a plugin throws. Later is a upstream problem.

So following my own statement, I inserted
```
if ( $error === NULL ) $error = array();
```
into L250 in grafana/library/Grafana/ProvidedHook/Grapher.php. 
Now fine graphs again. Seems like the json_decode in L249 return NULL instead of a structure.
I guess there is a change of behavior for that function...

**Comment by Mikesch-mp** [comment]
Hmm i have many installations with ldap also running and they dont show the errors you have.
I guess its more a problem of grafana configuration. Can you plese post full grafana.ini and ldap.toml (please remove passwords etc first).

For reference you can compare to my grafana config files
[grafana.zip](https://github.com/Mikesch-mp/icingaweb2-module-grafana/files/1169934/grafana.zip)

**Comment by d-zalewski** [comment]
it turns out it was puppet issue! we had two grafana config in one file! sorry for trobule

**Comment by sargon** [comment]
I had a look into the php docs, json_decode does return NULL in some situations, so that normal behavior, which isn't handled in that code.

grafana.ini: https://paste.toppoint.de/?39c2931d85b3186d#fx3xpujF/tjLcaouEi6mW/8sZaxY08kzLkZT5bwX7ig=
ldap.toml: https://paste.toppoint.de/?e9e35d15021ebd16#TSh6kGc8x840Pj+gw9WUyxEj0MYchsDRRbN7vobeyF0=

By the way, the user used by the plugin is not in the ldap database, but it is a additional configured local one. Maybe that the specialty here, @d-zalewski is that the case in your setup?

**Comment by d-zalewski** [comment]
@sargon it was my grafana config had double entries for some properties.

**Comment by sargon** [comment]
Okay that is not the case here and I get the exact same stacktrace. Maybe we just triggered the same bug, for other reasons. Can some one please reopen this issue.

**Comment by Mikesch-mp** [comment]
@sargon where do you store local users if you disable sqlite at all? Can you login into grafana using that local user? I have also (always) a local user for the access from the module.

**Comment by sargon** [comment]
You can't disable the database, those commented lines are the default values i guess.
So I store them in the database and I can login with that extra user, just tested it.

**Comment by Mikesch-mp** [comment]
Can you post your config.ini, graphs.ini and which service/command you expierence the problem please

**Comment by sargon** [comment]
https://paste.toppoint.de/?c9abc841a24fc122#O7XEECuUCX/KfiWLs8zbGh2OQbsKyjTcxBfspSbX3r8=

We experience the problem with every graph.

**Comment by Mikesch-mp** [comment]
Please delete that hostalive graph configuration :) just configure the graph using base-metrics.
Is the user configured in the organization id 1?

**Comment by sargon** [comment]
No the user don't exists in the LDAP directory. 

Okay, that funny. I removed the graph.ini settings. Undo my quickfix, works. 
I restore the graph.ini again, works.

But last time before the quickfix, I also thought it is gone, but a moment later it was back again.

**Comment by Mikesch-mp** [comment]
@sargon so we canclose this issue?
