### ISSUE TITLE
disable graphs at service manually or automatic?

### ISSUE THREAD

**Issue by mkayontour** [Mikesch-mp/icingaweb2-module-grafana#9]
Hi there, 

is there anything implemented which allows me to disable graphs for a specific service? 
Would be great to disable some service instead of having a empty. 
![empty-graph](https://cloud.githubusercontent.com/assets/7584938/23752854/47d5f064-04d7-11e7-9a0f-52f89fbe0201.png)

I'm not a developer otherwise i would implement something and contribute.

**Comment by mkayontour** [comment]
Problem solved: graphs get disabled if no perfomance_data is active at the service

But if I need the performance data but not the graph in the webinterface is still a issue for me. ;)

**Comment by mkayontour** [comment]
link to PR [#11](https://github.com/Mikesch-mp/icingaweb2-module-grafana/pull/11)

**Comment by Aleksey-Maksimov** [comment]
I do not agree that the problem is solved.
In my opinion, it is better to make graphics visible only to those services for which they are explicitly configured in /icingaweb2/grafana/graph.
For example, I have a lot of services and many of them graphic is not needed.

**Comment by Mikesch-mp** [comment]
I have 2 ideas now for that problem. 

- config option to show only configured graphs 
- config option for a custom variable, that if set the graph will not be displayed

Would that fit your needs ?

**Comment by janvonde** [comment]
+1 for the custom variable in icinga2

**Comment by Aleksey-Maksimov** [comment]
Both options :)
