### ISSUE TITLE
Error viewing host after enable grafana module

### ISSUE THREAD

**Issue by R00T88** [Mikesch-mp/icingaweb2-module-grafana#92]
Hello,
i have graphite installed correctly and availabe on 127.0.0.1:8888.
Grafana is available on 127.0.0.1:3000 and use graphite as datastore

![image](https://user-images.githubusercontent.com/9050487/29406468-7589d938-8341-11e7-900a-ee2b09ff78ed.png)

this is the configuration for grafana module

![image](https://user-images.githubusercontent.com/9050487/29406502-8e19de76-8341-11e7-99bc-55e1ec7e8c90.png)

Now when i click on host to view status ecc i got this error

![image](https://user-images.githubusercontent.com/9050487/29406534-a93eabbe-8341-11e7-8d4c-64cb59276e90.png)

Thanks

**Comment by Mikesch-mp** [comment]
Please post your grafana.ini and Screenshot of available dashboards & data source with successful test

**Comment by R00T88** [comment]
fixed upgrading grafana module

Thanks
