### ISSUE TITLE
Error importing dashboard grafana

### ISSUE THREAD

**Issue by R00T88** [Mikesch-mp/icingaweb2-module-grafana#93]
Hello,
i try to import graphite dashboard icinga2-default.json and base-metrics.json into grafana but i get this error and import fail 

![image](https://user-images.githubusercontent.com/9050487/29406659-f10f254a-8341-11e7-8b01-78a2fb99f1f9.png)

Datasource ic correctly configured

![image](https://user-images.githubusercontent.com/9050487/29406675-00a7cbd8-8342-11e7-8113-591c43f1c78c.png)

Thanks

**Comment by Mikesch-mp** [comment]
Do you have any Datasource defined in Grafana? See http://docs.grafana.org/features/datasources/graphite/

**Comment by R00T88** [comment]
fixed upgrading grafana 

Thanks
