### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by R00T88** [Mikesch-mp/icingaweb2-module-grafana#94]
Hello,
sometimes we get an errore retreiving the graph about curl timeout.
What is the best timeout?
Actually is set to 5 sec

Thanks

**Comment by R00T88** [comment]
![image](https://user-images.githubusercontent.com/9050487/29453629-9d24f1fc-840a-11e7-9e8d-ba4b26a9e82a.png)

**Comment by Mikesch-mp** [comment]
The default is 5 secs, if you get timeout errors you should increase the value.
For example on my small test setup on a celeron with only2gb ram i need 6 seconds. On my big server with 20 cores/256gb ram i need less then a second.
