### ISSUE TITLE
Custom Variable not working with Icinga service sub-variables

### ISSUE THREAD

**Issue by idMaxCZ** [Mikesch-mp/icingaweb2-module-grafana#95]
I tried use CustomVariable for graph with included performance data: 

_&var-test=$service.performance_data$_

..but in case of this configuration Graph on service page return error 
_Cannot fetch graph with curl: 'Operation timed out after 5164 milliseconds with 0 out of -1 bytes received'._

I also tried simple test with 
_&var-test=$service.name$_
and this configuration returned same error. 

What I doing wrong? Or this way is impossible?

Thanks

**Comment by Mikesch-mp** [comment]
Did you install Grafana & InfluxDB/Graphite? Did you configure Icinga2 to write perfdata to InfluxDB/Graphite? Did you read the docs?

**Comment by Mikesch-mp** [comment]
OK, then you should know that if you use custom variable, you need to use templating in your Grafana dashboard. So you can control with a custo mvariable what will be shown in your dashboard.

**Comment by idMaxCZ** [comment]
Templeting is configured correctly I hope. If i set custom variable like 
&var-test=123 then graph is generated successfully, but with variable like &var-test=$service.performance_data$ or &var-test=$service.name$ plugin timing out. 

Can you try this variables on your environment please?

**Comment by Mikesch-mp** [comment]
Please provide Grafana Version, module version and your dashboard.

**Comment by idMaxCZ** [comment]
grafana-4.4.1-1.x86_64.rpm
icingaweb2-module-grafana-1.1.8.tar
Dashboard is your icinga-default.json for influxDB 

Thanks for support

**Comment by Mikesch-mp** [comment]
OK then you dont need to test with custom-variables, because that template only have vars enabled for hostname,servicename, command_name nad (but not used from module side) perf metric name. Grafana has the bad behavior that if you send variables, which are not used to load forever and dont give back a error faster or ignore thatvariable.
