### ISSUE TITLE
Add check_command as query parameter for use in dashboards

### ISSUE THREAD

**Issue by friesoft** [Mikesch-mp/icingaweb2-module-grafana#98]
## Expected Behavior
Have check_command as query parameter for use in dashboards. Using this it would be possible to have one generic dashboard for all check_commands.

## Current Behavior
Only Host and service are given, therefore the check_command has to be specified manually in the query (influxdb)

## Possible Solution
Add check_command as an additional query parameter.

## Steps to Reproduce (for bugs)
All dashboards have the check_command specified manually.

## Context
Many check_commands => many dashboards

**Comment by Mikesch-mp** [comment]
And your Problem is?

**Comment by friesoft** [comment]
We want to have graphs by default for every check_command and only create custom graphs if we need special representation. The out of the box experience should imho be that all performance data can be displayed with a single dashboard.

**Comment by dnsmichi** [comment]
Isn't that more of a static Grafana dashboard with custom queries, and not related to this kind of module with detail view graphs?

**Comment by Mikesch-mp** [comment]
Just read the documentation ..... https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/04-graph-configuration.md#name-search-order

So the service check_command is used. but you still have to configure them inside the module.
Your problem is (from what i see in the other issues you comment/opened) check_by_ssh, which then will result that the real command is hidded behind tcheck_by_ssh. so all entries in the influxdb as check_command = check_by_ssh. Now you can change your influxwriter configuration, or change your dashboards and use customvar option from the module. But at the end it is RTFM (module, Grafana & InfluxDB).

By the way, the icinga-default dashboard is a single graph for every commnad. if you want to have all metrics shown in it, just change the panel query a litle bit (it is realy easy).

**Comment by friesoft** [comment]
I already read the docs before creating the ticket but it didn't work as I thought it would.
As stated in the other bugreport I have "Spring Boot /mypath.jar" and I'm trying to match with "Spring Boot" which isn't working. Only if I change the name to "Spring" the correct dashboard is chosen - to me the behavior feels like a bug but maybe I did understand something wrong.

How it will help me to change the influxwriter configuration - do you propose to remove the check_command from the template? What's my measurement then? Some static value?
```
  host_template = {
    measurement = "onecheckcommandforeverything"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "onecheckcommandforeverything"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
    }
  }
```

I also tried the customvar option but I don't see how this helps me as I don't have a custom variable to use for the dashboard containing the check_command. I tried to put "$service.check_command$" and "$check_command$" into it and also looked into the code where the customvar is parsed but as I understood only icinga2 custom vars are processed - so that doesn't help me either :(

Thanks for your time and I understand it is annoying if not everyone has the same understanding as you do, but just reading the docs and thinking/trying basically all the things you proposed didn't help me. 
That's the reason I opened this ticket as having the check_command in the URL from the module would solve my problem. If this is not the way it should be done I haven't grasped yet how to properly do it and would appreciate any help :)

**Comment by Mikesch-mp** [comment]
Hi,
if you would read the docs you would know that you can use full service name = "Spring Boot /mypath.jar" or parametrized service name which would be "Spring" or the check command from that service which  is i think check_by_ssh in your environment.
The influxwrite would help you to get the real check command written into influxdb. my influxwrite loooks like this:

```
/**
 * The InfluxdbWriter type writes check result metrics and
 * performance data to an InfluxDB HTTP API
 */

library "perfdata"

object InfluxdbWriter "influxdb" {
  host = "127.0.0.1"
  port = 8086
  database = "icinga2"
  username = "icinga2"
  password = "*icinga2*"

  enable_send_thresholds = true
  enable_send_metadata = true

  flush_interval = 20

  host_template = {
    measurement = "$host.check_command$"
    tags = {
      hostname = "$host.name$"
    }
  }
  service_template = {
    measurement = "$service.vars.influx_command$"
    tags = {
      hostname = "$host.name$"
      service = "$service.name$"
      instance = "$service.vars.instance$"
    }
  }
}
```
A service which does not use nrpe or by_ssh have this line after the check_command line

```
vars.influx_command = "$service.check_command$"
```
and a service with nrpe (after vars.nrpe_command) for example has this line
```
vars.influx_command = "$service.vars.nrpe_command$"
```

So i get always the real command written to influxdb. Its a dirty trick, but it works and you can put it also in templates for services.

The custom-var option is not for Iciinga2 Custom Variables, It for Grafana. For example you can put in the config for a service graph this:
```
&var-check_command=$service.check_command$
```
you can send with this option ny runtime variable from your service or host to grafana and use it for Grafana templating.

Best regards,
Carsten

**Comment by friesoft** [comment]
> if you would read the docs you would know that you can use full service name = "Spring Boot /mypath.jar" or parametrized service name which would be "Spring" or the check command from that service which is i think check_by_ssh in your environment.

The example service name in the docs doesn't contain any spaces so it isn't clear if only the first word is used for matching or if every word (separated by space) can be used for matching (which was my expectation). Therefore I tried to use "Spring Boot" because my apply for rule generated services like "Spring Boot /mypath.jar". Maybe it would be good to add some hint to the docs that either the full service name OR **the first word** OR the check_command can be used.

Thanks for the InfluxDbWriter tip. Thats a nice one which will be useful to differentiate the different by_ssh services. Atm my bigger problem though are my services which use different check_commands :)

> The custom-var option is not for Iciinga2 Custom Variables, It for Grafana. For example you can put in the config for a service graph this:

I tried the customvar exactly like you provided (already before the ticket). It doesn't work for me :(
That is the url generated by the module with the customvar option set like you mentioned: The check_command variable is not resolved. (Yes I tried with a service graph and not with a host graph)
`ImgageURL: http://ourgrafanahost:3000/render/dashboard-solo/db/icinga2-influxdb-default?var-hostname=ourhostname&var-service=Login&var-check_command=$service.check_command$&panelId=1&orgId=1&width=900&height=280&theme=light&from=now-6h&to=now`

Should this work?

Thanks & Best regards,
Bernhard

**Comment by friesoft** [comment]
https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/library/Grafana/ProvidedHook/Grapher.php#L369

The fetchCustomvars()->customvars only contains my custom vars of the host/service - NOT the "normal"properties of a host/service (like check_command). The object itself contains the information needed.
If I add a print here like this:
`print_r($object->service_check_command);`
I corrctly get the check_command.

This is my workaround patch now (very hacky):
```
diff --git a/library/Grafana/ProvidedHook/Grapher.php b/library/Grafana/ProvidedHook/Grapher.php
index 51ebacf..e2c9e4c 100644
--- a/library/Grafana/ProvidedHook/Grapher.php
+++ b/library/Grafana/ProvidedHook/Grapher.php
@@ -357,6 +358,8 @@ class Grapher extends GrapherHook
             return;
         }

+        $this->customVars = '&var-check_command=$service.check_command$';
+
         if($this->repeatable == "yes" ) {
             $this->panelId = implode(',', range($this->panelId, ($this->panelId -1) + intval(substr_count($object->perfdata, '=')/$this->nmetrics)));
         }
@@ -367,6 +370,12 @@ class Grapher extends GrapherHook
         }

         $customVars = $object->fetchCustomvars()->customvars;
+        if ($object instanceof Host) {
+            $customVars["host.check_command"] = $object->host_check_command;
+            $customVars["service.check_command"] = $object->host_check_command;
+        } else {
+            $customVars["service.check_command"] = $object->service_check_command;
+        }
         // replace template to customVars from Icinga2
         foreach ($customVars as $k => $v) {
             $search[] = "\$$k\$";
```

First part of the diff: 
Setting the customVars hardcoded to var-check_command=$service.check-command$ is needed for the default dashboard as it is not possible to set customvars for the default dashboard.

Second part of the diff:
set host.check_command and service.check_command from the object variables.

Using this approach I have my 1 default dashboard which works out of the box for all services (no matter what check_command is used).

Maybe it is now clearer what I want to achieve..

**Comment by Mikesch-mp** [comment]
Hi,

your right about the custom-vars. But use your brain, just put `vars.mycommand = check_command` into your service object .

And about the docs, ther is a space in the service name, dont cal me a liar. This will only let me loose my will to help you. But to make it clearer for you to read here a copy of the docs in bigger letters from 04-graph-configuration.md:

# **Name search order**

# **This module prefers the service name, then looks for an optional parametrized service name and for the service check command name.**

# **At first glance Name = "if-usage ens3" must provide a match. Then if-usage (parametrized service name) and last but not least any service check_command attribute which is set to nwc_health.**


But anyways why you dont use the provided default dashboard? I works and is easy to edit if you want to see more then one metric?

**Comment by friesoft** [comment]
Hi,

> And about the docs, ther is a space in the service name, dont cal me a liar.

I don't call you a liar but the provided example is a single word ("if-usage") and then the part appended from the apply for rule ("ens3"). In my case I have two words ("Spring Boot") and then the part appended by the apply rule ("/mypath.jar"). As I understood it from the docs the parametrized service name should be "Spring Boot" and not only "Spring". Therefore my tries with "Spring Boot" as custom graph name at first.
Well different topic..

I was using the provided default dashboard.. it was months old though (of the initial release of the module where no graphite/influxdb separation existed). With the current icinga2-default dashboard it is working :)
Looks like with the template variables of this default dashboard it is not needed to pass the check_command variable over as it is evaluated at dashboard load. I didn't know that was possible.

Sorry for the ticket and thanks for your help! Closing the ticket.
